// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: crsystem/v1/common.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Pagination with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Pagination) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Pagination with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaginationMultiError, or
// nil if none found.
func (m *Pagination) ValidateAll() error {
	return m.validate(true)
}

func (m *Pagination) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return PaginationMultiError(errors)
	}

	return nil
}

// PaginationMultiError is an error wrapping multiple validation errors
// returned by Pagination.ValidateAll() if the designated constraints aren't met.
type PaginationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaginationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaginationMultiError) AllErrors() []error { return m }

// PaginationValidationError is the validation error returned by
// Pagination.Validate if the designated constraints aren't met.
type PaginationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationValidationError) ErrorName() string { return "PaginationValidationError" }

// Error satisfies the builtin error interface
func (e PaginationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPagination.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationValidationError{}

// Validate checks the field values on PaginationResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PaginationResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PaginationResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PaginationRespMultiError,
// or nil if none found.
func (m *PaginationResp) ValidateAll() error {
	return m.validate(true)
}

func (m *PaginationResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for TotalPages

	if len(errors) > 0 {
		return PaginationRespMultiError(errors)
	}

	return nil
}

// PaginationRespMultiError is an error wrapping multiple validation errors
// returned by PaginationResp.ValidateAll() if the designated constraints
// aren't met.
type PaginationRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PaginationRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PaginationRespMultiError) AllErrors() []error { return m }

// PaginationRespValidationError is the validation error returned by
// PaginationResp.Validate if the designated constraints aren't met.
type PaginationRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaginationRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaginationRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaginationRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaginationRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaginationRespValidationError) ErrorName() string { return "PaginationRespValidationError" }

// Error satisfies the builtin error interface
func (e PaginationRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaginationResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaginationRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaginationRespValidationError{}

// Validate checks the field values on OperateResult with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OperateResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OperateResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OperateResultMultiError, or
// nil if none found.
func (m *OperateResult) ValidateAll() error {
	return m.validate(true)
}

func (m *OperateResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return OperateResultMultiError(errors)
	}

	return nil
}

// OperateResultMultiError is an error wrapping multiple validation errors
// returned by OperateResult.ValidateAll() if the designated constraints
// aren't met.
type OperateResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OperateResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OperateResultMultiError) AllErrors() []error { return m }

// OperateResultValidationError is the validation error returned by
// OperateResult.Validate if the designated constraints aren't met.
type OperateResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OperateResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OperateResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OperateResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OperateResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OperateResultValidationError) ErrorName() string { return "OperateResultValidationError" }

// Error satisfies the builtin error interface
func (e OperateResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOperateResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OperateResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OperateResultValidationError{}
