// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: crsystem/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 评审单状态枚举（LLD §3.3 状态流转硬编码约束）
type ReviewStatus int32

const (
	ReviewStatus_REVIEW_STATUS_UNSPECIFIED ReviewStatus = 0
	ReviewStatus_REVIEW_STATUS_PENDING     ReviewStatus = 1 // 待评审
	ReviewStatus_REVIEW_STATUS_IN_PROGRESS ReviewStatus = 2 // 评审进行中
	ReviewStatus_REVIEW_STATUS_REJECTED    ReviewStatus = 3 // 驳回待修改
	ReviewStatus_REVIEW_STATUS_RESUBMITTED ReviewStatus = 4 // 提交复审
	ReviewStatus_REVIEW_STATUS_APPROVED    ReviewStatus = 5 // 复审通过
	ReviewStatus_REVIEW_STATUS_ARCHIVED    ReviewStatus = 6 // 正式归档关闭
)

// Enum value maps for ReviewStatus.
var (
	ReviewStatus_name = map[int32]string{
		0: "REVIEW_STATUS_UNSPECIFIED",
		1: "REVIEW_STATUS_PENDING",
		2: "REVIEW_STATUS_IN_PROGRESS",
		3: "REVIEW_STATUS_REJECTED",
		4: "REVIEW_STATUS_RESUBMITTED",
		5: "REVIEW_STATUS_APPROVED",
		6: "REVIEW_STATUS_ARCHIVED",
	}
	ReviewStatus_value = map[string]int32{
		"REVIEW_STATUS_UNSPECIFIED": 0,
		"REVIEW_STATUS_PENDING":     1,
		"REVIEW_STATUS_IN_PROGRESS": 2,
		"REVIEW_STATUS_REJECTED":    3,
		"REVIEW_STATUS_RESUBMITTED": 4,
		"REVIEW_STATUS_APPROVED":    5,
		"REVIEW_STATUS_ARCHIVED":    6,
	}
)

func (x ReviewStatus) Enum() *ReviewStatus {
	p := new(ReviewStatus)
	*p = x
	return p
}

func (x ReviewStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_crsystem_v1_common_proto_enumTypes[0].Descriptor()
}

func (ReviewStatus) Type() protoreflect.EnumType {
	return &file_crsystem_v1_common_proto_enumTypes[0]
}

func (x ReviewStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewStatus.Descriptor instead.
func (ReviewStatus) EnumDescriptor() ([]byte, []int) {
	return file_crsystem_v1_common_proto_rawDescGZIP(), []int{0}
}

// 评审优先级
type ReviewPriority int32

const (
	ReviewPriority_REVIEW_PRIORITY_UNSPECIFIED ReviewPriority = 0
	ReviewPriority_REVIEW_PRIORITY_LOW         ReviewPriority = 1 // 低优先级
	ReviewPriority_REVIEW_PRIORITY_NORMAL      ReviewPriority = 2 // 普通
	ReviewPriority_REVIEW_PRIORITY_HIGH        ReviewPriority = 3 // 高优先级
	ReviewPriority_REVIEW_PRIORITY_URGENT      ReviewPriority = 4 // 紧急
)

// Enum value maps for ReviewPriority.
var (
	ReviewPriority_name = map[int32]string{
		0: "REVIEW_PRIORITY_UNSPECIFIED",
		1: "REVIEW_PRIORITY_LOW",
		2: "REVIEW_PRIORITY_NORMAL",
		3: "REVIEW_PRIORITY_HIGH",
		4: "REVIEW_PRIORITY_URGENT",
	}
	ReviewPriority_value = map[string]int32{
		"REVIEW_PRIORITY_UNSPECIFIED": 0,
		"REVIEW_PRIORITY_LOW":         1,
		"REVIEW_PRIORITY_NORMAL":      2,
		"REVIEW_PRIORITY_HIGH":        3,
		"REVIEW_PRIORITY_URGENT":      4,
	}
)

func (x ReviewPriority) Enum() *ReviewPriority {
	p := new(ReviewPriority)
	*p = x
	return p
}

func (x ReviewPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_crsystem_v1_common_proto_enumTypes[1].Descriptor()
}

func (ReviewPriority) Type() protoreflect.EnumType {
	return &file_crsystem_v1_common_proto_enumTypes[1]
}

func (x ReviewPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewPriority.Descriptor instead.
func (ReviewPriority) EnumDescriptor() ([]byte, []int) {
	return file_crsystem_v1_common_proto_rawDescGZIP(), []int{1}
}

// 缺陷等级（SRS F02-03 / SQA §4.1）
type DefectLevel int32

const (
	DefectLevel_DEFECT_LEVEL_UNSPECIFIED DefectLevel = 0
	DefectLevel_DEFECT_LEVEL_FATAL       DefectLevel = 1 // 致命缺陷 P0
	DefectLevel_DEFECT_LEVEL_CRITICAL    DefectLevel = 2 // 严重缺陷 P1
	DefectLevel_DEFECT_LEVEL_MAJOR       DefectLevel = 3 // 一般缺陷 P2
	DefectLevel_DEFECT_LEVEL_MINOR       DefectLevel = 4 // 优化建议 P3
)

// Enum value maps for DefectLevel.
var (
	DefectLevel_name = map[int32]string{
		0: "DEFECT_LEVEL_UNSPECIFIED",
		1: "DEFECT_LEVEL_FATAL",
		2: "DEFECT_LEVEL_CRITICAL",
		3: "DEFECT_LEVEL_MAJOR",
		4: "DEFECT_LEVEL_MINOR",
	}
	DefectLevel_value = map[string]int32{
		"DEFECT_LEVEL_UNSPECIFIED": 0,
		"DEFECT_LEVEL_FATAL":       1,
		"DEFECT_LEVEL_CRITICAL":    2,
		"DEFECT_LEVEL_MAJOR":       3,
		"DEFECT_LEVEL_MINOR":       4,
	}
)

func (x DefectLevel) Enum() *DefectLevel {
	p := new(DefectLevel)
	*p = x
	return p
}

func (x DefectLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefectLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_crsystem_v1_common_proto_enumTypes[2].Descriptor()
}

func (DefectLevel) Type() protoreflect.EnumType {
	return &file_crsystem_v1_common_proto_enumTypes[2]
}

func (x DefectLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefectLevel.Descriptor instead.
func (DefectLevel) EnumDescriptor() ([]byte, []int) {
	return file_crsystem_v1_common_proto_rawDescGZIP(), []int{2}
}

// Git平台类型
type GitPlatform int32

const (
	GitPlatform_GIT_PLATFORM_UNSPECIFIED GitPlatform = 0
	GitPlatform_GIT_PLATFORM_GITLAB      GitPlatform = 1
	GitPlatform_GIT_PLATFORM_GITEE       GitPlatform = 2
	GitPlatform_GIT_PLATFORM_GITHUB      GitPlatform = 3
)

// Enum value maps for GitPlatform.
var (
	GitPlatform_name = map[int32]string{
		0: "GIT_PLATFORM_UNSPECIFIED",
		1: "GIT_PLATFORM_GITLAB",
		2: "GIT_PLATFORM_GITEE",
		3: "GIT_PLATFORM_GITHUB",
	}
	GitPlatform_value = map[string]int32{
		"GIT_PLATFORM_UNSPECIFIED": 0,
		"GIT_PLATFORM_GITLAB":      1,
		"GIT_PLATFORM_GITEE":       2,
		"GIT_PLATFORM_GITHUB":      3,
	}
)

func (x GitPlatform) Enum() *GitPlatform {
	p := new(GitPlatform)
	*p = x
	return p
}

func (x GitPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GitPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_crsystem_v1_common_proto_enumTypes[3].Descriptor()
}

func (GitPlatform) Type() protoreflect.EnumType {
	return &file_crsystem_v1_common_proto_enumTypes[3]
}

func (x GitPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GitPlatform.Descriptor instead.
func (GitPlatform) EnumDescriptor() ([]byte, []int) {
	return file_crsystem_v1_common_proto_rawDescGZIP(), []int{3}
}

// 代码变更类型
type DiffChangeType int32

const (
	DiffChangeType_DIFF_CHANGE_TYPE_UNSPECIFIED DiffChangeType = 0
	DiffChangeType_DIFF_CHANGE_TYPE_ADD         DiffChangeType = 1 // 新增行
	DiffChangeType_DIFF_CHANGE_TYPE_DELETE      DiffChangeType = 2 // 删除行
	DiffChangeType_DIFF_CHANGE_TYPE_MODIFY      DiffChangeType = 3 // 修改行
)

// Enum value maps for DiffChangeType.
var (
	DiffChangeType_name = map[int32]string{
		0: "DIFF_CHANGE_TYPE_UNSPECIFIED",
		1: "DIFF_CHANGE_TYPE_ADD",
		2: "DIFF_CHANGE_TYPE_DELETE",
		3: "DIFF_CHANGE_TYPE_MODIFY",
	}
	DiffChangeType_value = map[string]int32{
		"DIFF_CHANGE_TYPE_UNSPECIFIED": 0,
		"DIFF_CHANGE_TYPE_ADD":         1,
		"DIFF_CHANGE_TYPE_DELETE":      2,
		"DIFF_CHANGE_TYPE_MODIFY":      3,
	}
)

func (x DiffChangeType) Enum() *DiffChangeType {
	p := new(DiffChangeType)
	*p = x
	return p
}

func (x DiffChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiffChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_crsystem_v1_common_proto_enumTypes[4].Descriptor()
}

func (DiffChangeType) Type() protoreflect.EnumType {
	return &file_crsystem_v1_common_proto_enumTypes[4]
}

func (x DiffChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiffChangeType.Descriptor instead.
func (DiffChangeType) EnumDescriptor() ([]byte, []int) {
	return file_crsystem_v1_common_proto_rawDescGZIP(), []int{4}
}

// 通用分页请求参数
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码，从1开始
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页条数，默认20，最大100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_crsystem_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 通用分页响应参数
type PaginationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                             // 总记录数
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                               // 当前页码
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // 每页条数
	TotalPages    uint32                 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"` // 总页数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationResp) Reset() {
	*x = PaginationResp{}
	mi := &file_crsystem_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationResp) ProtoMessage() {}

func (x *PaginationResp) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationResp.ProtoReflect.Descriptor instead.
func (*PaginationResp) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PaginationResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationResp) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// 通用操作结果
type OperateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateResult) Reset() {
	*x = OperateResult{}
	mi := &file_crsystem_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateResult) ProtoMessage() {}

func (x *OperateResult) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateResult.ProtoReflect.Descriptor instead.
func (*OperateResult) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *OperateResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperateResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_crsystem_v1_common_proto protoreflect.FileDescriptor

const file_crsystem_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18crsystem/v1/common.proto\x12\vcrsystem.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"x\n" +
	"\x0ePaginationResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\rR\n" +
	"totalPages\"C\n" +
	"\rOperateResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xda\x01\n" +
	"\fReviewStatus\x12\x1d\n" +
	"\x19REVIEW_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REVIEW_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19REVIEW_STATUS_IN_PROGRESS\x10\x02\x12\x1a\n" +
	"\x16REVIEW_STATUS_REJECTED\x10\x03\x12\x1d\n" +
	"\x19REVIEW_STATUS_RESUBMITTED\x10\x04\x12\x1a\n" +
	"\x16REVIEW_STATUS_APPROVED\x10\x05\x12\x1a\n" +
	"\x16REVIEW_STATUS_ARCHIVED\x10\x06*\x9c\x01\n" +
	"\x0eReviewPriority\x12\x1f\n" +
	"\x1bREVIEW_PRIORITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13REVIEW_PRIORITY_LOW\x10\x01\x12\x1a\n" +
	"\x16REVIEW_PRIORITY_NORMAL\x10\x02\x12\x18\n" +
	"\x14REVIEW_PRIORITY_HIGH\x10\x03\x12\x1a\n" +
	"\x16REVIEW_PRIORITY_URGENT\x10\x04*\x8e\x01\n" +
	"\vDefectLevel\x12\x1c\n" +
	"\x18DEFECT_LEVEL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DEFECT_LEVEL_FATAL\x10\x01\x12\x19\n" +
	"\x15DEFECT_LEVEL_CRITICAL\x10\x02\x12\x16\n" +
	"\x12DEFECT_LEVEL_MAJOR\x10\x03\x12\x16\n" +
	"\x12DEFECT_LEVEL_MINOR\x10\x04*u\n" +
	"\vGitPlatform\x12\x1c\n" +
	"\x18GIT_PLATFORM_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13GIT_PLATFORM_GITLAB\x10\x01\x12\x16\n" +
	"\x12GIT_PLATFORM_GITEE\x10\x02\x12\x17\n" +
	"\x13GIT_PLATFORM_GITHUB\x10\x03*\x86\x01\n" +
	"\x0eDiffChangeType\x12 \n" +
	"\x1cDIFF_CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DIFF_CHANGE_TYPE_ADD\x10\x01\x12\x1b\n" +
	"\x17DIFF_CHANGE_TYPE_DELETE\x10\x02\x12\x1b\n" +
	"\x17DIFF_CHANGE_TYPE_MODIFY\x10\x03B\x1eZ\x1ccr-system/api/crsystem/v1;v1b\x06proto3"

var (
	file_crsystem_v1_common_proto_rawDescOnce sync.Once
	file_crsystem_v1_common_proto_rawDescData []byte
)

func file_crsystem_v1_common_proto_rawDescGZIP() []byte {
	file_crsystem_v1_common_proto_rawDescOnce.Do(func() {
		file_crsystem_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crsystem_v1_common_proto_rawDesc), len(file_crsystem_v1_common_proto_rawDesc)))
	})
	return file_crsystem_v1_common_proto_rawDescData
}

var file_crsystem_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_crsystem_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_crsystem_v1_common_proto_goTypes = []any{
	(ReviewStatus)(0),      // 0: crsystem.v1.ReviewStatus
	(ReviewPriority)(0),    // 1: crsystem.v1.ReviewPriority
	(DefectLevel)(0),       // 2: crsystem.v1.DefectLevel
	(GitPlatform)(0),       // 3: crsystem.v1.GitPlatform
	(DiffChangeType)(0),    // 4: crsystem.v1.DiffChangeType
	(*Pagination)(nil),     // 5: crsystem.v1.Pagination
	(*PaginationResp)(nil), // 6: crsystem.v1.PaginationResp
	(*OperateResult)(nil),  // 7: crsystem.v1.OperateResult
}
var file_crsystem_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crsystem_v1_common_proto_init() }
func file_crsystem_v1_common_proto_init() {
	if File_crsystem_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crsystem_v1_common_proto_rawDesc), len(file_crsystem_v1_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crsystem_v1_common_proto_goTypes,
		DependencyIndexes: file_crsystem_v1_common_proto_depIdxs,
		EnumInfos:         file_crsystem_v1_common_proto_enumTypes,
		MessageInfos:      file_crsystem_v1_common_proto_msgTypes,
	}.Build()
	File_crsystem_v1_common_proto = out.File
	file_crsystem_v1_common_proto_goTypes = nil
	file_crsystem_v1_common_proto_depIdxs = nil
}
