// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: crsystem/v1/git_adapter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGitAdapterServiceBindRepository = "/crsystem.v1.GitAdapterService/BindRepository"
const OperationGitAdapterServiceGetAuthURL = "/crsystem.v1.GitAdapterService/GetAuthURL"
const OperationGitAdapterServiceGetDiffData = "/crsystem.v1.GitAdapterService/GetDiffData"
const OperationGitAdapterServiceGetMRData = "/crsystem.v1.GitAdapterService/GetMRData"
const OperationGitAdapterServiceGetMRFiles = "/crsystem.v1.GitAdapterService/GetMRFiles"
const OperationGitAdapterServiceGetRepoBlacklist = "/crsystem.v1.GitAdapterService/GetRepoBlacklist"
const OperationGitAdapterServiceGetSensitiveExtensions = "/crsystem.v1.GitAdapterService/GetSensitiveExtensions"
const OperationGitAdapterServiceHandleOAuthCallback = "/crsystem.v1.GitAdapterService/HandleOAuthCallback"
const OperationGitAdapterServiceListAuthorizations = "/crsystem.v1.GitAdapterService/ListAuthorizations"
const OperationGitAdapterServiceListRemoteRepos = "/crsystem.v1.GitAdapterService/ListRemoteRepos"
const OperationGitAdapterServiceListRepositories = "/crsystem.v1.GitAdapterService/ListRepositories"
const OperationGitAdapterServiceRevokeAuthorization = "/crsystem.v1.GitAdapterService/RevokeAuthorization"
const OperationGitAdapterServiceSetRepoBlacklist = "/crsystem.v1.GitAdapterService/SetRepoBlacklist"
const OperationGitAdapterServiceSetSensitiveExtensions = "/crsystem.v1.GitAdapterService/SetSensitiveExtensions"
const OperationGitAdapterServiceTriggerSync = "/crsystem.v1.GitAdapterService/TriggerSync"
const OperationGitAdapterServiceUnbindRepository = "/crsystem.v1.GitAdapterService/UnbindRepository"

type GitAdapterServiceHTTPServer interface {
	// BindRepository 绑定仓库到本系统（纳入评审管理范围）
	BindRepository(context.Context, *BindRepoReq) (*RepoInfo, error)
	// GetAuthURL 获取OAuth授权跳转URL
	GetAuthURL(context.Context, *GetAuthURLReq) (*GetAuthURLResp, error)
	// GetDiffData 获取指定文件的结构化Diff数据（LLD §3.2 Diff解析模块）
	GetDiffData(context.Context, *GetDiffDataReq) (*DiffData, error)
	// GetMRData 获取MR基础信息（由cr-core调用）
	GetMRData(context.Context, *GetMRDataReq) (*MRData, error)
	// GetMRFiles 获取MR变更文件列表
	GetMRFiles(context.Context, *GetMRFilesReq) (*GetMRFilesResp, error)
	// GetRepoBlacklist 获取黑名单列表
	GetRepoBlacklist(context.Context, *GetBlacklistReq) (*GetBlacklistResp, error)
	// GetSensitiveExtensions 获取敏感文件后缀列表
	GetSensitiveExtensions(context.Context, *GetSensitiveExtReq) (*GetSensitiveExtResp, error)
	// HandleOAuthCallback OAuth回调处理 — 换取Token并存储
	HandleOAuthCallback(context.Context, *OAuthCallbackReq) (*OAuthCallbackResp, error)
	// ListAuthorizations 获取当前租户已绑定的Git授权列表
	ListAuthorizations(context.Context, *ListAuthReq) (*ListAuthResp, error)
	// ListRemoteRepos 获取已授权账号下可见的仓库列表（从Git平台拉取）
	ListRemoteRepos(context.Context, *ListRemoteReposReq) (*ListRemoteReposResp, error)
	// ListRepositories 获取已绑定仓库列表
	ListRepositories(context.Context, *ListReposReq) (*ListReposResp, error)
	// RevokeAuthorization 撤销Git授权
	RevokeAuthorization(context.Context, *RevokeAuthReq) (*OperateResult, error)
	// SetRepoBlacklist 配置仓库黑白名单
	SetRepoBlacklist(context.Context, *SetBlacklistReq) (*OperateResult, error)
	// SetSensitiveExtensions 配置敏感文件后缀
	SetSensitiveExtensions(context.Context, *SetSensitiveExtReq) (*OperateResult, error)
	// TriggerSync 手动触发仓库全量同步
	TriggerSync(context.Context, *TriggerSyncReq) (*OperateResult, error)
	// UnbindRepository 解绑仓库
	UnbindRepository(context.Context, *UnbindRepoReq) (*OperateResult, error)
}

func RegisterGitAdapterServiceHTTPServer(s *http.Server, srv GitAdapterServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/git/oauth/url", _GitAdapterService_GetAuthURL0_HTTP_Handler(srv))
	r.POST("/api/v1/git/oauth/callback", _GitAdapterService_HandleOAuthCallback0_HTTP_Handler(srv))
	r.GET("/api/v1/git/authorizations", _GitAdapterService_ListAuthorizations0_HTTP_Handler(srv))
	r.DELETE("/api/v1/git/authorizations/{auth_id}", _GitAdapterService_RevokeAuthorization0_HTTP_Handler(srv))
	r.GET("/api/v1/git/remote-repos", _GitAdapterService_ListRemoteRepos0_HTTP_Handler(srv))
	r.POST("/api/v1/git/repos", _GitAdapterService_BindRepository0_HTTP_Handler(srv))
	r.GET("/api/v1/git/repos", _GitAdapterService_ListRepositories0_HTTP_Handler(srv))
	r.DELETE("/api/v1/git/repos/{repo_id}", _GitAdapterService_UnbindRepository0_HTTP_Handler(srv))
	r.GET("/api/v1/git/repos/{repo_id}/mrs/{mr_id}", _GitAdapterService_GetMRData0_HTTP_Handler(srv))
	r.GET("/api/v1/git/repos/{repo_id}/mrs/{mr_id}/files", _GitAdapterService_GetMRFiles0_HTTP_Handler(srv))
	r.GET("/api/v1/git/repos/{repo_id}/mrs/{mr_id}/diff", _GitAdapterService_GetDiffData0_HTTP_Handler(srv))
	r.POST("/api/v1/git/repos/{repo_id}/sync", _GitAdapterService_TriggerSync0_HTTP_Handler(srv))
	r.POST("/api/v1/git/repos/blacklist", _GitAdapterService_SetRepoBlacklist0_HTTP_Handler(srv))
	r.GET("/api/v1/git/repos/blacklist", _GitAdapterService_GetRepoBlacklist0_HTTP_Handler(srv))
	r.POST("/api/v1/git/repos/sensitive-extensions", _GitAdapterService_SetSensitiveExtensions0_HTTP_Handler(srv))
	r.GET("/api/v1/git/repos/sensitive-extensions", _GitAdapterService_GetSensitiveExtensions0_HTTP_Handler(srv))
}

func _GitAdapterService_GetAuthURL0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAuthURLReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceGetAuthURL)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAuthURL(ctx, req.(*GetAuthURLReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAuthURLResp)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_HandleOAuthCallback0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OAuthCallbackReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceHandleOAuthCallback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HandleOAuthCallback(ctx, req.(*OAuthCallbackReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OAuthCallbackResp)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_ListAuthorizations0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAuthReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceListAuthorizations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAuthorizations(ctx, req.(*ListAuthReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAuthResp)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_RevokeAuthorization0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeAuthReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceRevokeAuthorization)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeAuthorization(ctx, req.(*RevokeAuthReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_ListRemoteRepos0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRemoteReposReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceListRemoteRepos)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRemoteRepos(ctx, req.(*ListRemoteReposReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRemoteReposResp)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_BindRepository0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindRepoReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceBindRepository)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindRepository(ctx, req.(*BindRepoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RepoInfo)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_ListRepositories0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReposReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceListRepositories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRepositories(ctx, req.(*ListReposReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReposResp)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_UnbindRepository0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UnbindRepoReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceUnbindRepository)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UnbindRepository(ctx, req.(*UnbindRepoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_GetMRData0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMRDataReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceGetMRData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMRData(ctx, req.(*GetMRDataReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MRData)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_GetMRFiles0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMRFilesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceGetMRFiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMRFiles(ctx, req.(*GetMRFilesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMRFilesResp)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_GetDiffData0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDiffDataReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceGetDiffData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDiffData(ctx, req.(*GetDiffDataReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DiffData)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_TriggerSync0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TriggerSyncReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceTriggerSync)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TriggerSync(ctx, req.(*TriggerSyncReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_SetRepoBlacklist0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetBlacklistReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceSetRepoBlacklist)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetRepoBlacklist(ctx, req.(*SetBlacklistReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_GetRepoBlacklist0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBlacklistReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceGetRepoBlacklist)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRepoBlacklist(ctx, req.(*GetBlacklistReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBlacklistResp)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_SetSensitiveExtensions0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetSensitiveExtReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceSetSensitiveExtensions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetSensitiveExtensions(ctx, req.(*SetSensitiveExtReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _GitAdapterService_GetSensitiveExtensions0_HTTP_Handler(srv GitAdapterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSensitiveExtReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGitAdapterServiceGetSensitiveExtensions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSensitiveExtensions(ctx, req.(*GetSensitiveExtReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSensitiveExtResp)
		return ctx.Result(200, reply)
	}
}

type GitAdapterServiceHTTPClient interface {
	// BindRepository 绑定仓库到本系统（纳入评审管理范围）
	BindRepository(ctx context.Context, req *BindRepoReq, opts ...http.CallOption) (rsp *RepoInfo, err error)
	// GetAuthURL 获取OAuth授权跳转URL
	GetAuthURL(ctx context.Context, req *GetAuthURLReq, opts ...http.CallOption) (rsp *GetAuthURLResp, err error)
	// GetDiffData 获取指定文件的结构化Diff数据（LLD §3.2 Diff解析模块）
	GetDiffData(ctx context.Context, req *GetDiffDataReq, opts ...http.CallOption) (rsp *DiffData, err error)
	// GetMRData 获取MR基础信息（由cr-core调用）
	GetMRData(ctx context.Context, req *GetMRDataReq, opts ...http.CallOption) (rsp *MRData, err error)
	// GetMRFiles 获取MR变更文件列表
	GetMRFiles(ctx context.Context, req *GetMRFilesReq, opts ...http.CallOption) (rsp *GetMRFilesResp, err error)
	// GetRepoBlacklist 获取黑名单列表
	GetRepoBlacklist(ctx context.Context, req *GetBlacklistReq, opts ...http.CallOption) (rsp *GetBlacklistResp, err error)
	// GetSensitiveExtensions 获取敏感文件后缀列表
	GetSensitiveExtensions(ctx context.Context, req *GetSensitiveExtReq, opts ...http.CallOption) (rsp *GetSensitiveExtResp, err error)
	// HandleOAuthCallback OAuth回调处理 — 换取Token并存储
	HandleOAuthCallback(ctx context.Context, req *OAuthCallbackReq, opts ...http.CallOption) (rsp *OAuthCallbackResp, err error)
	// ListAuthorizations 获取当前租户已绑定的Git授权列表
	ListAuthorizations(ctx context.Context, req *ListAuthReq, opts ...http.CallOption) (rsp *ListAuthResp, err error)
	// ListRemoteRepos 获取已授权账号下可见的仓库列表（从Git平台拉取）
	ListRemoteRepos(ctx context.Context, req *ListRemoteReposReq, opts ...http.CallOption) (rsp *ListRemoteReposResp, err error)
	// ListRepositories 获取已绑定仓库列表
	ListRepositories(ctx context.Context, req *ListReposReq, opts ...http.CallOption) (rsp *ListReposResp, err error)
	// RevokeAuthorization 撤销Git授权
	RevokeAuthorization(ctx context.Context, req *RevokeAuthReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// SetRepoBlacklist 配置仓库黑白名单
	SetRepoBlacklist(ctx context.Context, req *SetBlacklistReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// SetSensitiveExtensions 配置敏感文件后缀
	SetSensitiveExtensions(ctx context.Context, req *SetSensitiveExtReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// TriggerSync 手动触发仓库全量同步
	TriggerSync(ctx context.Context, req *TriggerSyncReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// UnbindRepository 解绑仓库
	UnbindRepository(ctx context.Context, req *UnbindRepoReq, opts ...http.CallOption) (rsp *OperateResult, err error)
}

type GitAdapterServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewGitAdapterServiceHTTPClient(client *http.Client) GitAdapterServiceHTTPClient {
	return &GitAdapterServiceHTTPClientImpl{client}
}

// BindRepository 绑定仓库到本系统（纳入评审管理范围）
func (c *GitAdapterServiceHTTPClientImpl) BindRepository(ctx context.Context, in *BindRepoReq, opts ...http.CallOption) (*RepoInfo, error) {
	var out RepoInfo
	pattern := "/api/v1/git/repos"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGitAdapterServiceBindRepository))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAuthURL 获取OAuth授权跳转URL
func (c *GitAdapterServiceHTTPClientImpl) GetAuthURL(ctx context.Context, in *GetAuthURLReq, opts ...http.CallOption) (*GetAuthURLResp, error) {
	var out GetAuthURLResp
	pattern := "/api/v1/git/oauth/url"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceGetAuthURL))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDiffData 获取指定文件的结构化Diff数据（LLD §3.2 Diff解析模块）
func (c *GitAdapterServiceHTTPClientImpl) GetDiffData(ctx context.Context, in *GetDiffDataReq, opts ...http.CallOption) (*DiffData, error) {
	var out DiffData
	pattern := "/api/v1/git/repos/{repo_id}/mrs/{mr_id}/diff"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceGetDiffData))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMRData 获取MR基础信息（由cr-core调用）
func (c *GitAdapterServiceHTTPClientImpl) GetMRData(ctx context.Context, in *GetMRDataReq, opts ...http.CallOption) (*MRData, error) {
	var out MRData
	pattern := "/api/v1/git/repos/{repo_id}/mrs/{mr_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceGetMRData))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMRFiles 获取MR变更文件列表
func (c *GitAdapterServiceHTTPClientImpl) GetMRFiles(ctx context.Context, in *GetMRFilesReq, opts ...http.CallOption) (*GetMRFilesResp, error) {
	var out GetMRFilesResp
	pattern := "/api/v1/git/repos/{repo_id}/mrs/{mr_id}/files"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceGetMRFiles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRepoBlacklist 获取黑名单列表
func (c *GitAdapterServiceHTTPClientImpl) GetRepoBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...http.CallOption) (*GetBlacklistResp, error) {
	var out GetBlacklistResp
	pattern := "/api/v1/git/repos/blacklist"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceGetRepoBlacklist))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSensitiveExtensions 获取敏感文件后缀列表
func (c *GitAdapterServiceHTTPClientImpl) GetSensitiveExtensions(ctx context.Context, in *GetSensitiveExtReq, opts ...http.CallOption) (*GetSensitiveExtResp, error) {
	var out GetSensitiveExtResp
	pattern := "/api/v1/git/repos/sensitive-extensions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceGetSensitiveExtensions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HandleOAuthCallback OAuth回调处理 — 换取Token并存储
func (c *GitAdapterServiceHTTPClientImpl) HandleOAuthCallback(ctx context.Context, in *OAuthCallbackReq, opts ...http.CallOption) (*OAuthCallbackResp, error) {
	var out OAuthCallbackResp
	pattern := "/api/v1/git/oauth/callback"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGitAdapterServiceHandleOAuthCallback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAuthorizations 获取当前租户已绑定的Git授权列表
func (c *GitAdapterServiceHTTPClientImpl) ListAuthorizations(ctx context.Context, in *ListAuthReq, opts ...http.CallOption) (*ListAuthResp, error) {
	var out ListAuthResp
	pattern := "/api/v1/git/authorizations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceListAuthorizations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRemoteRepos 获取已授权账号下可见的仓库列表（从Git平台拉取）
func (c *GitAdapterServiceHTTPClientImpl) ListRemoteRepos(ctx context.Context, in *ListRemoteReposReq, opts ...http.CallOption) (*ListRemoteReposResp, error) {
	var out ListRemoteReposResp
	pattern := "/api/v1/git/remote-repos"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceListRemoteRepos))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRepositories 获取已绑定仓库列表
func (c *GitAdapterServiceHTTPClientImpl) ListRepositories(ctx context.Context, in *ListReposReq, opts ...http.CallOption) (*ListReposResp, error) {
	var out ListReposResp
	pattern := "/api/v1/git/repos"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceListRepositories))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RevokeAuthorization 撤销Git授权
func (c *GitAdapterServiceHTTPClientImpl) RevokeAuthorization(ctx context.Context, in *RevokeAuthReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/git/authorizations/{auth_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceRevokeAuthorization))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetRepoBlacklist 配置仓库黑白名单
func (c *GitAdapterServiceHTTPClientImpl) SetRepoBlacklist(ctx context.Context, in *SetBlacklistReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/git/repos/blacklist"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGitAdapterServiceSetRepoBlacklist))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetSensitiveExtensions 配置敏感文件后缀
func (c *GitAdapterServiceHTTPClientImpl) SetSensitiveExtensions(ctx context.Context, in *SetSensitiveExtReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/git/repos/sensitive-extensions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGitAdapterServiceSetSensitiveExtensions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TriggerSync 手动触发仓库全量同步
func (c *GitAdapterServiceHTTPClientImpl) TriggerSync(ctx context.Context, in *TriggerSyncReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/git/repos/{repo_id}/sync"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGitAdapterServiceTriggerSync))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UnbindRepository 解绑仓库
func (c *GitAdapterServiceHTTPClientImpl) UnbindRepository(ctx context.Context, in *UnbindRepoReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/git/repos/{repo_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGitAdapterServiceUnbindRepository))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
