// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: crsystem/v1/git_adapter.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitAdapterService_GetAuthURL_FullMethodName             = "/crsystem.v1.GitAdapterService/GetAuthURL"
	GitAdapterService_HandleOAuthCallback_FullMethodName    = "/crsystem.v1.GitAdapterService/HandleOAuthCallback"
	GitAdapterService_ListAuthorizations_FullMethodName     = "/crsystem.v1.GitAdapterService/ListAuthorizations"
	GitAdapterService_RevokeAuthorization_FullMethodName    = "/crsystem.v1.GitAdapterService/RevokeAuthorization"
	GitAdapterService_ListRemoteRepos_FullMethodName        = "/crsystem.v1.GitAdapterService/ListRemoteRepos"
	GitAdapterService_BindRepository_FullMethodName         = "/crsystem.v1.GitAdapterService/BindRepository"
	GitAdapterService_ListRepositories_FullMethodName       = "/crsystem.v1.GitAdapterService/ListRepositories"
	GitAdapterService_UnbindRepository_FullMethodName       = "/crsystem.v1.GitAdapterService/UnbindRepository"
	GitAdapterService_GetMRData_FullMethodName              = "/crsystem.v1.GitAdapterService/GetMRData"
	GitAdapterService_GetMRFiles_FullMethodName             = "/crsystem.v1.GitAdapterService/GetMRFiles"
	GitAdapterService_GetDiffData_FullMethodName            = "/crsystem.v1.GitAdapterService/GetDiffData"
	GitAdapterService_TriggerSync_FullMethodName            = "/crsystem.v1.GitAdapterService/TriggerSync"
	GitAdapterService_SetRepoBlacklist_FullMethodName       = "/crsystem.v1.GitAdapterService/SetRepoBlacklist"
	GitAdapterService_GetRepoBlacklist_FullMethodName       = "/crsystem.v1.GitAdapterService/GetRepoBlacklist"
	GitAdapterService_SetSensitiveExtensions_FullMethodName = "/crsystem.v1.GitAdapterService/SetSensitiveExtensions"
	GitAdapterService_GetSensitiveExtensions_FullMethodName = "/crsystem.v1.GitAdapterService/GetSensitiveExtensions"
)

// GitAdapterServiceClient is the client API for GitAdapterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================
// git-adapter 仓库适配服务（HLD §2.1 / LLD §3.2）
// 核心职责：三方Git平台接口对接、OAuth授权生命周期管理、
//
//	项目/分支/MR数据同步、Diff解析、敏感文件过滤
//
// ============================================================
type GitAdapterServiceClient interface {
	// 获取OAuth授权跳转URL
	GetAuthURL(ctx context.Context, in *GetAuthURLReq, opts ...grpc.CallOption) (*GetAuthURLResp, error)
	// OAuth回调处理 — 换取Token并存储
	HandleOAuthCallback(ctx context.Context, in *OAuthCallbackReq, opts ...grpc.CallOption) (*OAuthCallbackResp, error)
	// 获取当前租户已绑定的Git授权列表
	ListAuthorizations(ctx context.Context, in *ListAuthReq, opts ...grpc.CallOption) (*ListAuthResp, error)
	// 撤销Git授权
	RevokeAuthorization(ctx context.Context, in *RevokeAuthReq, opts ...grpc.CallOption) (*OperateResult, error)
	// 获取已授权账号下可见的仓库列表（从Git平台拉取）
	ListRemoteRepos(ctx context.Context, in *ListRemoteReposReq, opts ...grpc.CallOption) (*ListRemoteReposResp, error)
	// 绑定仓库到本系统（纳入评审管理范围）
	BindRepository(ctx context.Context, in *BindRepoReq, opts ...grpc.CallOption) (*RepoInfo, error)
	// 获取已绑定仓库列表
	ListRepositories(ctx context.Context, in *ListReposReq, opts ...grpc.CallOption) (*ListReposResp, error)
	// 解绑仓库
	UnbindRepository(ctx context.Context, in *UnbindRepoReq, opts ...grpc.CallOption) (*OperateResult, error)
	// 获取MR基础信息（由cr-core调用）
	GetMRData(ctx context.Context, in *GetMRDataReq, opts ...grpc.CallOption) (*MRData, error)
	// 获取MR变更文件列表
	GetMRFiles(ctx context.Context, in *GetMRFilesReq, opts ...grpc.CallOption) (*GetMRFilesResp, error)
	// 获取指定文件的结构化Diff数据（LLD §3.2 Diff解析模块）
	GetDiffData(ctx context.Context, in *GetDiffDataReq, opts ...grpc.CallOption) (*DiffData, error)
	// 手动触发仓库全量同步
	TriggerSync(ctx context.Context, in *TriggerSyncReq, opts ...grpc.CallOption) (*OperateResult, error)
	// 配置仓库黑白名单
	SetRepoBlacklist(ctx context.Context, in *SetBlacklistReq, opts ...grpc.CallOption) (*OperateResult, error)
	// 获取黑名单列表
	GetRepoBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error)
	// 配置敏感文件后缀
	SetSensitiveExtensions(ctx context.Context, in *SetSensitiveExtReq, opts ...grpc.CallOption) (*OperateResult, error)
	// 获取敏感文件后缀列表
	GetSensitiveExtensions(ctx context.Context, in *GetSensitiveExtReq, opts ...grpc.CallOption) (*GetSensitiveExtResp, error)
}

type gitAdapterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGitAdapterServiceClient(cc grpc.ClientConnInterface) GitAdapterServiceClient {
	return &gitAdapterServiceClient{cc}
}

func (c *gitAdapterServiceClient) GetAuthURL(ctx context.Context, in *GetAuthURLReq, opts ...grpc.CallOption) (*GetAuthURLResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthURLResp)
	err := c.cc.Invoke(ctx, GitAdapterService_GetAuthURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) HandleOAuthCallback(ctx context.Context, in *OAuthCallbackReq, opts ...grpc.CallOption) (*OAuthCallbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuthCallbackResp)
	err := c.cc.Invoke(ctx, GitAdapterService_HandleOAuthCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) ListAuthorizations(ctx context.Context, in *ListAuthReq, opts ...grpc.CallOption) (*ListAuthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuthResp)
	err := c.cc.Invoke(ctx, GitAdapterService_ListAuthorizations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) RevokeAuthorization(ctx context.Context, in *RevokeAuthReq, opts ...grpc.CallOption) (*OperateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResult)
	err := c.cc.Invoke(ctx, GitAdapterService_RevokeAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) ListRemoteRepos(ctx context.Context, in *ListRemoteReposReq, opts ...grpc.CallOption) (*ListRemoteReposResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRemoteReposResp)
	err := c.cc.Invoke(ctx, GitAdapterService_ListRemoteRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) BindRepository(ctx context.Context, in *BindRepoReq, opts ...grpc.CallOption) (*RepoInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoInfo)
	err := c.cc.Invoke(ctx, GitAdapterService_BindRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) ListRepositories(ctx context.Context, in *ListReposReq, opts ...grpc.CallOption) (*ListReposResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReposResp)
	err := c.cc.Invoke(ctx, GitAdapterService_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) UnbindRepository(ctx context.Context, in *UnbindRepoReq, opts ...grpc.CallOption) (*OperateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResult)
	err := c.cc.Invoke(ctx, GitAdapterService_UnbindRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) GetMRData(ctx context.Context, in *GetMRDataReq, opts ...grpc.CallOption) (*MRData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MRData)
	err := c.cc.Invoke(ctx, GitAdapterService_GetMRData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) GetMRFiles(ctx context.Context, in *GetMRFilesReq, opts ...grpc.CallOption) (*GetMRFilesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMRFilesResp)
	err := c.cc.Invoke(ctx, GitAdapterService_GetMRFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) GetDiffData(ctx context.Context, in *GetDiffDataReq, opts ...grpc.CallOption) (*DiffData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffData)
	err := c.cc.Invoke(ctx, GitAdapterService_GetDiffData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) TriggerSync(ctx context.Context, in *TriggerSyncReq, opts ...grpc.CallOption) (*OperateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResult)
	err := c.cc.Invoke(ctx, GitAdapterService_TriggerSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) SetRepoBlacklist(ctx context.Context, in *SetBlacklistReq, opts ...grpc.CallOption) (*OperateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResult)
	err := c.cc.Invoke(ctx, GitAdapterService_SetRepoBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) GetRepoBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlacklistResp)
	err := c.cc.Invoke(ctx, GitAdapterService_GetRepoBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) SetSensitiveExtensions(ctx context.Context, in *SetSensitiveExtReq, opts ...grpc.CallOption) (*OperateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResult)
	err := c.cc.Invoke(ctx, GitAdapterService_SetSensitiveExtensions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitAdapterServiceClient) GetSensitiveExtensions(ctx context.Context, in *GetSensitiveExtReq, opts ...grpc.CallOption) (*GetSensitiveExtResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSensitiveExtResp)
	err := c.cc.Invoke(ctx, GitAdapterService_GetSensitiveExtensions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitAdapterServiceServer is the server API for GitAdapterService service.
// All implementations must embed UnimplementedGitAdapterServiceServer
// for forward compatibility.
//
// ============================================================
// git-adapter 仓库适配服务（HLD §2.1 / LLD §3.2）
// 核心职责：三方Git平台接口对接、OAuth授权生命周期管理、
//
//	项目/分支/MR数据同步、Diff解析、敏感文件过滤
//
// ============================================================
type GitAdapterServiceServer interface {
	// 获取OAuth授权跳转URL
	GetAuthURL(context.Context, *GetAuthURLReq) (*GetAuthURLResp, error)
	// OAuth回调处理 — 换取Token并存储
	HandleOAuthCallback(context.Context, *OAuthCallbackReq) (*OAuthCallbackResp, error)
	// 获取当前租户已绑定的Git授权列表
	ListAuthorizations(context.Context, *ListAuthReq) (*ListAuthResp, error)
	// 撤销Git授权
	RevokeAuthorization(context.Context, *RevokeAuthReq) (*OperateResult, error)
	// 获取已授权账号下可见的仓库列表（从Git平台拉取）
	ListRemoteRepos(context.Context, *ListRemoteReposReq) (*ListRemoteReposResp, error)
	// 绑定仓库到本系统（纳入评审管理范围）
	BindRepository(context.Context, *BindRepoReq) (*RepoInfo, error)
	// 获取已绑定仓库列表
	ListRepositories(context.Context, *ListReposReq) (*ListReposResp, error)
	// 解绑仓库
	UnbindRepository(context.Context, *UnbindRepoReq) (*OperateResult, error)
	// 获取MR基础信息（由cr-core调用）
	GetMRData(context.Context, *GetMRDataReq) (*MRData, error)
	// 获取MR变更文件列表
	GetMRFiles(context.Context, *GetMRFilesReq) (*GetMRFilesResp, error)
	// 获取指定文件的结构化Diff数据（LLD §3.2 Diff解析模块）
	GetDiffData(context.Context, *GetDiffDataReq) (*DiffData, error)
	// 手动触发仓库全量同步
	TriggerSync(context.Context, *TriggerSyncReq) (*OperateResult, error)
	// 配置仓库黑白名单
	SetRepoBlacklist(context.Context, *SetBlacklistReq) (*OperateResult, error)
	// 获取黑名单列表
	GetRepoBlacklist(context.Context, *GetBlacklistReq) (*GetBlacklistResp, error)
	// 配置敏感文件后缀
	SetSensitiveExtensions(context.Context, *SetSensitiveExtReq) (*OperateResult, error)
	// 获取敏感文件后缀列表
	GetSensitiveExtensions(context.Context, *GetSensitiveExtReq) (*GetSensitiveExtResp, error)
	mustEmbedUnimplementedGitAdapterServiceServer()
}

// UnimplementedGitAdapterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitAdapterServiceServer struct{}

func (UnimplementedGitAdapterServiceServer) GetAuthURL(context.Context, *GetAuthURLReq) (*GetAuthURLResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthURL not implemented")
}
func (UnimplementedGitAdapterServiceServer) HandleOAuthCallback(context.Context, *OAuthCallbackReq) (*OAuthCallbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleOAuthCallback not implemented")
}
func (UnimplementedGitAdapterServiceServer) ListAuthorizations(context.Context, *ListAuthReq) (*ListAuthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuthorizations not implemented")
}
func (UnimplementedGitAdapterServiceServer) RevokeAuthorization(context.Context, *RevokeAuthReq) (*OperateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAuthorization not implemented")
}
func (UnimplementedGitAdapterServiceServer) ListRemoteRepos(context.Context, *ListRemoteReposReq) (*ListRemoteReposResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRemoteRepos not implemented")
}
func (UnimplementedGitAdapterServiceServer) BindRepository(context.Context, *BindRepoReq) (*RepoInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method BindRepository not implemented")
}
func (UnimplementedGitAdapterServiceServer) ListRepositories(context.Context, *ListReposReq) (*ListReposResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedGitAdapterServiceServer) UnbindRepository(context.Context, *UnbindRepoReq) (*OperateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindRepository not implemented")
}
func (UnimplementedGitAdapterServiceServer) GetMRData(context.Context, *GetMRDataReq) (*MRData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMRData not implemented")
}
func (UnimplementedGitAdapterServiceServer) GetMRFiles(context.Context, *GetMRFilesReq) (*GetMRFilesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMRFiles not implemented")
}
func (UnimplementedGitAdapterServiceServer) GetDiffData(context.Context, *GetDiffDataReq) (*DiffData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiffData not implemented")
}
func (UnimplementedGitAdapterServiceServer) TriggerSync(context.Context, *TriggerSyncReq) (*OperateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerSync not implemented")
}
func (UnimplementedGitAdapterServiceServer) SetRepoBlacklist(context.Context, *SetBlacklistReq) (*OperateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRepoBlacklist not implemented")
}
func (UnimplementedGitAdapterServiceServer) GetRepoBlacklist(context.Context, *GetBlacklistReq) (*GetBlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepoBlacklist not implemented")
}
func (UnimplementedGitAdapterServiceServer) SetSensitiveExtensions(context.Context, *SetSensitiveExtReq) (*OperateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSensitiveExtensions not implemented")
}
func (UnimplementedGitAdapterServiceServer) GetSensitiveExtensions(context.Context, *GetSensitiveExtReq) (*GetSensitiveExtResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSensitiveExtensions not implemented")
}
func (UnimplementedGitAdapterServiceServer) mustEmbedUnimplementedGitAdapterServiceServer() {}
func (UnimplementedGitAdapterServiceServer) testEmbeddedByValue()                           {}

// UnsafeGitAdapterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitAdapterServiceServer will
// result in compilation errors.
type UnsafeGitAdapterServiceServer interface {
	mustEmbedUnimplementedGitAdapterServiceServer()
}

func RegisterGitAdapterServiceServer(s grpc.ServiceRegistrar, srv GitAdapterServiceServer) {
	// If the following call panics, it indicates UnimplementedGitAdapterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitAdapterService_ServiceDesc, srv)
}

func _GitAdapterService_GetAuthURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).GetAuthURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_GetAuthURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).GetAuthURL(ctx, req.(*GetAuthURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_HandleOAuthCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuthCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).HandleOAuthCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_HandleOAuthCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).HandleOAuthCallback(ctx, req.(*OAuthCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_ListAuthorizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).ListAuthorizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_ListAuthorizations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).ListAuthorizations(ctx, req.(*ListAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_RevokeAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).RevokeAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_RevokeAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).RevokeAuthorization(ctx, req.(*RevokeAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_ListRemoteRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRemoteReposReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).ListRemoteRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_ListRemoteRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).ListRemoteRepos(ctx, req.(*ListRemoteReposReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_BindRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRepoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).BindRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_BindRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).BindRepository(ctx, req.(*BindRepoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReposReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).ListRepositories(ctx, req.(*ListReposReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_UnbindRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindRepoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).UnbindRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_UnbindRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).UnbindRepository(ctx, req.(*UnbindRepoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_GetMRData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMRDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).GetMRData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_GetMRData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).GetMRData(ctx, req.(*GetMRDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_GetMRFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMRFilesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).GetMRFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_GetMRFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).GetMRFiles(ctx, req.(*GetMRFilesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_GetDiffData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiffDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).GetDiffData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_GetDiffData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).GetDiffData(ctx, req.(*GetDiffDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_TriggerSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerSyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).TriggerSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_TriggerSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).TriggerSync(ctx, req.(*TriggerSyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_SetRepoBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).SetRepoBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_SetRepoBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).SetRepoBlacklist(ctx, req.(*SetBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_GetRepoBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).GetRepoBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_GetRepoBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).GetRepoBlacklist(ctx, req.(*GetBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_SetSensitiveExtensions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSensitiveExtReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).SetSensitiveExtensions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_SetSensitiveExtensions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).SetSensitiveExtensions(ctx, req.(*SetSensitiveExtReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitAdapterService_GetSensitiveExtensions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSensitiveExtReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAdapterServiceServer).GetSensitiveExtensions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAdapterService_GetSensitiveExtensions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAdapterServiceServer).GetSensitiveExtensions(ctx, req.(*GetSensitiveExtReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GitAdapterService_ServiceDesc is the grpc.ServiceDesc for GitAdapterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitAdapterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crsystem.v1.GitAdapterService",
	HandlerType: (*GitAdapterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthURL",
			Handler:    _GitAdapterService_GetAuthURL_Handler,
		},
		{
			MethodName: "HandleOAuthCallback",
			Handler:    _GitAdapterService_HandleOAuthCallback_Handler,
		},
		{
			MethodName: "ListAuthorizations",
			Handler:    _GitAdapterService_ListAuthorizations_Handler,
		},
		{
			MethodName: "RevokeAuthorization",
			Handler:    _GitAdapterService_RevokeAuthorization_Handler,
		},
		{
			MethodName: "ListRemoteRepos",
			Handler:    _GitAdapterService_ListRemoteRepos_Handler,
		},
		{
			MethodName: "BindRepository",
			Handler:    _GitAdapterService_BindRepository_Handler,
		},
		{
			MethodName: "ListRepositories",
			Handler:    _GitAdapterService_ListRepositories_Handler,
		},
		{
			MethodName: "UnbindRepository",
			Handler:    _GitAdapterService_UnbindRepository_Handler,
		},
		{
			MethodName: "GetMRData",
			Handler:    _GitAdapterService_GetMRData_Handler,
		},
		{
			MethodName: "GetMRFiles",
			Handler:    _GitAdapterService_GetMRFiles_Handler,
		},
		{
			MethodName: "GetDiffData",
			Handler:    _GitAdapterService_GetDiffData_Handler,
		},
		{
			MethodName: "TriggerSync",
			Handler:    _GitAdapterService_TriggerSync_Handler,
		},
		{
			MethodName: "SetRepoBlacklist",
			Handler:    _GitAdapterService_SetRepoBlacklist_Handler,
		},
		{
			MethodName: "GetRepoBlacklist",
			Handler:    _GitAdapterService_GetRepoBlacklist_Handler,
		},
		{
			MethodName: "SetSensitiveExtensions",
			Handler:    _GitAdapterService_SetSensitiveExtensions_Handler,
		},
		{
			MethodName: "GetSensitiveExtensions",
			Handler:    _GitAdapterService_GetSensitiveExtensions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crsystem/v1/git_adapter.proto",
}
