// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: crsystem/v1/iam.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CheckDataPermissionReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckDataPermissionReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckDataPermissionReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckDataPermissionReqMultiError, or nil if none found.
func (m *CheckDataPermissionReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckDataPermissionReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for UserId

	// no validation rules for ResourceType

	// no validation rules for ResourceId

	// no validation rules for Action

	if len(errors) > 0 {
		return CheckDataPermissionReqMultiError(errors)
	}

	return nil
}

// CheckDataPermissionReqMultiError is an error wrapping multiple validation
// errors returned by CheckDataPermissionReq.ValidateAll() if the designated
// constraints aren't met.
type CheckDataPermissionReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckDataPermissionReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckDataPermissionReqMultiError) AllErrors() []error { return m }

// CheckDataPermissionReqValidationError is the validation error returned by
// CheckDataPermissionReq.Validate if the designated constraints aren't met.
type CheckDataPermissionReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckDataPermissionReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckDataPermissionReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckDataPermissionReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckDataPermissionReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckDataPermissionReqValidationError) ErrorName() string {
	return "CheckDataPermissionReqValidationError"
}

// Error satisfies the builtin error interface
func (e CheckDataPermissionReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckDataPermissionReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckDataPermissionReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckDataPermissionReqValidationError{}

// Validate checks the field values on CheckDataPermissionResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckDataPermissionResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckDataPermissionResp with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckDataPermissionRespMultiError, or nil if none found.
func (m *CheckDataPermissionResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckDataPermissionResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Allowed

	// no validation rules for DenyReason

	if len(errors) > 0 {
		return CheckDataPermissionRespMultiError(errors)
	}

	return nil
}

// CheckDataPermissionRespMultiError is an error wrapping multiple validation
// errors returned by CheckDataPermissionResp.ValidateAll() if the designated
// constraints aren't met.
type CheckDataPermissionRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckDataPermissionRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckDataPermissionRespMultiError) AllErrors() []error { return m }

// CheckDataPermissionRespValidationError is the validation error returned by
// CheckDataPermissionResp.Validate if the designated constraints aren't met.
type CheckDataPermissionRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckDataPermissionRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckDataPermissionRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckDataPermissionRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckDataPermissionRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckDataPermissionRespValidationError) ErrorName() string {
	return "CheckDataPermissionRespValidationError"
}

// Error satisfies the builtin error interface
func (e CheckDataPermissionRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckDataPermissionResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckDataPermissionRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckDataPermissionRespValidationError{}

// Validate checks the field values on CreateTenantReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateTenantReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTenantReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTenantReqMultiError, or nil if none found.
func (m *CreateTenantReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTenantReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for ContactEmail

	if len(errors) > 0 {
		return CreateTenantReqMultiError(errors)
	}

	return nil
}

// CreateTenantReqMultiError is an error wrapping multiple validation errors
// returned by CreateTenantReq.ValidateAll() if the designated constraints
// aren't met.
type CreateTenantReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTenantReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTenantReqMultiError) AllErrors() []error { return m }

// CreateTenantReqValidationError is the validation error returned by
// CreateTenantReq.Validate if the designated constraints aren't met.
type CreateTenantReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTenantReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTenantReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTenantReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTenantReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTenantReqValidationError) ErrorName() string { return "CreateTenantReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateTenantReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTenantReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTenantReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTenantReqValidationError{}

// Validate checks the field values on GetTenantReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetTenantReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTenantReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetTenantReqMultiError, or
// nil if none found.
func (m *GetTenantReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTenantReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	if len(errors) > 0 {
		return GetTenantReqMultiError(errors)
	}

	return nil
}

// GetTenantReqMultiError is an error wrapping multiple validation errors
// returned by GetTenantReq.ValidateAll() if the designated constraints aren't met.
type GetTenantReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTenantReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTenantReqMultiError) AllErrors() []error { return m }

// GetTenantReqValidationError is the validation error returned by
// GetTenantReq.Validate if the designated constraints aren't met.
type GetTenantReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTenantReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTenantReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTenantReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTenantReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTenantReqValidationError) ErrorName() string { return "GetTenantReqValidationError" }

// Error satisfies the builtin error interface
func (e GetTenantReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTenantReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTenantReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTenantReqValidationError{}

// Validate checks the field values on ListTenantsReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListTenantsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTenantsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListTenantsReqMultiError,
// or nil if none found.
func (m *ListTenantsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTenantsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListTenantsReqValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListTenantsReqValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListTenantsReqValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Keyword

	if len(errors) > 0 {
		return ListTenantsReqMultiError(errors)
	}

	return nil
}

// ListTenantsReqMultiError is an error wrapping multiple validation errors
// returned by ListTenantsReq.ValidateAll() if the designated constraints
// aren't met.
type ListTenantsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTenantsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTenantsReqMultiError) AllErrors() []error { return m }

// ListTenantsReqValidationError is the validation error returned by
// ListTenantsReq.Validate if the designated constraints aren't met.
type ListTenantsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTenantsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTenantsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTenantsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTenantsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTenantsReqValidationError) ErrorName() string { return "ListTenantsReqValidationError" }

// Error satisfies the builtin error interface
func (e ListTenantsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTenantsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTenantsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTenantsReqValidationError{}

// Validate checks the field values on ListTenantsResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListTenantsResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTenantsResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTenantsRespMultiError, or nil if none found.
func (m *ListTenantsResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTenantsResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTenantsRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTenantsRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTenantsRespValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListTenantsRespValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListTenantsRespValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListTenantsRespValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListTenantsRespMultiError(errors)
	}

	return nil
}

// ListTenantsRespMultiError is an error wrapping multiple validation errors
// returned by ListTenantsResp.ValidateAll() if the designated constraints
// aren't met.
type ListTenantsRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTenantsRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTenantsRespMultiError) AllErrors() []error { return m }

// ListTenantsRespValidationError is the validation error returned by
// ListTenantsResp.Validate if the designated constraints aren't met.
type ListTenantsRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTenantsRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTenantsRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTenantsRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTenantsRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTenantsRespValidationError) ErrorName() string { return "ListTenantsRespValidationError" }

// Error satisfies the builtin error interface
func (e ListTenantsRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTenantsResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTenantsRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTenantsRespValidationError{}

// Validate checks the field values on UpdateTenantReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateTenantReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateTenantReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateTenantReqMultiError, or nil if none found.
func (m *UpdateTenantReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateTenantReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for ContactEmail

	// no validation rules for IsActive

	if len(errors) > 0 {
		return UpdateTenantReqMultiError(errors)
	}

	return nil
}

// UpdateTenantReqMultiError is an error wrapping multiple validation errors
// returned by UpdateTenantReq.ValidateAll() if the designated constraints
// aren't met.
type UpdateTenantReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateTenantReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateTenantReqMultiError) AllErrors() []error { return m }

// UpdateTenantReqValidationError is the validation error returned by
// UpdateTenantReq.Validate if the designated constraints aren't met.
type UpdateTenantReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateTenantReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateTenantReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateTenantReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateTenantReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateTenantReqValidationError) ErrorName() string { return "UpdateTenantReqValidationError" }

// Error satisfies the builtin error interface
func (e UpdateTenantReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateTenantReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateTenantReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateTenantReqValidationError{}

// Validate checks the field values on TenantInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TenantInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TenantInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TenantInfoMultiError, or
// nil if none found.
func (m *TenantInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *TenantInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for ContactEmail

	// no validation rules for IsActive

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TenantInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TenantInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TenantInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TenantInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TenantInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TenantInfoValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TenantInfoMultiError(errors)
	}

	return nil
}

// TenantInfoMultiError is an error wrapping multiple validation errors
// returned by TenantInfo.ValidateAll() if the designated constraints aren't met.
type TenantInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantInfoMultiError) AllErrors() []error { return m }

// TenantInfoValidationError is the validation error returned by
// TenantInfo.Validate if the designated constraints aren't met.
type TenantInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantInfoValidationError) ErrorName() string { return "TenantInfoValidationError" }

// Error satisfies the builtin error interface
func (e TenantInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenantInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantInfoValidationError{}

// Validate checks the field values on GetUserReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetUserReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetUserReqMultiError, or
// nil if none found.
func (m *GetUserReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if len(errors) > 0 {
		return GetUserReqMultiError(errors)
	}

	return nil
}

// GetUserReqMultiError is an error wrapping multiple validation errors
// returned by GetUserReq.ValidateAll() if the designated constraints aren't met.
type GetUserReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserReqMultiError) AllErrors() []error { return m }

// GetUserReqValidationError is the validation error returned by
// GetUserReq.Validate if the designated constraints aren't met.
type GetUserReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserReqValidationError) ErrorName() string { return "GetUserReqValidationError" }

// Error satisfies the builtin error interface
func (e GetUserReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserReqValidationError{}

// Validate checks the field values on ListUsersReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListUsersReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUsersReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListUsersReqMultiError, or
// nil if none found.
func (m *ListUsersReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUsersReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListUsersReqValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListUsersReqValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListUsersReqValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Keyword

	// no validation rules for RoleId

	if len(errors) > 0 {
		return ListUsersReqMultiError(errors)
	}

	return nil
}

// ListUsersReqMultiError is an error wrapping multiple validation errors
// returned by ListUsersReq.ValidateAll() if the designated constraints aren't met.
type ListUsersReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUsersReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUsersReqMultiError) AllErrors() []error { return m }

// ListUsersReqValidationError is the validation error returned by
// ListUsersReq.Validate if the designated constraints aren't met.
type ListUsersReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUsersReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUsersReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUsersReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUsersReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUsersReqValidationError) ErrorName() string { return "ListUsersReqValidationError" }

// Error satisfies the builtin error interface
func (e ListUsersReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUsersReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUsersReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUsersReqValidationError{}

// Validate checks the field values on ListUsersResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListUsersResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUsersResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListUsersRespMultiError, or
// nil if none found.
func (m *ListUsersResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUsersResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListUsersRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListUsersRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListUsersRespValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListUsersRespValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListUsersRespValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListUsersRespValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListUsersRespMultiError(errors)
	}

	return nil
}

// ListUsersRespMultiError is an error wrapping multiple validation errors
// returned by ListUsersResp.ValidateAll() if the designated constraints
// aren't met.
type ListUsersRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUsersRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUsersRespMultiError) AllErrors() []error { return m }

// ListUsersRespValidationError is the validation error returned by
// ListUsersResp.Validate if the designated constraints aren't met.
type ListUsersRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUsersRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUsersRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUsersRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUsersRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUsersRespValidationError) ErrorName() string { return "ListUsersRespValidationError" }

// Error satisfies the builtin error interface
func (e ListUsersRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUsersResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUsersRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUsersRespValidationError{}

// Validate checks the field values on UserInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserInfoMultiError, or nil
// if none found.
func (m *UserInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *UserInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for TenantId

	// no validation rules for Username

	// no validation rules for DisplayName

	// no validation rules for Email

	// no validation rules for AvatarUrl

	// no validation rules for IsActive

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLastLoginAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserInfoValidationError{
					field:  "LastLoginAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserInfoValidationError{
					field:  "LastLoginAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastLoginAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserInfoValidationError{
				field:  "LastLoginAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UserInfoMultiError(errors)
	}

	return nil
}

// UserInfoMultiError is an error wrapping multiple validation errors returned
// by UserInfo.ValidateAll() if the designated constraints aren't met.
type UserInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserInfoMultiError) AllErrors() []error { return m }

// UserInfoValidationError is the validation error returned by
// UserInfo.Validate if the designated constraints aren't met.
type UserInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserInfoValidationError) ErrorName() string { return "UserInfoValidationError" }

// Error satisfies the builtin error interface
func (e UserInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserInfoValidationError{}

// Validate checks the field values on AssignRoleReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AssignRoleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AssignRoleReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AssignRoleReqMultiError, or
// nil if none found.
func (m *AssignRoleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *AssignRoleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for RoleId

	// no validation rules for TenantId

	if len(errors) > 0 {
		return AssignRoleReqMultiError(errors)
	}

	return nil
}

// AssignRoleReqMultiError is an error wrapping multiple validation errors
// returned by AssignRoleReq.ValidateAll() if the designated constraints
// aren't met.
type AssignRoleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AssignRoleReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AssignRoleReqMultiError) AllErrors() []error { return m }

// AssignRoleReqValidationError is the validation error returned by
// AssignRoleReq.Validate if the designated constraints aren't met.
type AssignRoleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AssignRoleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AssignRoleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AssignRoleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AssignRoleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AssignRoleReqValidationError) ErrorName() string { return "AssignRoleReqValidationError" }

// Error satisfies the builtin error interface
func (e AssignRoleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAssignRoleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AssignRoleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AssignRoleReqValidationError{}

// Validate checks the field values on RemoveRoleReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RemoveRoleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoveRoleReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RemoveRoleReqMultiError, or
// nil if none found.
func (m *RemoveRoleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoveRoleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for RoleId

	if len(errors) > 0 {
		return RemoveRoleReqMultiError(errors)
	}

	return nil
}

// RemoveRoleReqMultiError is an error wrapping multiple validation errors
// returned by RemoveRoleReq.ValidateAll() if the designated constraints
// aren't met.
type RemoveRoleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoveRoleReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoveRoleReqMultiError) AllErrors() []error { return m }

// RemoveRoleReqValidationError is the validation error returned by
// RemoveRoleReq.Validate if the designated constraints aren't met.
type RemoveRoleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveRoleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveRoleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveRoleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveRoleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveRoleReqValidationError) ErrorName() string { return "RemoveRoleReqValidationError" }

// Error satisfies the builtin error interface
func (e RemoveRoleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveRoleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveRoleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveRoleReqValidationError{}

// Validate checks the field values on ListRolesReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListRolesReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRolesReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListRolesReqMultiError, or
// nil if none found.
func (m *ListRolesReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRolesReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	if len(errors) > 0 {
		return ListRolesReqMultiError(errors)
	}

	return nil
}

// ListRolesReqMultiError is an error wrapping multiple validation errors
// returned by ListRolesReq.ValidateAll() if the designated constraints aren't met.
type ListRolesReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRolesReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRolesReqMultiError) AllErrors() []error { return m }

// ListRolesReqValidationError is the validation error returned by
// ListRolesReq.Validate if the designated constraints aren't met.
type ListRolesReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRolesReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRolesReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRolesReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRolesReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRolesReqValidationError) ErrorName() string { return "ListRolesReqValidationError" }

// Error satisfies the builtin error interface
func (e ListRolesReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRolesReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRolesReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRolesReqValidationError{}

// Validate checks the field values on ListRolesResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListRolesResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRolesResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListRolesRespMultiError, or
// nil if none found.
func (m *ListRolesResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRolesResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRolesRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRolesRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRolesRespValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListRolesRespMultiError(errors)
	}

	return nil
}

// ListRolesRespMultiError is an error wrapping multiple validation errors
// returned by ListRolesResp.ValidateAll() if the designated constraints
// aren't met.
type ListRolesRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRolesRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRolesRespMultiError) AllErrors() []error { return m }

// ListRolesRespValidationError is the validation error returned by
// ListRolesResp.Validate if the designated constraints aren't met.
type ListRolesRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRolesRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRolesRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRolesRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRolesRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRolesRespValidationError) ErrorName() string { return "ListRolesRespValidationError" }

// Error satisfies the builtin error interface
func (e ListRolesRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRolesResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRolesRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRolesRespValidationError{}

// Validate checks the field values on CreateRoleReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateRoleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRoleReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateRoleReqMultiError, or
// nil if none found.
func (m *CreateRoleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRoleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for Name

	// no validation rules for Description

	if len(errors) > 0 {
		return CreateRoleReqMultiError(errors)
	}

	return nil
}

// CreateRoleReqMultiError is an error wrapping multiple validation errors
// returned by CreateRoleReq.ValidateAll() if the designated constraints
// aren't met.
type CreateRoleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRoleReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRoleReqMultiError) AllErrors() []error { return m }

// CreateRoleReqValidationError is the validation error returned by
// CreateRoleReq.Validate if the designated constraints aren't met.
type CreateRoleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRoleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRoleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRoleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRoleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRoleReqValidationError) ErrorName() string { return "CreateRoleReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateRoleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRoleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRoleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRoleReqValidationError{}

// Validate checks the field values on UpdateRoleReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UpdateRoleReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRoleReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UpdateRoleReqMultiError, or
// nil if none found.
func (m *UpdateRoleReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRoleReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleId

	// no validation rules for Name

	// no validation rules for Description

	if len(errors) > 0 {
		return UpdateRoleReqMultiError(errors)
	}

	return nil
}

// UpdateRoleReqMultiError is an error wrapping multiple validation errors
// returned by UpdateRoleReq.ValidateAll() if the designated constraints
// aren't met.
type UpdateRoleReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRoleReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRoleReqMultiError) AllErrors() []error { return m }

// UpdateRoleReqValidationError is the validation error returned by
// UpdateRoleReq.Validate if the designated constraints aren't met.
type UpdateRoleReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRoleReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRoleReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRoleReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRoleReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRoleReqValidationError) ErrorName() string { return "UpdateRoleReqValidationError" }

// Error satisfies the builtin error interface
func (e UpdateRoleReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRoleReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRoleReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRoleReqValidationError{}

// Validate checks the field values on RoleInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleInfoMultiError, or nil
// if none found.
func (m *RoleInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoleId

	// no validation rules for TenantId

	// no validation rules for Name

	// no validation rules for Description

	// no validation rules for IsSystem

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RoleInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RoleInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RoleInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RoleInfoMultiError(errors)
	}

	return nil
}

// RoleInfoMultiError is an error wrapping multiple validation errors returned
// by RoleInfo.ValidateAll() if the designated constraints aren't met.
type RoleInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleInfoMultiError) AllErrors() []error { return m }

// RoleInfoValidationError is the validation error returned by
// RoleInfo.Validate if the designated constraints aren't met.
type RoleInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleInfoValidationError) ErrorName() string { return "RoleInfoValidationError" }

// Error satisfies the builtin error interface
func (e RoleInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleInfoValidationError{}

// Validate checks the field values on SyncUsersReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SyncUsersReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncUsersReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SyncUsersReqMultiError, or
// nil if none found.
func (m *SyncUsersReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncUsersReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	if len(errors) > 0 {
		return SyncUsersReqMultiError(errors)
	}

	return nil
}

// SyncUsersReqMultiError is an error wrapping multiple validation errors
// returned by SyncUsersReq.ValidateAll() if the designated constraints aren't met.
type SyncUsersReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncUsersReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncUsersReqMultiError) AllErrors() []error { return m }

// SyncUsersReqValidationError is the validation error returned by
// SyncUsersReq.Validate if the designated constraints aren't met.
type SyncUsersReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncUsersReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncUsersReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncUsersReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncUsersReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncUsersReqValidationError) ErrorName() string { return "SyncUsersReqValidationError" }

// Error satisfies the builtin error interface
func (e SyncUsersReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncUsersReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncUsersReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncUsersReqValidationError{}

// Validate checks the field values on SyncUsersResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SyncUsersResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncUsersResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SyncUsersRespMultiError, or
// nil if none found.
func (m *SyncUsersResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncUsersResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SyncedCount

	// no validation rules for DisabledCount

	// no validation rules for Message

	if len(errors) > 0 {
		return SyncUsersRespMultiError(errors)
	}

	return nil
}

// SyncUsersRespMultiError is an error wrapping multiple validation errors
// returned by SyncUsersResp.ValidateAll() if the designated constraints
// aren't met.
type SyncUsersRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncUsersRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncUsersRespMultiError) AllErrors() []error { return m }

// SyncUsersRespValidationError is the validation error returned by
// SyncUsersResp.Validate if the designated constraints aren't met.
type SyncUsersRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncUsersRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncUsersRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncUsersRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncUsersRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncUsersRespValidationError) ErrorName() string { return "SyncUsersRespValidationError" }

// Error satisfies the builtin error interface
func (e SyncUsersRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncUsersResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncUsersRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncUsersRespValidationError{}
