// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: crsystem/v1/iam.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationIAMServiceAssignRole = "/crsystem.v1.IAMService/AssignRole"
const OperationIAMServiceCreateRole = "/crsystem.v1.IAMService/CreateRole"
const OperationIAMServiceCreateTenant = "/crsystem.v1.IAMService/CreateTenant"
const OperationIAMServiceGetTenant = "/crsystem.v1.IAMService/GetTenant"
const OperationIAMServiceGetUser = "/crsystem.v1.IAMService/GetUser"
const OperationIAMServiceListRoles = "/crsystem.v1.IAMService/ListRoles"
const OperationIAMServiceListTenants = "/crsystem.v1.IAMService/ListTenants"
const OperationIAMServiceListUsers = "/crsystem.v1.IAMService/ListUsers"
const OperationIAMServiceRemoveRole = "/crsystem.v1.IAMService/RemoveRole"
const OperationIAMServiceSyncUsersFromKeycloak = "/crsystem.v1.IAMService/SyncUsersFromKeycloak"
const OperationIAMServiceUpdateRole = "/crsystem.v1.IAMService/UpdateRole"
const OperationIAMServiceUpdateTenant = "/crsystem.v1.IAMService/UpdateTenant"

type IAMServiceHTTPServer interface {
	// AssignRole 分配用户角色
	AssignRole(context.Context, *AssignRoleReq) (*OperateResult, error)
	// CreateRole 创建自定义角色
	CreateRole(context.Context, *CreateRoleReq) (*RoleInfo, error)
	// CreateTenant 创建租户
	CreateTenant(context.Context, *CreateTenantReq) (*TenantInfo, error)
	// GetTenant 获取租户详情
	GetTenant(context.Context, *GetTenantReq) (*TenantInfo, error)
	// GetUser 获取用户信息
	GetUser(context.Context, *GetUserReq) (*UserInfo, error)
	// ListRoles 获取角色列表
	ListRoles(context.Context, *ListRolesReq) (*ListRolesResp, error)
	// ListTenants 获取租户列表
	ListTenants(context.Context, *ListTenantsReq) (*ListTenantsResp, error)
	// ListUsers 获取租户下用户列表
	ListUsers(context.Context, *ListUsersReq) (*ListUsersResp, error)
	// RemoveRole 移除用户角色
	RemoveRole(context.Context, *RemoveRoleReq) (*OperateResult, error)
	// SyncUsersFromKeycloak 手动触发Keycloak用户同步
	SyncUsersFromKeycloak(context.Context, *SyncUsersReq) (*SyncUsersResp, error)
	// UpdateRole 更新角色权限
	UpdateRole(context.Context, *UpdateRoleReq) (*RoleInfo, error)
	// UpdateTenant 更新租户信息
	UpdateTenant(context.Context, *UpdateTenantReq) (*TenantInfo, error)
}

func RegisterIAMServiceHTTPServer(s *http.Server, srv IAMServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/tenants", _IAMService_CreateTenant0_HTTP_Handler(srv))
	r.GET("/api/v1/tenants/{tenant_id}", _IAMService_GetTenant0_HTTP_Handler(srv))
	r.GET("/api/v1/tenants", _IAMService_ListTenants0_HTTP_Handler(srv))
	r.PUT("/api/v1/tenants/{tenant_id}", _IAMService_UpdateTenant0_HTTP_Handler(srv))
	r.GET("/api/v1/users/{user_id}", _IAMService_GetUser0_HTTP_Handler(srv))
	r.GET("/api/v1/tenants/{tenant_id}/users", _IAMService_ListUsers0_HTTP_Handler(srv))
	r.POST("/api/v1/users/{user_id}/roles", _IAMService_AssignRole0_HTTP_Handler(srv))
	r.DELETE("/api/v1/users/{user_id}/roles/{role_id}", _IAMService_RemoveRole0_HTTP_Handler(srv))
	r.GET("/api/v1/tenants/{tenant_id}/roles", _IAMService_ListRoles0_HTTP_Handler(srv))
	r.POST("/api/v1/tenants/{tenant_id}/roles", _IAMService_CreateRole0_HTTP_Handler(srv))
	r.PUT("/api/v1/roles/{role_id}", _IAMService_UpdateRole0_HTTP_Handler(srv))
	r.POST("/api/v1/keycloak/sync", _IAMService_SyncUsersFromKeycloak0_HTTP_Handler(srv))
}

func _IAMService_CreateTenant0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTenantReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceCreateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTenant(ctx, req.(*CreateTenantReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantInfo)
		return ctx.Result(200, reply)
	}
}

func _IAMService_GetTenant0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTenantReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceGetTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTenant(ctx, req.(*GetTenantReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantInfo)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ListTenants0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTenantsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceListTenants)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTenants(ctx, req.(*ListTenantsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTenantsResp)
		return ctx.Result(200, reply)
	}
}

func _IAMService_UpdateTenant0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTenantReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceUpdateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTenant(ctx, req.(*UpdateTenantReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TenantInfo)
		return ctx.Result(200, reply)
	}
}

func _IAMService_GetUser0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceGetUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser(ctx, req.(*GetUserReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserInfo)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ListUsers0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUsersReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceListUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUsers(ctx, req.(*ListUsersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUsersResp)
		return ctx.Result(200, reply)
	}
}

func _IAMService_AssignRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignRoleReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceAssignRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignRole(ctx, req.(*AssignRoleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _IAMService_RemoveRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveRoleReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceRemoveRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveRole(ctx, req.(*RemoveRoleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ListRoles0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRolesReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceListRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoles(ctx, req.(*ListRolesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRolesResp)
		return ctx.Result(200, reply)
	}
}

func _IAMService_CreateRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRoleReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceCreateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRole(ctx, req.(*CreateRoleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RoleInfo)
		return ctx.Result(200, reply)
	}
}

func _IAMService_UpdateRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRoleReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceUpdateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRole(ctx, req.(*UpdateRoleReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RoleInfo)
		return ctx.Result(200, reply)
	}
}

func _IAMService_SyncUsersFromKeycloak0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncUsersReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceSyncUsersFromKeycloak)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncUsersFromKeycloak(ctx, req.(*SyncUsersReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncUsersResp)
		return ctx.Result(200, reply)
	}
}

type IAMServiceHTTPClient interface {
	// AssignRole 分配用户角色
	AssignRole(ctx context.Context, req *AssignRoleReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// CreateRole 创建自定义角色
	CreateRole(ctx context.Context, req *CreateRoleReq, opts ...http.CallOption) (rsp *RoleInfo, err error)
	// CreateTenant 创建租户
	CreateTenant(ctx context.Context, req *CreateTenantReq, opts ...http.CallOption) (rsp *TenantInfo, err error)
	// GetTenant 获取租户详情
	GetTenant(ctx context.Context, req *GetTenantReq, opts ...http.CallOption) (rsp *TenantInfo, err error)
	// GetUser 获取用户信息
	GetUser(ctx context.Context, req *GetUserReq, opts ...http.CallOption) (rsp *UserInfo, err error)
	// ListRoles 获取角色列表
	ListRoles(ctx context.Context, req *ListRolesReq, opts ...http.CallOption) (rsp *ListRolesResp, err error)
	// ListTenants 获取租户列表
	ListTenants(ctx context.Context, req *ListTenantsReq, opts ...http.CallOption) (rsp *ListTenantsResp, err error)
	// ListUsers 获取租户下用户列表
	ListUsers(ctx context.Context, req *ListUsersReq, opts ...http.CallOption) (rsp *ListUsersResp, err error)
	// RemoveRole 移除用户角色
	RemoveRole(ctx context.Context, req *RemoveRoleReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// SyncUsersFromKeycloak 手动触发Keycloak用户同步
	SyncUsersFromKeycloak(ctx context.Context, req *SyncUsersReq, opts ...http.CallOption) (rsp *SyncUsersResp, err error)
	// UpdateRole 更新角色权限
	UpdateRole(ctx context.Context, req *UpdateRoleReq, opts ...http.CallOption) (rsp *RoleInfo, err error)
	// UpdateTenant 更新租户信息
	UpdateTenant(ctx context.Context, req *UpdateTenantReq, opts ...http.CallOption) (rsp *TenantInfo, err error)
}

type IAMServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewIAMServiceHTTPClient(client *http.Client) IAMServiceHTTPClient {
	return &IAMServiceHTTPClientImpl{client}
}

// AssignRole 分配用户角色
func (c *IAMServiceHTTPClientImpl) AssignRole(ctx context.Context, in *AssignRoleReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/users/{user_id}/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceAssignRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateRole 创建自定义角色
func (c *IAMServiceHTTPClientImpl) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...http.CallOption) (*RoleInfo, error) {
	var out RoleInfo
	pattern := "/api/v1/tenants/{tenant_id}/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceCreateRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTenant 创建租户
func (c *IAMServiceHTTPClientImpl) CreateTenant(ctx context.Context, in *CreateTenantReq, opts ...http.CallOption) (*TenantInfo, error) {
	var out TenantInfo
	pattern := "/api/v1/tenants"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceCreateTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTenant 获取租户详情
func (c *IAMServiceHTTPClientImpl) GetTenant(ctx context.Context, in *GetTenantReq, opts ...http.CallOption) (*TenantInfo, error) {
	var out TenantInfo
	pattern := "/api/v1/tenants/{tenant_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceGetTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUser 获取用户信息
func (c *IAMServiceHTTPClientImpl) GetUser(ctx context.Context, in *GetUserReq, opts ...http.CallOption) (*UserInfo, error) {
	var out UserInfo
	pattern := "/api/v1/users/{user_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceGetUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRoles 获取角色列表
func (c *IAMServiceHTTPClientImpl) ListRoles(ctx context.Context, in *ListRolesReq, opts ...http.CallOption) (*ListRolesResp, error) {
	var out ListRolesResp
	pattern := "/api/v1/tenants/{tenant_id}/roles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceListRoles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTenants 获取租户列表
func (c *IAMServiceHTTPClientImpl) ListTenants(ctx context.Context, in *ListTenantsReq, opts ...http.CallOption) (*ListTenantsResp, error) {
	var out ListTenantsResp
	pattern := "/api/v1/tenants"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceListTenants))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListUsers 获取租户下用户列表
func (c *IAMServiceHTTPClientImpl) ListUsers(ctx context.Context, in *ListUsersReq, opts ...http.CallOption) (*ListUsersResp, error) {
	var out ListUsersResp
	pattern := "/api/v1/tenants/{tenant_id}/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceListUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveRole 移除用户角色
func (c *IAMServiceHTTPClientImpl) RemoveRole(ctx context.Context, in *RemoveRoleReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/users/{user_id}/roles/{role_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceRemoveRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SyncUsersFromKeycloak 手动触发Keycloak用户同步
func (c *IAMServiceHTTPClientImpl) SyncUsersFromKeycloak(ctx context.Context, in *SyncUsersReq, opts ...http.CallOption) (*SyncUsersResp, error) {
	var out SyncUsersResp
	pattern := "/api/v1/keycloak/sync"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceSyncUsersFromKeycloak))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateRole 更新角色权限
func (c *IAMServiceHTTPClientImpl) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...http.CallOption) (*RoleInfo, error) {
	var out RoleInfo
	pattern := "/api/v1/roles/{role_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceUpdateRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTenant 更新租户信息
func (c *IAMServiceHTTPClientImpl) UpdateTenant(ctx context.Context, in *UpdateTenantReq, opts ...http.CallOption) (*TenantInfo, error) {
	var out TenantInfo
	pattern := "/api/v1/tenants/{tenant_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceUpdateTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
