// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: crsystem/v1/job_scheduler.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationJobSchedulerServiceGetJob = "/crsystem.v1.JobSchedulerService/GetJob"
const OperationJobSchedulerServiceListJobExecutions = "/crsystem.v1.JobSchedulerService/ListJobExecutions"
const OperationJobSchedulerServiceListJobs = "/crsystem.v1.JobSchedulerService/ListJobs"
const OperationJobSchedulerServiceSetJobEnabled = "/crsystem.v1.JobSchedulerService/SetJobEnabled"
const OperationJobSchedulerServiceTriggerJob = "/crsystem.v1.JobSchedulerService/TriggerJob"

type JobSchedulerServiceHTTPServer interface {
	// GetJob 获取任务详情
	GetJob(context.Context, *GetJobReq) (*JobInfo, error)
	// ListJobExecutions 获取任务执行记录
	ListJobExecutions(context.Context, *ListJobExecutionsReq) (*ListJobExecutionsResp, error)
	// ListJobs 获取定时任务列表
	ListJobs(context.Context, *ListJobsReq) (*ListJobsResp, error)
	// SetJobEnabled 启用/停用任务
	SetJobEnabled(context.Context, *SetJobEnabledReq) (*OperateResult, error)
	// TriggerJob 手动触发任务执行（运维补偿场景）
	TriggerJob(context.Context, *TriggerJobReq) (*JobExecutionInfo, error)
}

func RegisterJobSchedulerServiceHTTPServer(s *http.Server, srv JobSchedulerServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/jobs", _JobSchedulerService_ListJobs0_HTTP_Handler(srv))
	r.GET("/api/v1/jobs/{job_id}", _JobSchedulerService_GetJob0_HTTP_Handler(srv))
	r.POST("/api/v1/jobs/{job_id}/trigger", _JobSchedulerService_TriggerJob0_HTTP_Handler(srv))
	r.PUT("/api/v1/jobs/{job_id}/enabled", _JobSchedulerService_SetJobEnabled0_HTTP_Handler(srv))
	r.GET("/api/v1/jobs/{job_id}/executions", _JobSchedulerService_ListJobExecutions0_HTTP_Handler(srv))
}

func _JobSchedulerService_ListJobs0_HTTP_Handler(srv JobSchedulerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListJobsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobSchedulerServiceListJobs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListJobs(ctx, req.(*ListJobsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListJobsResp)
		return ctx.Result(200, reply)
	}
}

func _JobSchedulerService_GetJob0_HTTP_Handler(srv JobSchedulerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetJobReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobSchedulerServiceGetJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetJob(ctx, req.(*GetJobReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobInfo)
		return ctx.Result(200, reply)
	}
}

func _JobSchedulerService_TriggerJob0_HTTP_Handler(srv JobSchedulerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TriggerJobReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobSchedulerServiceTriggerJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TriggerJob(ctx, req.(*TriggerJobReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*JobExecutionInfo)
		return ctx.Result(200, reply)
	}
}

func _JobSchedulerService_SetJobEnabled0_HTTP_Handler(srv JobSchedulerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetJobEnabledReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobSchedulerServiceSetJobEnabled)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetJobEnabled(ctx, req.(*SetJobEnabledReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _JobSchedulerService_ListJobExecutions0_HTTP_Handler(srv JobSchedulerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListJobExecutionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationJobSchedulerServiceListJobExecutions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListJobExecutions(ctx, req.(*ListJobExecutionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListJobExecutionsResp)
		return ctx.Result(200, reply)
	}
}

type JobSchedulerServiceHTTPClient interface {
	// GetJob 获取任务详情
	GetJob(ctx context.Context, req *GetJobReq, opts ...http.CallOption) (rsp *JobInfo, err error)
	// ListJobExecutions 获取任务执行记录
	ListJobExecutions(ctx context.Context, req *ListJobExecutionsReq, opts ...http.CallOption) (rsp *ListJobExecutionsResp, err error)
	// ListJobs 获取定时任务列表
	ListJobs(ctx context.Context, req *ListJobsReq, opts ...http.CallOption) (rsp *ListJobsResp, err error)
	// SetJobEnabled 启用/停用任务
	SetJobEnabled(ctx context.Context, req *SetJobEnabledReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// TriggerJob 手动触发任务执行（运维补偿场景）
	TriggerJob(ctx context.Context, req *TriggerJobReq, opts ...http.CallOption) (rsp *JobExecutionInfo, err error)
}

type JobSchedulerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewJobSchedulerServiceHTTPClient(client *http.Client) JobSchedulerServiceHTTPClient {
	return &JobSchedulerServiceHTTPClientImpl{client}
}

// GetJob 获取任务详情
func (c *JobSchedulerServiceHTTPClientImpl) GetJob(ctx context.Context, in *GetJobReq, opts ...http.CallOption) (*JobInfo, error) {
	var out JobInfo
	pattern := "/api/v1/jobs/{job_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobSchedulerServiceGetJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListJobExecutions 获取任务执行记录
func (c *JobSchedulerServiceHTTPClientImpl) ListJobExecutions(ctx context.Context, in *ListJobExecutionsReq, opts ...http.CallOption) (*ListJobExecutionsResp, error) {
	var out ListJobExecutionsResp
	pattern := "/api/v1/jobs/{job_id}/executions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobSchedulerServiceListJobExecutions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListJobs 获取定时任务列表
func (c *JobSchedulerServiceHTTPClientImpl) ListJobs(ctx context.Context, in *ListJobsReq, opts ...http.CallOption) (*ListJobsResp, error) {
	var out ListJobsResp
	pattern := "/api/v1/jobs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationJobSchedulerServiceListJobs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SetJobEnabled 启用/停用任务
func (c *JobSchedulerServiceHTTPClientImpl) SetJobEnabled(ctx context.Context, in *SetJobEnabledReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/jobs/{job_id}/enabled"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationJobSchedulerServiceSetJobEnabled))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TriggerJob 手动触发任务执行（运维补偿场景）
func (c *JobSchedulerServiceHTTPClientImpl) TriggerJob(ctx context.Context, in *TriggerJobReq, opts ...http.CallOption) (*JobExecutionInfo, error) {
	var out JobExecutionInfo
	pattern := "/api/v1/jobs/{job_id}/trigger"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationJobSchedulerServiceTriggerJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
