// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: crsystem/v1/job_scheduler.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobSchedulerService_ListJobs_FullMethodName          = "/crsystem.v1.JobSchedulerService/ListJobs"
	JobSchedulerService_GetJob_FullMethodName            = "/crsystem.v1.JobSchedulerService/GetJob"
	JobSchedulerService_TriggerJob_FullMethodName        = "/crsystem.v1.JobSchedulerService/TriggerJob"
	JobSchedulerService_SetJobEnabled_FullMethodName     = "/crsystem.v1.JobSchedulerService/SetJobEnabled"
	JobSchedulerService_ListJobExecutions_FullMethodName = "/crsystem.v1.JobSchedulerService/ListJobExecutions"
)

// JobSchedulerServiceClient is the client API for JobSchedulerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================
// job-scheduler 定时任务服务（HLD §2.5 / LLD §3.6）
// 核心职责：仓库增量同步触发、过期缓存清理、每日离线统计、
//
//	数据对账修复、Token自动轮换刷新
//
// 实现方式：K8s CronJob + 内部任务管理器，不引入额外定时中间件
// ============================================================
type JobSchedulerServiceClient interface {
	// 获取定时任务列表
	ListJobs(ctx context.Context, in *ListJobsReq, opts ...grpc.CallOption) (*ListJobsResp, error)
	// 获取任务详情
	GetJob(ctx context.Context, in *GetJobReq, opts ...grpc.CallOption) (*JobInfo, error)
	// 手动触发任务执行（运维补偿场景）
	TriggerJob(ctx context.Context, in *TriggerJobReq, opts ...grpc.CallOption) (*JobExecutionInfo, error)
	// 启用/停用任务
	SetJobEnabled(ctx context.Context, in *SetJobEnabledReq, opts ...grpc.CallOption) (*OperateResult, error)
	// 获取任务执行记录
	ListJobExecutions(ctx context.Context, in *ListJobExecutionsReq, opts ...grpc.CallOption) (*ListJobExecutionsResp, error)
}

type jobSchedulerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobSchedulerServiceClient(cc grpc.ClientConnInterface) JobSchedulerServiceClient {
	return &jobSchedulerServiceClient{cc}
}

func (c *jobSchedulerServiceClient) ListJobs(ctx context.Context, in *ListJobsReq, opts ...grpc.CallOption) (*ListJobsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResp)
	err := c.cc.Invoke(ctx, JobSchedulerService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedulerServiceClient) GetJob(ctx context.Context, in *GetJobReq, opts ...grpc.CallOption) (*JobInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobInfo)
	err := c.cc.Invoke(ctx, JobSchedulerService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedulerServiceClient) TriggerJob(ctx context.Context, in *TriggerJobReq, opts ...grpc.CallOption) (*JobExecutionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobExecutionInfo)
	err := c.cc.Invoke(ctx, JobSchedulerService_TriggerJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedulerServiceClient) SetJobEnabled(ctx context.Context, in *SetJobEnabledReq, opts ...grpc.CallOption) (*OperateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResult)
	err := c.cc.Invoke(ctx, JobSchedulerService_SetJobEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobSchedulerServiceClient) ListJobExecutions(ctx context.Context, in *ListJobExecutionsReq, opts ...grpc.CallOption) (*ListJobExecutionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobExecutionsResp)
	err := c.cc.Invoke(ctx, JobSchedulerService_ListJobExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobSchedulerServiceServer is the server API for JobSchedulerService service.
// All implementations must embed UnimplementedJobSchedulerServiceServer
// for forward compatibility.
//
// ============================================================
// job-scheduler 定时任务服务（HLD §2.5 / LLD §3.6）
// 核心职责：仓库增量同步触发、过期缓存清理、每日离线统计、
//
//	数据对账修复、Token自动轮换刷新
//
// 实现方式：K8s CronJob + 内部任务管理器，不引入额外定时中间件
// ============================================================
type JobSchedulerServiceServer interface {
	// 获取定时任务列表
	ListJobs(context.Context, *ListJobsReq) (*ListJobsResp, error)
	// 获取任务详情
	GetJob(context.Context, *GetJobReq) (*JobInfo, error)
	// 手动触发任务执行（运维补偿场景）
	TriggerJob(context.Context, *TriggerJobReq) (*JobExecutionInfo, error)
	// 启用/停用任务
	SetJobEnabled(context.Context, *SetJobEnabledReq) (*OperateResult, error)
	// 获取任务执行记录
	ListJobExecutions(context.Context, *ListJobExecutionsReq) (*ListJobExecutionsResp, error)
	mustEmbedUnimplementedJobSchedulerServiceServer()
}

// UnimplementedJobSchedulerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobSchedulerServiceServer struct{}

func (UnimplementedJobSchedulerServiceServer) ListJobs(context.Context, *ListJobsReq) (*ListJobsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedJobSchedulerServiceServer) GetJob(context.Context, *GetJobReq) (*JobInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedJobSchedulerServiceServer) TriggerJob(context.Context, *TriggerJobReq) (*JobExecutionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerJob not implemented")
}
func (UnimplementedJobSchedulerServiceServer) SetJobEnabled(context.Context, *SetJobEnabledReq) (*OperateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetJobEnabled not implemented")
}
func (UnimplementedJobSchedulerServiceServer) ListJobExecutions(context.Context, *ListJobExecutionsReq) (*ListJobExecutionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobExecutions not implemented")
}
func (UnimplementedJobSchedulerServiceServer) mustEmbedUnimplementedJobSchedulerServiceServer() {}
func (UnimplementedJobSchedulerServiceServer) testEmbeddedByValue()                             {}

// UnsafeJobSchedulerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobSchedulerServiceServer will
// result in compilation errors.
type UnsafeJobSchedulerServiceServer interface {
	mustEmbedUnimplementedJobSchedulerServiceServer()
}

func RegisterJobSchedulerServiceServer(s grpc.ServiceRegistrar, srv JobSchedulerServiceServer) {
	// If the following call panics, it indicates UnimplementedJobSchedulerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobSchedulerService_ServiceDesc, srv)
}

func _JobSchedulerService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedulerServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSchedulerService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedulerServiceServer).ListJobs(ctx, req.(*ListJobsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSchedulerService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedulerServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSchedulerService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedulerServiceServer).GetJob(ctx, req.(*GetJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSchedulerService_TriggerJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedulerServiceServer).TriggerJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSchedulerService_TriggerJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedulerServiceServer).TriggerJob(ctx, req.(*TriggerJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSchedulerService_SetJobEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetJobEnabledReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedulerServiceServer).SetJobEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSchedulerService_SetJobEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedulerServiceServer).SetJobEnabled(ctx, req.(*SetJobEnabledReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobSchedulerService_ListJobExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobExecutionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSchedulerServiceServer).ListJobExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSchedulerService_ListJobExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSchedulerServiceServer).ListJobExecutions(ctx, req.(*ListJobExecutionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// JobSchedulerService_ServiceDesc is the grpc.ServiceDesc for JobSchedulerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobSchedulerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crsystem.v1.JobSchedulerService",
	HandlerType: (*JobSchedulerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListJobs",
			Handler:    _JobSchedulerService_ListJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobSchedulerService_GetJob_Handler,
		},
		{
			MethodName: "TriggerJob",
			Handler:    _JobSchedulerService_TriggerJob_Handler,
		},
		{
			MethodName: "SetJobEnabled",
			Handler:    _JobSchedulerService_SetJobEnabled_Handler,
		},
		{
			MethodName: "ListJobExecutions",
			Handler:    _JobSchedulerService_ListJobExecutions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crsystem/v1/job_scheduler.proto",
}
