// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: crsystem/v1/job_scheduler.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobType 定时任务类型（LLD §3.6 任务清单）
type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED           JobType = 0
	JobType_JOB_TYPE_REPO_INCREMENTAL_SYNC JobType = 1 // 仓库增量同步（每6小时）
	JobType_JOB_TYPE_DATA_RECONCILIATION   JobType = 2 // PG单据与MQ消息对账（每日01:00）
	JobType_JOB_TYPE_CACHE_CLEANUP         JobType = 3 // Redis过期缓存清理（每日02:00）
	JobType_JOB_TYPE_TOKEN_REFRESH         JobType = 4 // Git授权Token刷新（每日03:00）
	JobType_JOB_TYPE_MONTHLY_REPORT        JobType = 5 // 全租户质量月报（每月首日）
	JobType_JOB_TYPE_KEYCLOAK_USER_SYNC    JobType = 6 // Keycloak账号同步（每日凌晨，LLD §3.1）
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_REPO_INCREMENTAL_SYNC",
		2: "JOB_TYPE_DATA_RECONCILIATION",
		3: "JOB_TYPE_CACHE_CLEANUP",
		4: "JOB_TYPE_TOKEN_REFRESH",
		5: "JOB_TYPE_MONTHLY_REPORT",
		6: "JOB_TYPE_KEYCLOAK_USER_SYNC",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED":           0,
		"JOB_TYPE_REPO_INCREMENTAL_SYNC": 1,
		"JOB_TYPE_DATA_RECONCILIATION":   2,
		"JOB_TYPE_CACHE_CLEANUP":         3,
		"JOB_TYPE_TOKEN_REFRESH":         4,
		"JOB_TYPE_MONTHLY_REPORT":        5,
		"JOB_TYPE_KEYCLOAK_USER_SYNC":    6,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_crsystem_v1_job_scheduler_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_crsystem_v1_job_scheduler_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{0}
}

type ListJobsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobType       string                 `protobuf:"bytes,1,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"` // 可选：按任务类型筛选
	EnabledOnly   bool                   `protobuf:"varint,2,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsReq) Reset() {
	*x = ListJobsReq{}
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsReq) ProtoMessage() {}

func (x *ListJobsReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsReq.ProtoReflect.Descriptor instead.
func (*ListJobsReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *ListJobsReq) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *ListJobsReq) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ListJobsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*JobInfo             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResp) Reset() {
	*x = ListJobsResp{}
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResp) ProtoMessage() {}

func (x *ListJobsResp) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResp.ProtoReflect.Descriptor instead.
func (*ListJobsResp) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ListJobsResp) GetItems() []*JobInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobReq) Reset() {
	*x = GetJobReq{}
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobReq) ProtoMessage() {}

func (x *GetJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobReq.ProtoReflect.Descriptor instead.
func (*GetJobReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobType       JobType                `protobuf:"varint,2,opt,name=job_type,json=jobType,proto3,enum=crsystem.v1.JobType" json:"job_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // 任务名称
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CronExpr      string                 `protobuf:"bytes,5,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"` // 调度表达式（与K8s CronJob一致）
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastRunAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	NextRunAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	LastStatus    string                 `protobuf:"bytes,9,opt,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty"` // success / failed / running
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *JobInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobInfo) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *JobInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *JobInfo) GetLastRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunAt
	}
	return nil
}

func (x *JobInfo) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *JobInfo) GetLastStatus() string {
	if x != nil {
		return x.LastStatus
	}
	return ""
}

type TriggerJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	OperatorUid   string                 `protobuf:"bytes,2,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"` // 手动触发操作人（审计记录）
	Param         string                 `protobuf:"bytes,3,opt,name=param,proto3" json:"param,omitempty"`                                // 可选：JSON格式触发参数（如指定租户/月份）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobReq) Reset() {
	*x = TriggerJobReq{}
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobReq) ProtoMessage() {}

func (x *TriggerJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobReq.ProtoReflect.Descriptor instead.
func (*TriggerJobReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerJobReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TriggerJobReq) GetOperatorUid() string {
	if x != nil {
		return x.OperatorUid
	}
	return ""
}

func (x *TriggerJobReq) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

type SetJobEnabledReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJobEnabledReq) Reset() {
	*x = SetJobEnabledReq{}
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobEnabledReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobEnabledReq) ProtoMessage() {}

func (x *SetJobEnabledReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobEnabledReq.ProtoReflect.Descriptor instead.
func (*SetJobEnabledReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *SetJobEnabledReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SetJobEnabledReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ListJobExecutionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 可选：success / failed / running
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobExecutionsReq) Reset() {
	*x = ListJobExecutionsReq{}
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobExecutionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobExecutionsReq) ProtoMessage() {}

func (x *ListJobExecutionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobExecutionsReq.ProtoReflect.Descriptor instead.
func (*ListJobExecutionsReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *ListJobExecutionsReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ListJobExecutionsReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListJobExecutionsReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListJobExecutionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*JobExecutionInfo    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *PaginationResp        `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobExecutionsResp) Reset() {
	*x = ListJobExecutionsResp{}
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobExecutionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobExecutionsResp) ProtoMessage() {}

func (x *ListJobExecutionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobExecutionsResp.ProtoReflect.Descriptor instead.
func (*ListJobExecutionsResp) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *ListJobExecutionsResp) GetItems() []*JobExecutionInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListJobExecutionsResp) GetPagination() *PaginationResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type JobExecutionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobType       JobType                `protobuf:"varint,3,opt,name=job_type,json=jobType,proto3,enum=crsystem.v1.JobType" json:"job_type,omitempty"`
	TriggerType   string                 `protobuf:"bytes,4,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`        // cron / manual / retry
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                     // running / success / failed
	AffectedCount uint32                 `protobuf:"varint,6,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"` // 本次处理的数据条数
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`     // 失败原因
	TraceId       string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                    // 链路追踪ID（Loki/Jaeger检索）
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobExecutionInfo) Reset() {
	*x = JobExecutionInfo{}
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecutionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecutionInfo) ProtoMessage() {}

func (x *JobExecutionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_job_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecutionInfo.ProtoReflect.Descriptor instead.
func (*JobExecutionInfo) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_job_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *JobExecutionInfo) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *JobExecutionInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobExecutionInfo) GetJobType() JobType {
	if x != nil {
		return x.JobType
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *JobExecutionInfo) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *JobExecutionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobExecutionInfo) GetAffectedCount() uint32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

func (x *JobExecutionInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobExecutionInfo) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *JobExecutionInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobExecutionInfo) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_crsystem_v1_job_scheduler_proto protoreflect.FileDescriptor

const file_crsystem_v1_job_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x1fcrsystem/v1/job_scheduler.proto\x12\vcrsystem.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18crsystem/v1/common.proto\"K\n" +
	"\vListJobsReq\x12\x19\n" +
	"\bjob_type\x18\x01 \x01(\tR\ajobType\x12!\n" +
	"\fenabled_only\x18\x02 \x01(\bR\venabledOnly\":\n" +
	"\fListJobsResp\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.crsystem.v1.JobInfoR\x05items\"\"\n" +
	"\tGetJobReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xd7\x02\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\bjob_type\x18\x02 \x01(\x0e2\x14.crsystem.v1.JobTypeR\ajobType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcron_expr\x18\x05 \x01(\tR\bcronExpr\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12:\n" +
	"\vlast_run_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tlastRunAt\x12:\n" +
	"\vnext_run_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x12\x1f\n" +
	"\vlast_status\x18\t \x01(\tR\n" +
	"lastStatus\"_\n" +
	"\rTriggerJobReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\foperator_uid\x18\x02 \x01(\tR\voperatorUid\x12\x14\n" +
	"\x05param\x18\x03 \x01(\tR\x05param\"C\n" +
	"\x10SetJobEnabledReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"~\n" +
	"\x14ListJobExecutionsReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x127\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x17.crsystem.v1.PaginationR\n" +
	"pagination\"\x89\x01\n" +
	"\x15ListJobExecutionsResp\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.crsystem.v1.JobExecutionInfoR\x05items\x12;\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1b.crsystem.v1.PaginationRespR\n" +
	"pagination\"\x97\x03\n" +
	"\x10JobExecutionInfo\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12/\n" +
	"\bjob_type\x18\x03 \x01(\x0e2\x14.crsystem.v1.JobTypeR\ajobType\x12!\n" +
	"\ftrigger_type\x18\x04 \x01(\tR\vtriggerType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0eaffected_count\x18\x06 \x01(\rR\raffectedCount\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt*\xdf\x01\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eJOB_TYPE_REPO_INCREMENTAL_SYNC\x10\x01\x12 \n" +
	"\x1cJOB_TYPE_DATA_RECONCILIATION\x10\x02\x12\x1a\n" +
	"\x16JOB_TYPE_CACHE_CLEANUP\x10\x03\x12\x1a\n" +
	"\x16JOB_TYPE_TOKEN_REFRESH\x10\x04\x12\x1b\n" +
	"\x17JOB_TYPE_MONTHLY_REPORT\x10\x05\x12\x1f\n" +
	"\x1bJOB_TYPE_KEYCLOAK_USER_SYNC\x10\x062\xb3\x04\n" +
	"\x13JobSchedulerService\x12U\n" +
	"\bListJobs\x12\x18.crsystem.v1.ListJobsReq\x1a\x19.crsystem.v1.ListJobsResp\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/jobs\x12U\n" +
	"\x06GetJob\x12\x16.crsystem.v1.GetJobReq\x1a\x14.crsystem.v1.JobInfo\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/jobs/{job_id}\x12q\n" +
	"\n" +
	"TriggerJob\x12\x1a.crsystem.v1.TriggerJobReq\x1a\x1d.crsystem.v1.JobExecutionInfo\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/jobs/{job_id}/trigger\x12t\n" +
	"\rSetJobEnabled\x12\x1d.crsystem.v1.SetJobEnabledReq\x1a\x1a.crsystem.v1.OperateResult\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/api/v1/jobs/{job_id}/enabled\x12\x84\x01\n" +
	"\x11ListJobExecutions\x12!.crsystem.v1.ListJobExecutionsReq\x1a\".crsystem.v1.ListJobExecutionsResp\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/jobs/{job_id}/executionsB\x1eZ\x1ccr-system/api/crsystem/v1;v1b\x06proto3"

var (
	file_crsystem_v1_job_scheduler_proto_rawDescOnce sync.Once
	file_crsystem_v1_job_scheduler_proto_rawDescData []byte
)

func file_crsystem_v1_job_scheduler_proto_rawDescGZIP() []byte {
	file_crsystem_v1_job_scheduler_proto_rawDescOnce.Do(func() {
		file_crsystem_v1_job_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crsystem_v1_job_scheduler_proto_rawDesc), len(file_crsystem_v1_job_scheduler_proto_rawDesc)))
	})
	return file_crsystem_v1_job_scheduler_proto_rawDescData
}

var file_crsystem_v1_job_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_crsystem_v1_job_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_crsystem_v1_job_scheduler_proto_goTypes = []any{
	(JobType)(0),                  // 0: crsystem.v1.JobType
	(*ListJobsReq)(nil),           // 1: crsystem.v1.ListJobsReq
	(*ListJobsResp)(nil),          // 2: crsystem.v1.ListJobsResp
	(*GetJobReq)(nil),             // 3: crsystem.v1.GetJobReq
	(*JobInfo)(nil),               // 4: crsystem.v1.JobInfo
	(*TriggerJobReq)(nil),         // 5: crsystem.v1.TriggerJobReq
	(*SetJobEnabledReq)(nil),      // 6: crsystem.v1.SetJobEnabledReq
	(*ListJobExecutionsReq)(nil),  // 7: crsystem.v1.ListJobExecutionsReq
	(*ListJobExecutionsResp)(nil), // 8: crsystem.v1.ListJobExecutionsResp
	(*JobExecutionInfo)(nil),      // 9: crsystem.v1.JobExecutionInfo
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*Pagination)(nil),            // 11: crsystem.v1.Pagination
	(*PaginationResp)(nil),        // 12: crsystem.v1.PaginationResp
	(*OperateResult)(nil),         // 13: crsystem.v1.OperateResult
}
var file_crsystem_v1_job_scheduler_proto_depIdxs = []int32{
	4,  // 0: crsystem.v1.ListJobsResp.items:type_name -> crsystem.v1.JobInfo
	0,  // 1: crsystem.v1.JobInfo.job_type:type_name -> crsystem.v1.JobType
	10, // 2: crsystem.v1.JobInfo.last_run_at:type_name -> google.protobuf.Timestamp
	10, // 3: crsystem.v1.JobInfo.next_run_at:type_name -> google.protobuf.Timestamp
	11, // 4: crsystem.v1.ListJobExecutionsReq.pagination:type_name -> crsystem.v1.Pagination
	9,  // 5: crsystem.v1.ListJobExecutionsResp.items:type_name -> crsystem.v1.JobExecutionInfo
	12, // 6: crsystem.v1.ListJobExecutionsResp.pagination:type_name -> crsystem.v1.PaginationResp
	0,  // 7: crsystem.v1.JobExecutionInfo.job_type:type_name -> crsystem.v1.JobType
	10, // 8: crsystem.v1.JobExecutionInfo.started_at:type_name -> google.protobuf.Timestamp
	10, // 9: crsystem.v1.JobExecutionInfo.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 10: crsystem.v1.JobSchedulerService.ListJobs:input_type -> crsystem.v1.ListJobsReq
	3,  // 11: crsystem.v1.JobSchedulerService.GetJob:input_type -> crsystem.v1.GetJobReq
	5,  // 12: crsystem.v1.JobSchedulerService.TriggerJob:input_type -> crsystem.v1.TriggerJobReq
	6,  // 13: crsystem.v1.JobSchedulerService.SetJobEnabled:input_type -> crsystem.v1.SetJobEnabledReq
	7,  // 14: crsystem.v1.JobSchedulerService.ListJobExecutions:input_type -> crsystem.v1.ListJobExecutionsReq
	2,  // 15: crsystem.v1.JobSchedulerService.ListJobs:output_type -> crsystem.v1.ListJobsResp
	4,  // 16: crsystem.v1.JobSchedulerService.GetJob:output_type -> crsystem.v1.JobInfo
	9,  // 17: crsystem.v1.JobSchedulerService.TriggerJob:output_type -> crsystem.v1.JobExecutionInfo
	13, // 18: crsystem.v1.JobSchedulerService.SetJobEnabled:output_type -> crsystem.v1.OperateResult
	8,  // 19: crsystem.v1.JobSchedulerService.ListJobExecutions:output_type -> crsystem.v1.ListJobExecutionsResp
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_crsystem_v1_job_scheduler_proto_init() }
func file_crsystem_v1_job_scheduler_proto_init() {
	if File_crsystem_v1_job_scheduler_proto != nil {
		return
	}
	file_crsystem_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crsystem_v1_job_scheduler_proto_rawDesc), len(file_crsystem_v1_job_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crsystem_v1_job_scheduler_proto_goTypes,
		DependencyIndexes: file_crsystem_v1_job_scheduler_proto_depIdxs,
		EnumInfos:         file_crsystem_v1_job_scheduler_proto_enumTypes,
		MessageInfos:      file_crsystem_v1_job_scheduler_proto_msgTypes,
	}.Build()
	File_crsystem_v1_job_scheduler_proto = out.File
	file_crsystem_v1_job_scheduler_proto_goTypes = nil
	file_crsystem_v1_job_scheduler_proto_depIdxs = nil
}
