// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: crsystem/v1/message.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMessageServiceBatchMarkAsRead = "/crsystem.v1.MessageService/BatchMarkAsRead"
const OperationMessageServiceGetChannelConfig = "/crsystem.v1.MessageService/GetChannelConfig"
const OperationMessageServiceGetNotificationPrefs = "/crsystem.v1.MessageService/GetNotificationPrefs"
const OperationMessageServiceGetUnreadCount = "/crsystem.v1.MessageService/GetUnreadCount"
const OperationMessageServiceListNotifications = "/crsystem.v1.MessageService/ListNotifications"
const OperationMessageServiceMarkAsRead = "/crsystem.v1.MessageService/MarkAsRead"
const OperationMessageServiceUpdateChannelConfig = "/crsystem.v1.MessageService/UpdateChannelConfig"
const OperationMessageServiceUpdateNotificationPrefs = "/crsystem.v1.MessageService/UpdateNotificationPrefs"

type MessageServiceHTTPServer interface {
	// BatchMarkAsRead 批量标记已读
	BatchMarkAsRead(context.Context, *BatchMarkAsReadReq) (*OperateResult, error)
	// GetChannelConfig 获取租户通知渠道配置
	GetChannelConfig(context.Context, *GetChannelConfigReq) (*ChannelConfig, error)
	// GetNotificationPrefs 获取用户通知偏好配置
	GetNotificationPrefs(context.Context, *GetPrefsReq) (*NotificationPrefs, error)
	// GetUnreadCount 获取未读消息数量
	GetUnreadCount(context.Context, *GetUnreadCountReq) (*UnreadCountResp, error)
	// ListNotifications 获取用户站内信列表
	ListNotifications(context.Context, *ListNotificationsReq) (*ListNotificationsResp, error)
	// MarkAsRead 标记站内信为已读
	MarkAsRead(context.Context, *MarkAsReadReq) (*OperateResult, error)
	// UpdateChannelConfig 更新租户通知渠道开关
	UpdateChannelConfig(context.Context, *UpdateChannelConfigReq) (*OperateResult, error)
	// UpdateNotificationPrefs 更新用户通知偏好
	UpdateNotificationPrefs(context.Context, *UpdatePrefsReq) (*OperateResult, error)
}

func RegisterMessageServiceHTTPServer(s *http.Server, srv MessageServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/notifications", _MessageService_ListNotifications0_HTTP_Handler(srv))
	r.POST("/api/v1/notifications/read", _MessageService_MarkAsRead0_HTTP_Handler(srv))
	r.POST("/api/v1/notifications/batch-read", _MessageService_BatchMarkAsRead0_HTTP_Handler(srv))
	r.GET("/api/v1/notifications/unread-count", _MessageService_GetUnreadCount0_HTTP_Handler(srv))
	r.GET("/api/v1/notifications/preferences", _MessageService_GetNotificationPrefs0_HTTP_Handler(srv))
	r.PUT("/api/v1/notifications/preferences", _MessageService_UpdateNotificationPrefs0_HTTP_Handler(srv))
	r.GET("/api/v1/tenants/{tenant_id}/notification-channels", _MessageService_GetChannelConfig0_HTTP_Handler(srv))
	r.PUT("/api/v1/tenants/{tenant_id}/notification-channels", _MessageService_UpdateChannelConfig0_HTTP_Handler(srv))
}

func _MessageService_ListNotifications0_HTTP_Handler(srv MessageServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNotificationsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMessageServiceListNotifications)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNotifications(ctx, req.(*ListNotificationsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNotificationsResp)
		return ctx.Result(200, reply)
	}
}

func _MessageService_MarkAsRead0_HTTP_Handler(srv MessageServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkAsReadReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMessageServiceMarkAsRead)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkAsRead(ctx, req.(*MarkAsReadReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _MessageService_BatchMarkAsRead0_HTTP_Handler(srv MessageServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchMarkAsReadReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMessageServiceBatchMarkAsRead)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchMarkAsRead(ctx, req.(*BatchMarkAsReadReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _MessageService_GetUnreadCount0_HTTP_Handler(srv MessageServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUnreadCountReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMessageServiceGetUnreadCount)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUnreadCount(ctx, req.(*GetUnreadCountReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UnreadCountResp)
		return ctx.Result(200, reply)
	}
}

func _MessageService_GetNotificationPrefs0_HTTP_Handler(srv MessageServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPrefsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMessageServiceGetNotificationPrefs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNotificationPrefs(ctx, req.(*GetPrefsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NotificationPrefs)
		return ctx.Result(200, reply)
	}
}

func _MessageService_UpdateNotificationPrefs0_HTTP_Handler(srv MessageServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePrefsReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMessageServiceUpdateNotificationPrefs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateNotificationPrefs(ctx, req.(*UpdatePrefsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

func _MessageService_GetChannelConfig0_HTTP_Handler(srv MessageServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetChannelConfigReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMessageServiceGetChannelConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChannelConfig(ctx, req.(*GetChannelConfigReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChannelConfig)
		return ctx.Result(200, reply)
	}
}

func _MessageService_UpdateChannelConfig0_HTTP_Handler(srv MessageServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateChannelConfigReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMessageServiceUpdateChannelConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateChannelConfig(ctx, req.(*UpdateChannelConfigReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperateResult)
		return ctx.Result(200, reply)
	}
}

type MessageServiceHTTPClient interface {
	// BatchMarkAsRead 批量标记已读
	BatchMarkAsRead(ctx context.Context, req *BatchMarkAsReadReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// GetChannelConfig 获取租户通知渠道配置
	GetChannelConfig(ctx context.Context, req *GetChannelConfigReq, opts ...http.CallOption) (rsp *ChannelConfig, err error)
	// GetNotificationPrefs 获取用户通知偏好配置
	GetNotificationPrefs(ctx context.Context, req *GetPrefsReq, opts ...http.CallOption) (rsp *NotificationPrefs, err error)
	// GetUnreadCount 获取未读消息数量
	GetUnreadCount(ctx context.Context, req *GetUnreadCountReq, opts ...http.CallOption) (rsp *UnreadCountResp, err error)
	// ListNotifications 获取用户站内信列表
	ListNotifications(ctx context.Context, req *ListNotificationsReq, opts ...http.CallOption) (rsp *ListNotificationsResp, err error)
	// MarkAsRead 标记站内信为已读
	MarkAsRead(ctx context.Context, req *MarkAsReadReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// UpdateChannelConfig 更新租户通知渠道开关
	UpdateChannelConfig(ctx context.Context, req *UpdateChannelConfigReq, opts ...http.CallOption) (rsp *OperateResult, err error)
	// UpdateNotificationPrefs 更新用户通知偏好
	UpdateNotificationPrefs(ctx context.Context, req *UpdatePrefsReq, opts ...http.CallOption) (rsp *OperateResult, err error)
}

type MessageServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMessageServiceHTTPClient(client *http.Client) MessageServiceHTTPClient {
	return &MessageServiceHTTPClientImpl{client}
}

// BatchMarkAsRead 批量标记已读
func (c *MessageServiceHTTPClientImpl) BatchMarkAsRead(ctx context.Context, in *BatchMarkAsReadReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/notifications/batch-read"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMessageServiceBatchMarkAsRead))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetChannelConfig 获取租户通知渠道配置
func (c *MessageServiceHTTPClientImpl) GetChannelConfig(ctx context.Context, in *GetChannelConfigReq, opts ...http.CallOption) (*ChannelConfig, error) {
	var out ChannelConfig
	pattern := "/api/v1/tenants/{tenant_id}/notification-channels"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMessageServiceGetChannelConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNotificationPrefs 获取用户通知偏好配置
func (c *MessageServiceHTTPClientImpl) GetNotificationPrefs(ctx context.Context, in *GetPrefsReq, opts ...http.CallOption) (*NotificationPrefs, error) {
	var out NotificationPrefs
	pattern := "/api/v1/notifications/preferences"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMessageServiceGetNotificationPrefs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUnreadCount 获取未读消息数量
func (c *MessageServiceHTTPClientImpl) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...http.CallOption) (*UnreadCountResp, error) {
	var out UnreadCountResp
	pattern := "/api/v1/notifications/unread-count"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMessageServiceGetUnreadCount))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNotifications 获取用户站内信列表
func (c *MessageServiceHTTPClientImpl) ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...http.CallOption) (*ListNotificationsResp, error) {
	var out ListNotificationsResp
	pattern := "/api/v1/notifications"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMessageServiceListNotifications))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MarkAsRead 标记站内信为已读
func (c *MessageServiceHTTPClientImpl) MarkAsRead(ctx context.Context, in *MarkAsReadReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/notifications/read"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMessageServiceMarkAsRead))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateChannelConfig 更新租户通知渠道开关
func (c *MessageServiceHTTPClientImpl) UpdateChannelConfig(ctx context.Context, in *UpdateChannelConfigReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/tenants/{tenant_id}/notification-channels"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMessageServiceUpdateChannelConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateNotificationPrefs 更新用户通知偏好
func (c *MessageServiceHTTPClientImpl) UpdateNotificationPrefs(ctx context.Context, in *UpdatePrefsReq, opts ...http.CallOption) (*OperateResult, error) {
	var out OperateResult
	pattern := "/api/v1/notifications/preferences"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMessageServiceUpdateNotificationPrefs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
