// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: crsystem/v1/quality.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDefectsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReviewId      string                 `protobuf:"bytes,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`                                        // 可选：按评审单筛选（SRS F05-04）
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`                                     // 可选：按项目筛选
	DefectLevel   DefectLevel            `protobuf:"varint,4,opt,name=defect_level,json=defectLevel,proto3,enum=crsystem.v1.DefectLevel" json:"defect_level,omitempty"` // 可选：按缺陷等级筛选
	IsFixed       bool                   `protobuf:"varint,5,opt,name=is_fixed,json=isFixed,proto3" json:"is_fixed,omitempty"`                                          // 可选：按修复状态筛选
	ModuleName    string                 `protobuf:"bytes,6,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`                                  // 可选：按模块筛选
	StatMonth     string                 `protobuf:"bytes,7,opt,name=stat_month,json=statMonth,proto3" json:"stat_month,omitempty"`                                     // 可选：统计月份 yyyy-MM
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,10,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefectsReq) Reset() {
	*x = ListDefectsReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefectsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefectsReq) ProtoMessage() {}

func (x *ListDefectsReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefectsReq.ProtoReflect.Descriptor instead.
func (*ListDefectsReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{0}
}

func (x *ListDefectsReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListDefectsReq) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *ListDefectsReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListDefectsReq) GetDefectLevel() DefectLevel {
	if x != nil {
		return x.DefectLevel
	}
	return DefectLevel_DEFECT_LEVEL_UNSPECIFIED
}

func (x *ListDefectsReq) GetIsFixed() bool {
	if x != nil {
		return x.IsFixed
	}
	return false
}

func (x *ListDefectsReq) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ListDefectsReq) GetStatMonth() string {
	if x != nil {
		return x.StatMonth
	}
	return ""
}

func (x *ListDefectsReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListDefectsReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListDefectsReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListDefectsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DefectInfo          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *PaginationResp        `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefectsResp) Reset() {
	*x = ListDefectsResp{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefectsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefectsResp) ProtoMessage() {}

func (x *ListDefectsResp) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefectsResp.ProtoReflect.Descriptor instead.
func (*ListDefectsResp) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{1}
}

func (x *ListDefectsResp) GetItems() []*DefectInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListDefectsResp) GetPagination() *PaginationResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetDefectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefectReq) Reset() {
	*x = GetDefectReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefectReq) ProtoMessage() {}

func (x *GetDefectReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefectReq.ProtoReflect.Descriptor instead.
func (*GetDefectReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{2}
}

func (x *GetDefectReq) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

type DefectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	ReviewId      string                 `protobuf:"bytes,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	CommentId     string                 `protobuf:"bytes,3,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	ReviewTitle   string                 `protobuf:"bytes,4,opt,name=review_title,json=reviewTitle,proto3" json:"review_title,omitempty"` // 关联评审单标题
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	LineNum       uint32                 `protobuf:"varint,6,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	DefectLevel   DefectLevel            `protobuf:"varint,7,opt,name=defect_level,json=defectLevel,proto3,enum=crsystem.v1.DefectLevel" json:"defect_level,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`                         // 缺陷描述内容
	ModuleName    string                 `protobuf:"bytes,9,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"` // 所属代码模块
	CreatorUid    string                 `protobuf:"bytes,10,opt,name=creator_uid,json=creatorUid,proto3" json:"creator_uid,omitempty"`
	CreatorName   string                 `protobuf:"bytes,11,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	IsFixed       bool                   `protobuf:"varint,12,opt,name=is_fixed,json=isFixed,proto3" json:"is_fixed,omitempty"`
	FixedByUid    string                 `protobuf:"bytes,13,opt,name=fixed_by_uid,json=fixedByUid,proto3" json:"fixed_by_uid,omitempty"`
	FixTime       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=fix_time,json=fixTime,proto3" json:"fix_time,omitempty"`
	StatMonth     string                 `protobuf:"bytes,15,opt,name=stat_month,json=statMonth,proto3" json:"stat_month,omitempty"` // 统计归属月份 yyyy-MM
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefectInfo) Reset() {
	*x = DefectInfo{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefectInfo) ProtoMessage() {}

func (x *DefectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefectInfo.ProtoReflect.Descriptor instead.
func (*DefectInfo) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{3}
}

func (x *DefectInfo) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

func (x *DefectInfo) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *DefectInfo) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *DefectInfo) GetReviewTitle() string {
	if x != nil {
		return x.ReviewTitle
	}
	return ""
}

func (x *DefectInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DefectInfo) GetLineNum() uint32 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

func (x *DefectInfo) GetDefectLevel() DefectLevel {
	if x != nil {
		return x.DefectLevel
	}
	return DefectLevel_DEFECT_LEVEL_UNSPECIFIED
}

func (x *DefectInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DefectInfo) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *DefectInfo) GetCreatorUid() string {
	if x != nil {
		return x.CreatorUid
	}
	return ""
}

func (x *DefectInfo) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *DefectInfo) GetIsFixed() bool {
	if x != nil {
		return x.IsFixed
	}
	return false
}

func (x *DefectInfo) GetFixedByUid() string {
	if x != nil {
		return x.FixedByUid
	}
	return ""
}

func (x *DefectInfo) GetFixTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FixTime
	}
	return nil
}

func (x *DefectInfo) GetStatMonth() string {
	if x != nil {
		return x.StatMonth
	}
	return ""
}

func (x *DefectInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateDefectStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	IsFixed       bool                   `protobuf:"varint,2,opt,name=is_fixed,json=isFixed,proto3" json:"is_fixed,omitempty"`
	OperatorUid   string                 `protobuf:"bytes,3,opt,name=operator_uid,json=operatorUid,proto3" json:"operator_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefectStatusReq) Reset() {
	*x = UpdateDefectStatusReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefectStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefectStatusReq) ProtoMessage() {}

func (x *UpdateDefectStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefectStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateDefectStatusReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDefectStatusReq) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

func (x *UpdateDefectStatusReq) GetIsFixed() bool {
	if x != nil {
		return x.IsFixed
	}
	return false
}

func (x *UpdateDefectStatusReq) GetOperatorUid() string {
	if x != nil {
		return x.OperatorUid
	}
	return ""
}

type GetMetricsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"` // 可选
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`                        // day / week / month
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsReq) Reset() {
	*x = GetMetricsReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsReq) ProtoMessage() {}

func (x *GetMetricsReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsReq.ProtoReflect.Descriptor instead.
func (*GetMetricsReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetricsReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetMetricsReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetMetricsReq) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetMetricsReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetMetricsReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type QualityMetrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ReviewCompletionRate float64                `protobuf:"fixed64,1,opt,name=review_completion_rate,json=reviewCompletionRate,proto3" json:"review_completion_rate,omitempty"` // 评审完成率 (%)
	DefectFixTimelyRate  float64                `protobuf:"fixed64,2,opt,name=defect_fix_timely_rate,json=defectFixTimelyRate,proto3" json:"defect_fix_timely_rate,omitempty"`  // 缺陷修复及时率 (%)
	TotalReviews         uint32                 `protobuf:"varint,3,opt,name=total_reviews,json=totalReviews,proto3" json:"total_reviews,omitempty"`                            // 评审单总数
	CompletedReviews     uint32                 `protobuf:"varint,4,opt,name=completed_reviews,json=completedReviews,proto3" json:"completed_reviews,omitempty"`                // 已完成评审数
	TotalDefects         uint32                 `protobuf:"varint,5,opt,name=total_defects,json=totalDefects,proto3" json:"total_defects,omitempty"`                            // 缺陷总数
	FixedDefects         uint32                 `protobuf:"varint,6,opt,name=fixed_defects,json=fixedDefects,proto3" json:"fixed_defects,omitempty"`                            // 已修复缺陷数
	AvgFixHours          float64                `protobuf:"fixed64,7,opt,name=avg_fix_hours,json=avgFixHours,proto3" json:"avg_fix_hours,omitempty"`                            // 平均修复时长(小时)
	FatalDefects         uint32                 `protobuf:"varint,8,opt,name=fatal_defects,json=fatalDefects,proto3" json:"fatal_defects,omitempty"`                            // 致命缺陷数
	CriticalDefects      uint32                 `protobuf:"varint,9,opt,name=critical_defects,json=criticalDefects,proto3" json:"critical_defects,omitempty"`                   // 严重缺陷数
	MajorDefects         uint32                 `protobuf:"varint,10,opt,name=major_defects,json=majorDefects,proto3" json:"major_defects,omitempty"`                           // 一般缺陷数
	MinorDefects         uint32                 `protobuf:"varint,11,opt,name=minor_defects,json=minorDefects,proto3" json:"minor_defects,omitempty"`                           // 优化建议数
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QualityMetrics) Reset() {
	*x = QualityMetrics{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityMetrics) ProtoMessage() {}

func (x *QualityMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityMetrics.ProtoReflect.Descriptor instead.
func (*QualityMetrics) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{6}
}

func (x *QualityMetrics) GetReviewCompletionRate() float64 {
	if x != nil {
		return x.ReviewCompletionRate
	}
	return 0
}

func (x *QualityMetrics) GetDefectFixTimelyRate() float64 {
	if x != nil {
		return x.DefectFixTimelyRate
	}
	return 0
}

func (x *QualityMetrics) GetTotalReviews() uint32 {
	if x != nil {
		return x.TotalReviews
	}
	return 0
}

func (x *QualityMetrics) GetCompletedReviews() uint32 {
	if x != nil {
		return x.CompletedReviews
	}
	return 0
}

func (x *QualityMetrics) GetTotalDefects() uint32 {
	if x != nil {
		return x.TotalDefects
	}
	return 0
}

func (x *QualityMetrics) GetFixedDefects() uint32 {
	if x != nil {
		return x.FixedDefects
	}
	return 0
}

func (x *QualityMetrics) GetAvgFixHours() float64 {
	if x != nil {
		return x.AvgFixHours
	}
	return 0
}

func (x *QualityMetrics) GetFatalDefects() uint32 {
	if x != nil {
		return x.FatalDefects
	}
	return 0
}

func (x *QualityMetrics) GetCriticalDefects() uint32 {
	if x != nil {
		return x.CriticalDefects
	}
	return 0
}

func (x *QualityMetrics) GetMajorDefects() uint32 {
	if x != nil {
		return x.MajorDefects
	}
	return 0
}

func (x *QualityMetrics) GetMinorDefects() uint32 {
	if x != nil {
		return x.MinorDefects
	}
	return 0
}

type GetUserStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 指定用户，空则返回全部用户
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`               // day / week / month
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsReq) Reset() {
	*x = GetUserStatsReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsReq) ProtoMessage() {}

func (x *GetUserStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsReq.ProtoReflect.Descriptor instead.
func (*GetUserStatsReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserStatsReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetUserStatsReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserStatsReq) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetUserStatsReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetUserStatsReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type UserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserStatItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{8}
}

func (x *UserStats) GetItems() []*UserStatItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UserStatItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName       string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ReviewCount    uint32                 `protobuf:"varint,3,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`             // 参与评审数
	CompletionRate float64                `protobuf:"fixed64,4,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`   // 评审完成率 (%)
	DefectCount    uint32                 `protobuf:"varint,5,opt,name=defect_count,json=defectCount,proto3" json:"defect_count,omitempty"`             // 发现的缺陷数
	FixedCount     uint32                 `protobuf:"varint,6,opt,name=fixed_count,json=fixedCount,proto3" json:"fixed_count,omitempty"`                // 已修复缺陷数
	AvgReviewHours float64                `protobuf:"fixed64,7,opt,name=avg_review_hours,json=avgReviewHours,proto3" json:"avg_review_hours,omitempty"` // 平均评审耗时(小时)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserStatItem) Reset() {
	*x = UserStatItem{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatItem) ProtoMessage() {}

func (x *UserStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatItem.ProtoReflect.Descriptor instead.
func (*UserStatItem) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{9}
}

func (x *UserStatItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStatItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserStatItem) GetReviewCount() uint32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *UserStatItem) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *UserStatItem) GetDefectCount() uint32 {
	if x != nil {
		return x.DefectCount
	}
	return 0
}

func (x *UserStatItem) GetFixedCount() uint32 {
	if x != nil {
		return x.FixedCount
	}
	return 0
}

func (x *UserStatItem) GetAvgReviewHours() float64 {
	if x != nil {
		return x.AvgReviewHours
	}
	return 0
}

type GetModuleStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleStatsReq) Reset() {
	*x = GetModuleStatsReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleStatsReq) ProtoMessage() {}

func (x *GetModuleStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleStatsReq.ProtoReflect.Descriptor instead.
func (*GetModuleStatsReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{10}
}

func (x *GetModuleStatsReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetModuleStatsReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetModuleStatsReq) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetModuleStatsReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetModuleStatsReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ModuleDefectStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ModuleStatItem      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleDefectStats) Reset() {
	*x = ModuleDefectStats{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleDefectStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDefectStats) ProtoMessage() {}

func (x *ModuleDefectStats) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDefectStats.ProtoReflect.Descriptor instead.
func (*ModuleDefectStats) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{11}
}

func (x *ModuleDefectStats) GetItems() []*ModuleStatItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ModuleStatItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleName    string                 `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	DefectCount   uint32                 `protobuf:"varint,2,opt,name=defect_count,json=defectCount,proto3" json:"defect_count,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`                                                  // 缺陷占比 (%)
	MaxSeverity   DefectLevel            `protobuf:"varint,4,opt,name=max_severity,json=maxSeverity,proto3,enum=crsystem.v1.DefectLevel" json:"max_severity,omitempty"` // 最高缺陷等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleStatItem) Reset() {
	*x = ModuleStatItem{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStatItem) ProtoMessage() {}

func (x *ModuleStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStatItem.ProtoReflect.Descriptor instead.
func (*ModuleStatItem) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{12}
}

func (x *ModuleStatItem) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ModuleStatItem) GetDefectCount() uint32 {
	if x != nil {
		return x.DefectCount
	}
	return 0
}

func (x *ModuleStatItem) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ModuleStatItem) GetMaxSeverity() DefectLevel {
	if x != nil {
		return x.MaxSeverity
	}
	return DefectLevel_DEFECT_LEVEL_UNSPECIFIED
}

type GetTechDebtReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTechDebtReq) Reset() {
	*x = GetTechDebtReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTechDebtReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechDebtReq) ProtoMessage() {}

func (x *GetTechDebtReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechDebtReq.ProtoReflect.Descriptor instead.
func (*GetTechDebtReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{13}
}

func (x *GetTechDebtReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTechDebtReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type TechDebtStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalUnfixed    uint32                 `protobuf:"varint,1,opt,name=total_unfixed,json=totalUnfixed,proto3" json:"total_unfixed,omitempty"` // 未修复缺陷总数
	FatalUnfixed    uint32                 `protobuf:"varint,2,opt,name=fatal_unfixed,json=fatalUnfixed,proto3" json:"fatal_unfixed,omitempty"`
	CriticalUnfixed uint32                 `protobuf:"varint,3,opt,name=critical_unfixed,json=criticalUnfixed,proto3" json:"critical_unfixed,omitempty"`
	DebtScore       float64                `protobuf:"fixed64,4,opt,name=debt_score,json=debtScore,proto3" json:"debt_score,omitempty"`  // 技术债务分值
	TopModules      []*ModuleStatItem      `protobuf:"bytes,5,rep,name=top_modules,json=topModules,proto3" json:"top_modules,omitempty"` // 债务最重的模块TOP5
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TechDebtStats) Reset() {
	*x = TechDebtStats{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TechDebtStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechDebtStats) ProtoMessage() {}

func (x *TechDebtStats) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechDebtStats.ProtoReflect.Descriptor instead.
func (*TechDebtStats) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{14}
}

func (x *TechDebtStats) GetTotalUnfixed() uint32 {
	if x != nil {
		return x.TotalUnfixed
	}
	return 0
}

func (x *TechDebtStats) GetFatalUnfixed() uint32 {
	if x != nil {
		return x.FatalUnfixed
	}
	return 0
}

func (x *TechDebtStats) GetCriticalUnfixed() uint32 {
	if x != nil {
		return x.CriticalUnfixed
	}
	return 0
}

func (x *TechDebtStats) GetDebtScore() float64 {
	if x != nil {
		return x.DebtScore
	}
	return 0
}

func (x *TechDebtStats) GetTopModules() []*ModuleStatItem {
	if x != nil {
		return x.TopModules
	}
	return nil
}

type GetDashboardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // day / week / month
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardReq) Reset() {
	*x = GetDashboardReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardReq) ProtoMessage() {}

func (x *GetDashboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardReq.ProtoReflect.Descriptor instead.
func (*GetDashboardReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{15}
}

func (x *GetDashboardReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetDashboardReq) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetDashboardReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetDashboardReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type DashboardData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Metrics            *QualityMetrics        `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	ReviewTrend        []*TrendPoint          `protobuf:"bytes,2,rep,name=review_trend,json=reviewTrend,proto3" json:"review_trend,omitempty"`                      // 评审单趋势
	DefectTrend        []*TrendPoint          `protobuf:"bytes,3,rep,name=defect_trend,json=defectTrend,proto3" json:"defect_trend,omitempty"`                      // 缺陷趋势
	ModuleDistribution []*ModuleStatItem      `protobuf:"bytes,4,rep,name=module_distribution,json=moduleDistribution,proto3" json:"module_distribution,omitempty"` // 模块缺陷分布
	TopReviewers       []*UserStatItem        `protobuf:"bytes,5,rep,name=top_reviewers,json=topReviewers,proto3" json:"top_reviewers,omitempty"`                   // 评审效率TOP5
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DashboardData) Reset() {
	*x = DashboardData{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardData) ProtoMessage() {}

func (x *DashboardData) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardData.ProtoReflect.Descriptor instead.
func (*DashboardData) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{16}
}

func (x *DashboardData) GetMetrics() *QualityMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *DashboardData) GetReviewTrend() []*TrendPoint {
	if x != nil {
		return x.ReviewTrend
	}
	return nil
}

func (x *DashboardData) GetDefectTrend() []*TrendPoint {
	if x != nil {
		return x.DefectTrend
	}
	return nil
}

func (x *DashboardData) GetModuleDistribution() []*ModuleStatItem {
	if x != nil {
		return x.ModuleDistribution
	}
	return nil
}

func (x *DashboardData) GetTopReviewers() []*UserStatItem {
	if x != nil {
		return x.TopReviewers
	}
	return nil
}

type TrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`    // 日期标签
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{17}
}

func (x *TrendPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TrendPoint) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GenerateReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportType    string                 `protobuf:"bytes,2,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"` // daily / weekly / monthly
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`                           // excel / pdf
	StatMonth     string                 `protobuf:"bytes,4,opt,name=stat_month,json=statMonth,proto3" json:"stat_month,omitempty"`    // 统计月份 yyyy-MM（月报必填）
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportReq) Reset() {
	*x = GenerateReportReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportReq) ProtoMessage() {}

func (x *GenerateReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportReq.ProtoReflect.Descriptor instead.
func (*GenerateReportReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateReportReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenerateReportReq) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *GenerateReportReq) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GenerateReportReq) GetStatMonth() string {
	if x != nil {
		return x.StatMonth
	}
	return ""
}

func (x *GenerateReportReq) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GenerateReportReq) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ReportInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportType    string                 `protobuf:"bytes,3,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	FileUrl       string                 `protobuf:"bytes,6,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"` // MinIO文件访问地址
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                  // generating / ready / failed
	CreatorUid    string                 `protobuf:"bytes,8,opt,name=creator_uid,json=creatorUid,proto3" json:"creator_uid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInfo) Reset() {
	*x = ReportInfo{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInfo) ProtoMessage() {}

func (x *ReportInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInfo.ProtoReflect.Descriptor instead.
func (*ReportInfo) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{19}
}

func (x *ReportInfo) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReportInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReportInfo) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *ReportInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ReportInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReportInfo) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *ReportInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportInfo) GetCreatorUid() string {
	if x != nil {
		return x.CreatorUid
	}
	return ""
}

func (x *ReportInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListReportsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ReportType    string                 `protobuf:"bytes,2,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"` // 可选筛选
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsReq) Reset() {
	*x = ListReportsReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsReq) ProtoMessage() {}

func (x *ListReportsReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsReq.ProtoReflect.Descriptor instead.
func (*ListReportsReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{20}
}

func (x *ListReportsReq) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListReportsReq) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *ListReportsReq) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListReportsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ReportInfo          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Pagination    *PaginationResp        `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResp) Reset() {
	*x = ListReportsResp{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResp) ProtoMessage() {}

func (x *ListReportsResp) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResp.ProtoReflect.Descriptor instead.
func (*ListReportsResp) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{21}
}

func (x *ListReportsResp) GetItems() []*ReportInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListReportsResp) GetPagination() *PaginationResp {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetReportDownloadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportDownloadReq) Reset() {
	*x = GetReportDownloadReq{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportDownloadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportDownloadReq) ProtoMessage() {}

func (x *GetReportDownloadReq) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportDownloadReq.ProtoReflect.Descriptor instead.
func (*GetReportDownloadReq) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{22}
}

func (x *GetReportDownloadReq) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type ReportDownloadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"` // MinIO预签名下载URL
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`          // URL过期时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDownloadResp) Reset() {
	*x = ReportDownloadResp{}
	mi := &file_crsystem_v1_quality_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDownloadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDownloadResp) ProtoMessage() {}

func (x *ReportDownloadResp) ProtoReflect() protoreflect.Message {
	mi := &file_crsystem_v1_quality_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDownloadResp.ProtoReflect.Descriptor instead.
func (*ReportDownloadResp) Descriptor() ([]byte, []int) {
	return file_crsystem_v1_quality_proto_rawDescGZIP(), []int{23}
}

func (x *ReportDownloadResp) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ReportDownloadResp) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

var File_crsystem_v1_quality_proto protoreflect.FileDescriptor

const file_crsystem_v1_quality_proto_rawDesc = "" +
	"\n" +
	"\x19crsystem/v1/quality.proto\x12\vcrsystem.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18crsystem/v1/common.proto\"\xac\x03\n" +
	"\x0eListDefectsReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\tR\breviewId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12;\n" +
	"\fdefect_level\x18\x04 \x01(\x0e2\x18.crsystem.v1.DefectLevelR\vdefectLevel\x12\x19\n" +
	"\bis_fixed\x18\x05 \x01(\bR\aisFixed\x12\x1f\n" +
	"\vmodule_name\x18\x06 \x01(\tR\n" +
	"moduleName\x12\x1d\n" +
	"\n" +
	"stat_month\x18\a \x01(\tR\tstatMonth\x129\n" +
	"\n" +
	"start_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x127\n" +
	"\n" +
	"pagination\x18\n" +
	" \x01(\v2\x17.crsystem.v1.PaginationR\n" +
	"pagination\"}\n" +
	"\x0fListDefectsResp\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.crsystem.v1.DefectInfoR\x05items\x12;\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1b.crsystem.v1.PaginationRespR\n" +
	"pagination\"+\n" +
	"\fGetDefectReq\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\"\xca\x04\n" +
	"\n" +
	"DefectInfo\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\tR\breviewId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x03 \x01(\tR\tcommentId\x12!\n" +
	"\freview_title\x18\x04 \x01(\tR\vreviewTitle\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x19\n" +
	"\bline_num\x18\x06 \x01(\rR\alineNum\x12;\n" +
	"\fdefect_level\x18\a \x01(\x0e2\x18.crsystem.v1.DefectLevelR\vdefectLevel\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1f\n" +
	"\vmodule_name\x18\t \x01(\tR\n" +
	"moduleName\x12\x1f\n" +
	"\vcreator_uid\x18\n" +
	" \x01(\tR\n" +
	"creatorUid\x12!\n" +
	"\fcreator_name\x18\v \x01(\tR\vcreatorName\x12\x19\n" +
	"\bis_fixed\x18\f \x01(\bR\aisFixed\x12 \n" +
	"\ffixed_by_uid\x18\r \x01(\tR\n" +
	"fixedByUid\x125\n" +
	"\bfix_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\afixTime\x12\x1d\n" +
	"\n" +
	"stat_month\x18\x0f \x01(\tR\tstatMonth\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"r\n" +
	"\x15UpdateDefectStatusReq\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\x12\x19\n" +
	"\bis_fixed\x18\x02 \x01(\bR\aisFixed\x12!\n" +
	"\foperator_uid\x18\x03 \x01(\tR\voperatorUid\"\xd5\x01\n" +
	"\rGetMetricsReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xd5\x03\n" +
	"\x0eQualityMetrics\x124\n" +
	"\x16review_completion_rate\x18\x01 \x01(\x01R\x14reviewCompletionRate\x123\n" +
	"\x16defect_fix_timely_rate\x18\x02 \x01(\x01R\x13defectFixTimelyRate\x12#\n" +
	"\rtotal_reviews\x18\x03 \x01(\rR\ftotalReviews\x12+\n" +
	"\x11completed_reviews\x18\x04 \x01(\rR\x10completedReviews\x12#\n" +
	"\rtotal_defects\x18\x05 \x01(\rR\ftotalDefects\x12#\n" +
	"\rfixed_defects\x18\x06 \x01(\rR\ffixedDefects\x12\"\n" +
	"\ravg_fix_hours\x18\a \x01(\x01R\vavgFixHours\x12#\n" +
	"\rfatal_defects\x18\b \x01(\rR\ffatalDefects\x12)\n" +
	"\x10critical_defects\x18\t \x01(\rR\x0fcriticalDefects\x12#\n" +
	"\rmajor_defects\x18\n" +
	" \x01(\rR\fmajorDefects\x12#\n" +
	"\rminor_defects\x18\v \x01(\rR\fminorDefects\"\xd1\x01\n" +
	"\x0fGetUserStatsReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"<\n" +
	"\tUserStats\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.crsystem.v1.UserStatItemR\x05items\"\xfe\x01\n" +
	"\fUserStatItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12!\n" +
	"\freview_count\x18\x03 \x01(\rR\vreviewCount\x12'\n" +
	"\x0fcompletion_rate\x18\x04 \x01(\x01R\x0ecompletionRate\x12!\n" +
	"\fdefect_count\x18\x05 \x01(\rR\vdefectCount\x12\x1f\n" +
	"\vfixed_count\x18\x06 \x01(\rR\n" +
	"fixedCount\x12(\n" +
	"\x10avg_review_hours\x18\a \x01(\x01R\x0eavgReviewHours\"\xd9\x01\n" +
	"\x11GetModuleStatsReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"F\n" +
	"\x11ModuleDefectStats\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.crsystem.v1.ModuleStatItemR\x05items\"\xb1\x01\n" +
	"\x0eModuleStatItem\x12\x1f\n" +
	"\vmodule_name\x18\x01 \x01(\tR\n" +
	"moduleName\x12!\n" +
	"\fdefect_count\x18\x02 \x01(\rR\vdefectCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\x12;\n" +
	"\fmax_severity\x18\x04 \x01(\x0e2\x18.crsystem.v1.DefectLevelR\vmaxSeverity\"L\n" +
	"\x0eGetTechDebtReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\xe1\x01\n" +
	"\rTechDebtStats\x12#\n" +
	"\rtotal_unfixed\x18\x01 \x01(\rR\ftotalUnfixed\x12#\n" +
	"\rfatal_unfixed\x18\x02 \x01(\rR\ffatalUnfixed\x12)\n" +
	"\x10critical_unfixed\x18\x03 \x01(\rR\x0fcriticalUnfixed\x12\x1d\n" +
	"\n" +
	"debt_score\x18\x04 \x01(\x01R\tdebtScore\x12<\n" +
	"\vtop_modules\x18\x05 \x03(\v2\x1b.crsystem.v1.ModuleStatItemR\n" +
	"topModules\"\xb8\x01\n" +
	"\x0fGetDashboardReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xcc\x02\n" +
	"\rDashboardData\x125\n" +
	"\ametrics\x18\x01 \x01(\v2\x1b.crsystem.v1.QualityMetricsR\ametrics\x12:\n" +
	"\freview_trend\x18\x02 \x03(\v2\x17.crsystem.v1.TrendPointR\vreviewTrend\x12:\n" +
	"\fdefect_trend\x18\x03 \x03(\v2\x17.crsystem.v1.TrendPointR\vdefectTrend\x12L\n" +
	"\x13module_distribution\x18\x04 \x03(\v2\x1b.crsystem.v1.ModuleStatItemR\x12moduleDistribution\x12>\n" +
	"\rtop_reviewers\x18\x05 \x03(\v2\x19.crsystem.v1.UserStatItemR\ftopReviewers\"6\n" +
	"\n" +
	"TrendPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\xfa\x01\n" +
	"\x11GenerateReportReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vreport_type\x18\x02 \x01(\tR\n" +
	"reportType\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"stat_month\x18\x04 \x01(\tR\tstatMonth\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xa4\x02\n" +
	"\n" +
	"ReportInfo\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vreport_type\x18\x03 \x01(\tR\n" +
	"reportType\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x19\n" +
	"\bfile_url\x18\x06 \x01(\tR\afileUrl\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vcreator_uid\x18\b \x01(\tR\n" +
	"creatorUid\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x87\x01\n" +
	"\x0eListReportsReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vreport_type\x18\x02 \x01(\tR\n" +
	"reportType\x127\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x17.crsystem.v1.PaginationR\n" +
	"pagination\"}\n" +
	"\x0fListReportsResp\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.crsystem.v1.ReportInfoR\x05items\x12;\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1b.crsystem.v1.PaginationRespR\n" +
	"pagination\"3\n" +
	"\x14GetReportDownloadReq\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"p\n" +
	"\x12ReportDownloadResp\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x127\n" +
	"\texpire_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt2\x81\n" +
	"\n" +
	"\x12QualityStatService\x12a\n" +
	"\vListDefects\x12\x1b.crsystem.v1.ListDefectsReq\x1a\x1c.crsystem.v1.ListDefectsResp\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/defects\x12d\n" +
	"\tGetDefect\x12\x19.crsystem.v1.GetDefectReq\x1a\x17.crsystem.v1.DefectInfo\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/defects/{defect_id}\x12\x83\x01\n" +
	"\x12UpdateDefectStatus\x12\".crsystem.v1.UpdateDefectStatusReq\x1a\x1a.crsystem.v1.OperateResult\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/api/v1/defects/{defect_id}/status\x12m\n" +
	"\x11GetQualityMetrics\x12\x1a.crsystem.v1.GetMetricsReq\x1a\x1b.crsystem.v1.QualityMetrics\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/quality/metrics\x12h\n" +
	"\fGetUserStats\x12\x1c.crsystem.v1.GetUserStatsReq\x1a\x16.crsystem.v1.UserStats\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/quality/user-stats\x12|\n" +
	"\x14GetModuleDefectStats\x12\x1e.crsystem.v1.GetModuleStatsReq\x1a\x1e.crsystem.v1.ModuleDefectStats\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/quality/module-stats\x12n\n" +
	"\x10GetTechDebtStats\x12\x1b.crsystem.v1.GetTechDebtReq\x1a\x1a.crsystem.v1.TechDebtStats\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/quality/tech-debt\x12k\n" +
	"\fGetDashboard\x12\x1c.crsystem.v1.GetDashboardReq\x1a\x1a.crsystem.v1.DashboardData\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/quality/dashboard\x12m\n" +
	"\x0eGenerateReport\x12\x1e.crsystem.v1.GenerateReportReq\x1a\x17.crsystem.v1.ReportInfo\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/quality/reports\x12i\n" +
	"\vListReports\x12\x1b.crsystem.v1.ListReportsReq\x1a\x1c.crsystem.v1.ListReportsResp\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/quality/reports\x12\x8d\x01\n" +
	"\x11GetReportDownload\x12!.crsystem.v1.GetReportDownloadReq\x1a\x1f.crsystem.v1.ReportDownloadResp\"4\x82\xd3\xe4\x93\x02.\x12,/api/v1/quality/reports/{report_id}/downloadB\x1eZ\x1ccr-system/api/crsystem/v1;v1b\x06proto3"

var (
	file_crsystem_v1_quality_proto_rawDescOnce sync.Once
	file_crsystem_v1_quality_proto_rawDescData []byte
)

func file_crsystem_v1_quality_proto_rawDescGZIP() []byte {
	file_crsystem_v1_quality_proto_rawDescOnce.Do(func() {
		file_crsystem_v1_quality_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crsystem_v1_quality_proto_rawDesc), len(file_crsystem_v1_quality_proto_rawDesc)))
	})
	return file_crsystem_v1_quality_proto_rawDescData
}

var file_crsystem_v1_quality_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_crsystem_v1_quality_proto_goTypes = []any{
	(*ListDefectsReq)(nil),        // 0: crsystem.v1.ListDefectsReq
	(*ListDefectsResp)(nil),       // 1: crsystem.v1.ListDefectsResp
	(*GetDefectReq)(nil),          // 2: crsystem.v1.GetDefectReq
	(*DefectInfo)(nil),            // 3: crsystem.v1.DefectInfo
	(*UpdateDefectStatusReq)(nil), // 4: crsystem.v1.UpdateDefectStatusReq
	(*GetMetricsReq)(nil),         // 5: crsystem.v1.GetMetricsReq
	(*QualityMetrics)(nil),        // 6: crsystem.v1.QualityMetrics
	(*GetUserStatsReq)(nil),       // 7: crsystem.v1.GetUserStatsReq
	(*UserStats)(nil),             // 8: crsystem.v1.UserStats
	(*UserStatItem)(nil),          // 9: crsystem.v1.UserStatItem
	(*GetModuleStatsReq)(nil),     // 10: crsystem.v1.GetModuleStatsReq
	(*ModuleDefectStats)(nil),     // 11: crsystem.v1.ModuleDefectStats
	(*ModuleStatItem)(nil),        // 12: crsystem.v1.ModuleStatItem
	(*GetTechDebtReq)(nil),        // 13: crsystem.v1.GetTechDebtReq
	(*TechDebtStats)(nil),         // 14: crsystem.v1.TechDebtStats
	(*GetDashboardReq)(nil),       // 15: crsystem.v1.GetDashboardReq
	(*DashboardData)(nil),         // 16: crsystem.v1.DashboardData
	(*TrendPoint)(nil),            // 17: crsystem.v1.TrendPoint
	(*GenerateReportReq)(nil),     // 18: crsystem.v1.GenerateReportReq
	(*ReportInfo)(nil),            // 19: crsystem.v1.ReportInfo
	(*ListReportsReq)(nil),        // 20: crsystem.v1.ListReportsReq
	(*ListReportsResp)(nil),       // 21: crsystem.v1.ListReportsResp
	(*GetReportDownloadReq)(nil),  // 22: crsystem.v1.GetReportDownloadReq
	(*ReportDownloadResp)(nil),    // 23: crsystem.v1.ReportDownloadResp
	(DefectLevel)(0),              // 24: crsystem.v1.DefectLevel
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
	(*Pagination)(nil),            // 26: crsystem.v1.Pagination
	(*PaginationResp)(nil),        // 27: crsystem.v1.PaginationResp
	(*OperateResult)(nil),         // 28: crsystem.v1.OperateResult
}
var file_crsystem_v1_quality_proto_depIdxs = []int32{
	24, // 0: crsystem.v1.ListDefectsReq.defect_level:type_name -> crsystem.v1.DefectLevel
	25, // 1: crsystem.v1.ListDefectsReq.start_time:type_name -> google.protobuf.Timestamp
	25, // 2: crsystem.v1.ListDefectsReq.end_time:type_name -> google.protobuf.Timestamp
	26, // 3: crsystem.v1.ListDefectsReq.pagination:type_name -> crsystem.v1.Pagination
	3,  // 4: crsystem.v1.ListDefectsResp.items:type_name -> crsystem.v1.DefectInfo
	27, // 5: crsystem.v1.ListDefectsResp.pagination:type_name -> crsystem.v1.PaginationResp
	24, // 6: crsystem.v1.DefectInfo.defect_level:type_name -> crsystem.v1.DefectLevel
	25, // 7: crsystem.v1.DefectInfo.fix_time:type_name -> google.protobuf.Timestamp
	25, // 8: crsystem.v1.DefectInfo.created_at:type_name -> google.protobuf.Timestamp
	25, // 9: crsystem.v1.GetMetricsReq.start_time:type_name -> google.protobuf.Timestamp
	25, // 10: crsystem.v1.GetMetricsReq.end_time:type_name -> google.protobuf.Timestamp
	25, // 11: crsystem.v1.GetUserStatsReq.start_time:type_name -> google.protobuf.Timestamp
	25, // 12: crsystem.v1.GetUserStatsReq.end_time:type_name -> google.protobuf.Timestamp
	9,  // 13: crsystem.v1.UserStats.items:type_name -> crsystem.v1.UserStatItem
	25, // 14: crsystem.v1.GetModuleStatsReq.start_time:type_name -> google.protobuf.Timestamp
	25, // 15: crsystem.v1.GetModuleStatsReq.end_time:type_name -> google.protobuf.Timestamp
	12, // 16: crsystem.v1.ModuleDefectStats.items:type_name -> crsystem.v1.ModuleStatItem
	24, // 17: crsystem.v1.ModuleStatItem.max_severity:type_name -> crsystem.v1.DefectLevel
	12, // 18: crsystem.v1.TechDebtStats.top_modules:type_name -> crsystem.v1.ModuleStatItem
	25, // 19: crsystem.v1.GetDashboardReq.start_time:type_name -> google.protobuf.Timestamp
	25, // 20: crsystem.v1.GetDashboardReq.end_time:type_name -> google.protobuf.Timestamp
	6,  // 21: crsystem.v1.DashboardData.metrics:type_name -> crsystem.v1.QualityMetrics
	17, // 22: crsystem.v1.DashboardData.review_trend:type_name -> crsystem.v1.TrendPoint
	17, // 23: crsystem.v1.DashboardData.defect_trend:type_name -> crsystem.v1.TrendPoint
	12, // 24: crsystem.v1.DashboardData.module_distribution:type_name -> crsystem.v1.ModuleStatItem
	9,  // 25: crsystem.v1.DashboardData.top_reviewers:type_name -> crsystem.v1.UserStatItem
	25, // 26: crsystem.v1.GenerateReportReq.start_time:type_name -> google.protobuf.Timestamp
	25, // 27: crsystem.v1.GenerateReportReq.end_time:type_name -> google.protobuf.Timestamp
	25, // 28: crsystem.v1.ReportInfo.created_at:type_name -> google.protobuf.Timestamp
	26, // 29: crsystem.v1.ListReportsReq.pagination:type_name -> crsystem.v1.Pagination
	19, // 30: crsystem.v1.ListReportsResp.items:type_name -> crsystem.v1.ReportInfo
	27, // 31: crsystem.v1.ListReportsResp.pagination:type_name -> crsystem.v1.PaginationResp
	25, // 32: crsystem.v1.ReportDownloadResp.expire_at:type_name -> google.protobuf.Timestamp
	0,  // 33: crsystem.v1.QualityStatService.ListDefects:input_type -> crsystem.v1.ListDefectsReq
	2,  // 34: crsystem.v1.QualityStatService.GetDefect:input_type -> crsystem.v1.GetDefectReq
	4,  // 35: crsystem.v1.QualityStatService.UpdateDefectStatus:input_type -> crsystem.v1.UpdateDefectStatusReq
	5,  // 36: crsystem.v1.QualityStatService.GetQualityMetrics:input_type -> crsystem.v1.GetMetricsReq
	7,  // 37: crsystem.v1.QualityStatService.GetUserStats:input_type -> crsystem.v1.GetUserStatsReq
	10, // 38: crsystem.v1.QualityStatService.GetModuleDefectStats:input_type -> crsystem.v1.GetModuleStatsReq
	13, // 39: crsystem.v1.QualityStatService.GetTechDebtStats:input_type -> crsystem.v1.GetTechDebtReq
	15, // 40: crsystem.v1.QualityStatService.GetDashboard:input_type -> crsystem.v1.GetDashboardReq
	18, // 41: crsystem.v1.QualityStatService.GenerateReport:input_type -> crsystem.v1.GenerateReportReq
	20, // 42: crsystem.v1.QualityStatService.ListReports:input_type -> crsystem.v1.ListReportsReq
	22, // 43: crsystem.v1.QualityStatService.GetReportDownload:input_type -> crsystem.v1.GetReportDownloadReq
	1,  // 44: crsystem.v1.QualityStatService.ListDefects:output_type -> crsystem.v1.ListDefectsResp
	3,  // 45: crsystem.v1.QualityStatService.GetDefect:output_type -> crsystem.v1.DefectInfo
	28, // 46: crsystem.v1.QualityStatService.UpdateDefectStatus:output_type -> crsystem.v1.OperateResult
	6,  // 47: crsystem.v1.QualityStatService.GetQualityMetrics:output_type -> crsystem.v1.QualityMetrics
	8,  // 48: crsystem.v1.QualityStatService.GetUserStats:output_type -> crsystem.v1.UserStats
	11, // 49: crsystem.v1.QualityStatService.GetModuleDefectStats:output_type -> crsystem.v1.ModuleDefectStats
	14, // 50: crsystem.v1.QualityStatService.GetTechDebtStats:output_type -> crsystem.v1.TechDebtStats
	16, // 51: crsystem.v1.QualityStatService.GetDashboard:output_type -> crsystem.v1.DashboardData
	19, // 52: crsystem.v1.QualityStatService.GenerateReport:output_type -> crsystem.v1.ReportInfo
	21, // 53: crsystem.v1.QualityStatService.ListReports:output_type -> crsystem.v1.ListReportsResp
	23, // 54: crsystem.v1.QualityStatService.GetReportDownload:output_type -> crsystem.v1.ReportDownloadResp
	44, // [44:55] is the sub-list for method output_type
	33, // [33:44] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_crsystem_v1_quality_proto_init() }
func file_crsystem_v1_quality_proto_init() {
	if File_crsystem_v1_quality_proto != nil {
		return
	}
	file_crsystem_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crsystem_v1_quality_proto_rawDesc), len(file_crsystem_v1_quality_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crsystem_v1_quality_proto_goTypes,
		DependencyIndexes: file_crsystem_v1_quality_proto_depIdxs,
		MessageInfos:      file_crsystem_v1_quality_proto_msgTypes,
	}.Build()
	File_crsystem_v1_quality_proto = out.File
	file_crsystem_v1_quality_proto_goTypes = nil
	file_crsystem_v1_quality_proto_depIdxs = nil
}
