// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: crsystem/v1/quality.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QualityStatService_ListDefects_FullMethodName          = "/crsystem.v1.QualityStatService/ListDefects"
	QualityStatService_GetDefect_FullMethodName            = "/crsystem.v1.QualityStatService/GetDefect"
	QualityStatService_UpdateDefectStatus_FullMethodName   = "/crsystem.v1.QualityStatService/UpdateDefectStatus"
	QualityStatService_GetQualityMetrics_FullMethodName    = "/crsystem.v1.QualityStatService/GetQualityMetrics"
	QualityStatService_GetUserStats_FullMethodName         = "/crsystem.v1.QualityStatService/GetUserStats"
	QualityStatService_GetModuleDefectStats_FullMethodName = "/crsystem.v1.QualityStatService/GetModuleDefectStats"
	QualityStatService_GetTechDebtStats_FullMethodName     = "/crsystem.v1.QualityStatService/GetTechDebtStats"
	QualityStatService_GetDashboard_FullMethodName         = "/crsystem.v1.QualityStatService/GetDashboard"
	QualityStatService_GenerateReport_FullMethodName       = "/crsystem.v1.QualityStatService/GenerateReport"
	QualityStatService_ListReports_FullMethodName          = "/crsystem.v1.QualityStatService/ListReports"
	QualityStatService_GetReportDownload_FullMethodName    = "/crsystem.v1.QualityStatService/GetReportDownload"
)

// QualityStatServiceClient is the client API for QualityStatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================
// quality-stat 质量统计服务（HLD §2.3 / LLD §3.5）
// 核心职责：消费MQ事件归集缺陷数据、多维度质量指标计算、
//
//	报表生成与PDF/Excel渲染、报表文件存入MinIO
//
// ============================================================
type QualityStatServiceClient interface {
	// 获取缺陷列表（SRS F05-01 缺陷台账）
	ListDefects(ctx context.Context, in *ListDefectsReq, opts ...grpc.CallOption) (*ListDefectsResp, error)
	// 获取缺陷详情
	GetDefect(ctx context.Context, in *GetDefectReq, opts ...grpc.CallOption) (*DefectInfo, error)
	// 更新缺陷修复状态
	UpdateDefectStatus(ctx context.Context, in *UpdateDefectStatusReq, opts ...grpc.CallOption) (*OperateResult, error)
	// 获取综合质量统计指标
	GetQualityMetrics(ctx context.Context, in *GetMetricsReq, opts ...grpc.CallOption) (*QualityMetrics, error)
	// 获取个人评审统计数据
	GetUserStats(ctx context.Context, in *GetUserStatsReq, opts ...grpc.CallOption) (*UserStats, error)
	// 获取模块缺陷分布统计
	GetModuleDefectStats(ctx context.Context, in *GetModuleStatsReq, opts ...grpc.CallOption) (*ModuleDefectStats, error)
	// 获取技术债务统计
	GetTechDebtStats(ctx context.Context, in *GetTechDebtReq, opts ...grpc.CallOption) (*TechDebtStats, error)
	// 获取大盘概览数据（按日/周/月筛选）
	GetDashboard(ctx context.Context, in *GetDashboardReq, opts ...grpc.CallOption) (*DashboardData, error)
	// 生成质量报表（Excel/PDF）
	GenerateReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*ReportInfo, error)
	// 获取报表列表
	ListReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ListReportsResp, error)
	// 获取报表下载链接（MinIO文件地址）
	GetReportDownload(ctx context.Context, in *GetReportDownloadReq, opts ...grpc.CallOption) (*ReportDownloadResp, error)
}

type qualityStatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQualityStatServiceClient(cc grpc.ClientConnInterface) QualityStatServiceClient {
	return &qualityStatServiceClient{cc}
}

func (c *qualityStatServiceClient) ListDefects(ctx context.Context, in *ListDefectsReq, opts ...grpc.CallOption) (*ListDefectsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDefectsResp)
	err := c.cc.Invoke(ctx, QualityStatService_ListDefects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) GetDefect(ctx context.Context, in *GetDefectReq, opts ...grpc.CallOption) (*DefectInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefectInfo)
	err := c.cc.Invoke(ctx, QualityStatService_GetDefect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) UpdateDefectStatus(ctx context.Context, in *UpdateDefectStatusReq, opts ...grpc.CallOption) (*OperateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateResult)
	err := c.cc.Invoke(ctx, QualityStatService_UpdateDefectStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) GetQualityMetrics(ctx context.Context, in *GetMetricsReq, opts ...grpc.CallOption) (*QualityMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QualityMetrics)
	err := c.cc.Invoke(ctx, QualityStatService_GetQualityMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) GetUserStats(ctx context.Context, in *GetUserStatsReq, opts ...grpc.CallOption) (*UserStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserStats)
	err := c.cc.Invoke(ctx, QualityStatService_GetUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) GetModuleDefectStats(ctx context.Context, in *GetModuleStatsReq, opts ...grpc.CallOption) (*ModuleDefectStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModuleDefectStats)
	err := c.cc.Invoke(ctx, QualityStatService_GetModuleDefectStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) GetTechDebtStats(ctx context.Context, in *GetTechDebtReq, opts ...grpc.CallOption) (*TechDebtStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TechDebtStats)
	err := c.cc.Invoke(ctx, QualityStatService_GetTechDebtStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) GetDashboard(ctx context.Context, in *GetDashboardReq, opts ...grpc.CallOption) (*DashboardData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardData)
	err := c.cc.Invoke(ctx, QualityStatService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) GenerateReport(ctx context.Context, in *GenerateReportReq, opts ...grpc.CallOption) (*ReportInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportInfo)
	err := c.cc.Invoke(ctx, QualityStatService_GenerateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) ListReports(ctx context.Context, in *ListReportsReq, opts ...grpc.CallOption) (*ListReportsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReportsResp)
	err := c.cc.Invoke(ctx, QualityStatService_ListReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualityStatServiceClient) GetReportDownload(ctx context.Context, in *GetReportDownloadReq, opts ...grpc.CallOption) (*ReportDownloadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportDownloadResp)
	err := c.cc.Invoke(ctx, QualityStatService_GetReportDownload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QualityStatServiceServer is the server API for QualityStatService service.
// All implementations must embed UnimplementedQualityStatServiceServer
// for forward compatibility.
//
// ============================================================
// quality-stat 质量统计服务（HLD §2.3 / LLD §3.5）
// 核心职责：消费MQ事件归集缺陷数据、多维度质量指标计算、
//
//	报表生成与PDF/Excel渲染、报表文件存入MinIO
//
// ============================================================
type QualityStatServiceServer interface {
	// 获取缺陷列表（SRS F05-01 缺陷台账）
	ListDefects(context.Context, *ListDefectsReq) (*ListDefectsResp, error)
	// 获取缺陷详情
	GetDefect(context.Context, *GetDefectReq) (*DefectInfo, error)
	// 更新缺陷修复状态
	UpdateDefectStatus(context.Context, *UpdateDefectStatusReq) (*OperateResult, error)
	// 获取综合质量统计指标
	GetQualityMetrics(context.Context, *GetMetricsReq) (*QualityMetrics, error)
	// 获取个人评审统计数据
	GetUserStats(context.Context, *GetUserStatsReq) (*UserStats, error)
	// 获取模块缺陷分布统计
	GetModuleDefectStats(context.Context, *GetModuleStatsReq) (*ModuleDefectStats, error)
	// 获取技术债务统计
	GetTechDebtStats(context.Context, *GetTechDebtReq) (*TechDebtStats, error)
	// 获取大盘概览数据（按日/周/月筛选）
	GetDashboard(context.Context, *GetDashboardReq) (*DashboardData, error)
	// 生成质量报表（Excel/PDF）
	GenerateReport(context.Context, *GenerateReportReq) (*ReportInfo, error)
	// 获取报表列表
	ListReports(context.Context, *ListReportsReq) (*ListReportsResp, error)
	// 获取报表下载链接（MinIO文件地址）
	GetReportDownload(context.Context, *GetReportDownloadReq) (*ReportDownloadResp, error)
	mustEmbedUnimplementedQualityStatServiceServer()
}

// UnimplementedQualityStatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQualityStatServiceServer struct{}

func (UnimplementedQualityStatServiceServer) ListDefects(context.Context, *ListDefectsReq) (*ListDefectsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDefects not implemented")
}
func (UnimplementedQualityStatServiceServer) GetDefect(context.Context, *GetDefectReq) (*DefectInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefect not implemented")
}
func (UnimplementedQualityStatServiceServer) UpdateDefectStatus(context.Context, *UpdateDefectStatusReq) (*OperateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDefectStatus not implemented")
}
func (UnimplementedQualityStatServiceServer) GetQualityMetrics(context.Context, *GetMetricsReq) (*QualityMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQualityMetrics not implemented")
}
func (UnimplementedQualityStatServiceServer) GetUserStats(context.Context, *GetUserStatsReq) (*UserStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedQualityStatServiceServer) GetModuleDefectStats(context.Context, *GetModuleStatsReq) (*ModuleDefectStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModuleDefectStats not implemented")
}
func (UnimplementedQualityStatServiceServer) GetTechDebtStats(context.Context, *GetTechDebtReq) (*TechDebtStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTechDebtStats not implemented")
}
func (UnimplementedQualityStatServiceServer) GetDashboard(context.Context, *GetDashboardReq) (*DashboardData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedQualityStatServiceServer) GenerateReport(context.Context, *GenerateReportReq) (*ReportInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateReport not implemented")
}
func (UnimplementedQualityStatServiceServer) ListReports(context.Context, *ListReportsReq) (*ListReportsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReports not implemented")
}
func (UnimplementedQualityStatServiceServer) GetReportDownload(context.Context, *GetReportDownloadReq) (*ReportDownloadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReportDownload not implemented")
}
func (UnimplementedQualityStatServiceServer) mustEmbedUnimplementedQualityStatServiceServer() {}
func (UnimplementedQualityStatServiceServer) testEmbeddedByValue()                            {}

// UnsafeQualityStatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QualityStatServiceServer will
// result in compilation errors.
type UnsafeQualityStatServiceServer interface {
	mustEmbedUnimplementedQualityStatServiceServer()
}

func RegisterQualityStatServiceServer(s grpc.ServiceRegistrar, srv QualityStatServiceServer) {
	// If the following call panics, it indicates UnimplementedQualityStatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QualityStatService_ServiceDesc, srv)
}

func _QualityStatService_ListDefects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDefectsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).ListDefects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_ListDefects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).ListDefects(ctx, req.(*ListDefectsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_GetDefect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).GetDefect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_GetDefect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).GetDefect(ctx, req.(*GetDefectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_UpdateDefectStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDefectStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).UpdateDefectStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_UpdateDefectStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).UpdateDefectStatus(ctx, req.(*UpdateDefectStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_GetQualityMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).GetQualityMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_GetQualityMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).GetQualityMetrics(ctx, req.(*GetMetricsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).GetUserStats(ctx, req.(*GetUserStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_GetModuleDefectStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).GetModuleDefectStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_GetModuleDefectStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).GetModuleDefectStats(ctx, req.(*GetModuleStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_GetTechDebtStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTechDebtReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).GetTechDebtStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_GetTechDebtStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).GetTechDebtStats(ctx, req.(*GetTechDebtReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).GetDashboard(ctx, req.(*GetDashboardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_GenerateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).GenerateReport(ctx, req.(*GenerateReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_ListReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReportsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).ListReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_ListReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).ListReports(ctx, req.(*ListReportsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QualityStatService_GetReportDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportDownloadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualityStatServiceServer).GetReportDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QualityStatService_GetReportDownload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualityStatServiceServer).GetReportDownload(ctx, req.(*GetReportDownloadReq))
	}
	return interceptor(ctx, in, info, handler)
}

// QualityStatService_ServiceDesc is the grpc.ServiceDesc for QualityStatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QualityStatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crsystem.v1.QualityStatService",
	HandlerType: (*QualityStatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDefects",
			Handler:    _QualityStatService_ListDefects_Handler,
		},
		{
			MethodName: "GetDefect",
			Handler:    _QualityStatService_GetDefect_Handler,
		},
		{
			MethodName: "UpdateDefectStatus",
			Handler:    _QualityStatService_UpdateDefectStatus_Handler,
		},
		{
			MethodName: "GetQualityMetrics",
			Handler:    _QualityStatService_GetQualityMetrics_Handler,
		},
		{
			MethodName: "GetUserStats",
			Handler:    _QualityStatService_GetUserStats_Handler,
		},
		{
			MethodName: "GetModuleDefectStats",
			Handler:    _QualityStatService_GetModuleDefectStats_Handler,
		},
		{
			MethodName: "GetTechDebtStats",
			Handler:    _QualityStatService_GetTechDebtStats_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _QualityStatService_GetDashboard_Handler,
		},
		{
			MethodName: "GenerateReport",
			Handler:    _QualityStatService_GenerateReport_Handler,
		},
		{
			MethodName: "ListReports",
			Handler:    _QualityStatService_ListReports_Handler,
		},
		{
			MethodName: "GetReportDownload",
			Handler:    _QualityStatService_GetReportDownload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crsystem/v1/quality.proto",
}
