// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: crsystem/v1/quality.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListDefectsReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListDefectsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDefectsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListDefectsReqMultiError,
// or nil if none found.
func (m *ListDefectsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDefectsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ReviewId

	// no validation rules for ProjectId

	// no validation rules for DefectLevel

	// no validation rules for IsFixed

	// no validation rules for ModuleName

	// no validation rules for StatMonth

	if all {
		switch v := interface{}(m.GetStartTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListDefectsReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListDefectsReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListDefectsReqValidationError{
				field:  "StartTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListDefectsReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListDefectsReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListDefectsReqValidationError{
				field:  "EndTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListDefectsReqValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListDefectsReqValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListDefectsReqValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListDefectsReqMultiError(errors)
	}

	return nil
}

// ListDefectsReqMultiError is an error wrapping multiple validation errors
// returned by ListDefectsReq.ValidateAll() if the designated constraints
// aren't met.
type ListDefectsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDefectsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDefectsReqMultiError) AllErrors() []error { return m }

// ListDefectsReqValidationError is the validation error returned by
// ListDefectsReq.Validate if the designated constraints aren't met.
type ListDefectsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDefectsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDefectsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDefectsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDefectsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDefectsReqValidationError) ErrorName() string { return "ListDefectsReqValidationError" }

// Error satisfies the builtin error interface
func (e ListDefectsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDefectsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDefectsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDefectsReqValidationError{}

// Validate checks the field values on ListDefectsResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListDefectsResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDefectsResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDefectsRespMultiError, or nil if none found.
func (m *ListDefectsResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDefectsResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListDefectsRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListDefectsRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListDefectsRespValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListDefectsRespValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListDefectsRespValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListDefectsRespValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListDefectsRespMultiError(errors)
	}

	return nil
}

// ListDefectsRespMultiError is an error wrapping multiple validation errors
// returned by ListDefectsResp.ValidateAll() if the designated constraints
// aren't met.
type ListDefectsRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDefectsRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDefectsRespMultiError) AllErrors() []error { return m }

// ListDefectsRespValidationError is the validation error returned by
// ListDefectsResp.Validate if the designated constraints aren't met.
type ListDefectsRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDefectsRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDefectsRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDefectsRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDefectsRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDefectsRespValidationError) ErrorName() string { return "ListDefectsRespValidationError" }

// Error satisfies the builtin error interface
func (e ListDefectsRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDefectsResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDefectsRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDefectsRespValidationError{}

// Validate checks the field values on GetDefectReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetDefectReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDefectReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetDefectReqMultiError, or
// nil if none found.
func (m *GetDefectReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDefectReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DefectId

	if len(errors) > 0 {
		return GetDefectReqMultiError(errors)
	}

	return nil
}

// GetDefectReqMultiError is an error wrapping multiple validation errors
// returned by GetDefectReq.ValidateAll() if the designated constraints aren't met.
type GetDefectReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDefectReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDefectReqMultiError) AllErrors() []error { return m }

// GetDefectReqValidationError is the validation error returned by
// GetDefectReq.Validate if the designated constraints aren't met.
type GetDefectReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDefectReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDefectReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDefectReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDefectReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDefectReqValidationError) ErrorName() string { return "GetDefectReqValidationError" }

// Error satisfies the builtin error interface
func (e GetDefectReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDefectReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDefectReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDefectReqValidationError{}

// Validate checks the field values on DefectInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DefectInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DefectInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DefectInfoMultiError, or
// nil if none found.
func (m *DefectInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *DefectInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DefectId

	// no validation rules for ReviewId

	// no validation rules for CommentId

	// no validation rules for ReviewTitle

	// no validation rules for FilePath

	// no validation rules for LineNum

	// no validation rules for DefectLevel

	// no validation rules for Content

	// no validation rules for ModuleName

	// no validation rules for CreatorUid

	// no validation rules for CreatorName

	// no validation rules for IsFixed

	// no validation rules for FixedByUid

	if all {
		switch v := interface{}(m.GetFixTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DefectInfoValidationError{
					field:  "FixTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DefectInfoValidationError{
					field:  "FixTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFixTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DefectInfoValidationError{
				field:  "FixTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for StatMonth

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DefectInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DefectInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DefectInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DefectInfoMultiError(errors)
	}

	return nil
}

// DefectInfoMultiError is an error wrapping multiple validation errors
// returned by DefectInfo.ValidateAll() if the designated constraints aren't met.
type DefectInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DefectInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DefectInfoMultiError) AllErrors() []error { return m }

// DefectInfoValidationError is the validation error returned by
// DefectInfo.Validate if the designated constraints aren't met.
type DefectInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DefectInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DefectInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DefectInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DefectInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DefectInfoValidationError) ErrorName() string { return "DefectInfoValidationError" }

// Error satisfies the builtin error interface
func (e DefectInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDefectInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DefectInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DefectInfoValidationError{}

// Validate checks the field values on UpdateDefectStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateDefectStatusReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateDefectStatusReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateDefectStatusReqMultiError, or nil if none found.
func (m *UpdateDefectStatusReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateDefectStatusReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DefectId

	// no validation rules for IsFixed

	// no validation rules for OperatorUid

	if len(errors) > 0 {
		return UpdateDefectStatusReqMultiError(errors)
	}

	return nil
}

// UpdateDefectStatusReqMultiError is an error wrapping multiple validation
// errors returned by UpdateDefectStatusReq.ValidateAll() if the designated
// constraints aren't met.
type UpdateDefectStatusReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateDefectStatusReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateDefectStatusReqMultiError) AllErrors() []error { return m }

// UpdateDefectStatusReqValidationError is the validation error returned by
// UpdateDefectStatusReq.Validate if the designated constraints aren't met.
type UpdateDefectStatusReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateDefectStatusReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateDefectStatusReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateDefectStatusReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateDefectStatusReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateDefectStatusReqValidationError) ErrorName() string {
	return "UpdateDefectStatusReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateDefectStatusReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateDefectStatusReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateDefectStatusReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateDefectStatusReqValidationError{}

// Validate checks the field values on GetMetricsReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetMetricsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMetricsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetMetricsReqMultiError, or
// nil if none found.
func (m *GetMetricsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMetricsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for Period

	if all {
		switch v := interface{}(m.GetStartTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMetricsReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMetricsReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMetricsReqValidationError{
				field:  "StartTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMetricsReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMetricsReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMetricsReqValidationError{
				field:  "EndTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMetricsReqMultiError(errors)
	}

	return nil
}

// GetMetricsReqMultiError is an error wrapping multiple validation errors
// returned by GetMetricsReq.ValidateAll() if the designated constraints
// aren't met.
type GetMetricsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMetricsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMetricsReqMultiError) AllErrors() []error { return m }

// GetMetricsReqValidationError is the validation error returned by
// GetMetricsReq.Validate if the designated constraints aren't met.
type GetMetricsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMetricsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMetricsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMetricsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMetricsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMetricsReqValidationError) ErrorName() string { return "GetMetricsReqValidationError" }

// Error satisfies the builtin error interface
func (e GetMetricsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMetricsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMetricsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMetricsReqValidationError{}

// Validate checks the field values on QualityMetrics with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QualityMetrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QualityMetrics with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QualityMetricsMultiError,
// or nil if none found.
func (m *QualityMetrics) ValidateAll() error {
	return m.validate(true)
}

func (m *QualityMetrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReviewCompletionRate

	// no validation rules for DefectFixTimelyRate

	// no validation rules for TotalReviews

	// no validation rules for CompletedReviews

	// no validation rules for TotalDefects

	// no validation rules for FixedDefects

	// no validation rules for AvgFixHours

	// no validation rules for FatalDefects

	// no validation rules for CriticalDefects

	// no validation rules for MajorDefects

	// no validation rules for MinorDefects

	if len(errors) > 0 {
		return QualityMetricsMultiError(errors)
	}

	return nil
}

// QualityMetricsMultiError is an error wrapping multiple validation errors
// returned by QualityMetrics.ValidateAll() if the designated constraints
// aren't met.
type QualityMetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QualityMetricsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QualityMetricsMultiError) AllErrors() []error { return m }

// QualityMetricsValidationError is the validation error returned by
// QualityMetrics.Validate if the designated constraints aren't met.
type QualityMetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QualityMetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QualityMetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QualityMetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QualityMetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QualityMetricsValidationError) ErrorName() string { return "QualityMetricsValidationError" }

// Error satisfies the builtin error interface
func (e QualityMetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQualityMetrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QualityMetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QualityMetricsValidationError{}

// Validate checks the field values on GetUserStatsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetUserStatsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserStatsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserStatsReqMultiError, or nil if none found.
func (m *GetUserStatsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserStatsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for UserId

	// no validation rules for Period

	if all {
		switch v := interface{}(m.GetStartTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserStatsReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserStatsReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserStatsReqValidationError{
				field:  "StartTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserStatsReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserStatsReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserStatsReqValidationError{
				field:  "EndTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUserStatsReqMultiError(errors)
	}

	return nil
}

// GetUserStatsReqMultiError is an error wrapping multiple validation errors
// returned by GetUserStatsReq.ValidateAll() if the designated constraints
// aren't met.
type GetUserStatsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserStatsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserStatsReqMultiError) AllErrors() []error { return m }

// GetUserStatsReqValidationError is the validation error returned by
// GetUserStatsReq.Validate if the designated constraints aren't met.
type GetUserStatsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserStatsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserStatsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserStatsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserStatsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserStatsReqValidationError) ErrorName() string { return "GetUserStatsReqValidationError" }

// Error satisfies the builtin error interface
func (e GetUserStatsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserStatsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserStatsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserStatsReqValidationError{}

// Validate checks the field values on UserStats with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserStats) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserStats with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserStatsMultiError, or nil
// if none found.
func (m *UserStats) ValidateAll() error {
	return m.validate(true)
}

func (m *UserStats) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserStatsValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserStatsValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserStatsValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserStatsMultiError(errors)
	}

	return nil
}

// UserStatsMultiError is an error wrapping multiple validation errors returned
// by UserStats.ValidateAll() if the designated constraints aren't met.
type UserStatsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserStatsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserStatsMultiError) AllErrors() []error { return m }

// UserStatsValidationError is the validation error returned by
// UserStats.Validate if the designated constraints aren't met.
type UserStatsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserStatsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserStatsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserStatsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserStatsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserStatsValidationError) ErrorName() string { return "UserStatsValidationError" }

// Error satisfies the builtin error interface
func (e UserStatsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserStats.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserStatsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserStatsValidationError{}

// Validate checks the field values on UserStatItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserStatItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserStatItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserStatItemMultiError, or
// nil if none found.
func (m *UserStatItem) ValidateAll() error {
	return m.validate(true)
}

func (m *UserStatItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for UserName

	// no validation rules for ReviewCount

	// no validation rules for CompletionRate

	// no validation rules for DefectCount

	// no validation rules for FixedCount

	// no validation rules for AvgReviewHours

	if len(errors) > 0 {
		return UserStatItemMultiError(errors)
	}

	return nil
}

// UserStatItemMultiError is an error wrapping multiple validation errors
// returned by UserStatItem.ValidateAll() if the designated constraints aren't met.
type UserStatItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserStatItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserStatItemMultiError) AllErrors() []error { return m }

// UserStatItemValidationError is the validation error returned by
// UserStatItem.Validate if the designated constraints aren't met.
type UserStatItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserStatItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserStatItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserStatItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserStatItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserStatItemValidationError) ErrorName() string { return "UserStatItemValidationError" }

// Error satisfies the builtin error interface
func (e UserStatItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserStatItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserStatItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserStatItemValidationError{}

// Validate checks the field values on GetModuleStatsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetModuleStatsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModuleStatsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModuleStatsReqMultiError, or nil if none found.
func (m *GetModuleStatsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModuleStatsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ProjectId

	// no validation rules for Period

	if all {
		switch v := interface{}(m.GetStartTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetModuleStatsReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetModuleStatsReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetModuleStatsReqValidationError{
				field:  "StartTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetModuleStatsReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetModuleStatsReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetModuleStatsReqValidationError{
				field:  "EndTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetModuleStatsReqMultiError(errors)
	}

	return nil
}

// GetModuleStatsReqMultiError is an error wrapping multiple validation errors
// returned by GetModuleStatsReq.ValidateAll() if the designated constraints
// aren't met.
type GetModuleStatsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModuleStatsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModuleStatsReqMultiError) AllErrors() []error { return m }

// GetModuleStatsReqValidationError is the validation error returned by
// GetModuleStatsReq.Validate if the designated constraints aren't met.
type GetModuleStatsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModuleStatsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModuleStatsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModuleStatsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModuleStatsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModuleStatsReqValidationError) ErrorName() string {
	return "GetModuleStatsReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetModuleStatsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModuleStatsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModuleStatsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModuleStatsReqValidationError{}

// Validate checks the field values on ModuleDefectStats with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ModuleDefectStats) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModuleDefectStats with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModuleDefectStatsMultiError, or nil if none found.
func (m *ModuleDefectStats) ValidateAll() error {
	return m.validate(true)
}

func (m *ModuleDefectStats) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModuleDefectStatsValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModuleDefectStatsValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModuleDefectStatsValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ModuleDefectStatsMultiError(errors)
	}

	return nil
}

// ModuleDefectStatsMultiError is an error wrapping multiple validation errors
// returned by ModuleDefectStats.ValidateAll() if the designated constraints
// aren't met.
type ModuleDefectStatsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModuleDefectStatsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModuleDefectStatsMultiError) AllErrors() []error { return m }

// ModuleDefectStatsValidationError is the validation error returned by
// ModuleDefectStats.Validate if the designated constraints aren't met.
type ModuleDefectStatsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModuleDefectStatsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModuleDefectStatsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModuleDefectStatsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModuleDefectStatsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModuleDefectStatsValidationError) ErrorName() string {
	return "ModuleDefectStatsValidationError"
}

// Error satisfies the builtin error interface
func (e ModuleDefectStatsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModuleDefectStats.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModuleDefectStatsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModuleDefectStatsValidationError{}

// Validate checks the field values on ModuleStatItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ModuleStatItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModuleStatItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ModuleStatItemMultiError,
// or nil if none found.
func (m *ModuleStatItem) ValidateAll() error {
	return m.validate(true)
}

func (m *ModuleStatItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ModuleName

	// no validation rules for DefectCount

	// no validation rules for Percentage

	// no validation rules for MaxSeverity

	if len(errors) > 0 {
		return ModuleStatItemMultiError(errors)
	}

	return nil
}

// ModuleStatItemMultiError is an error wrapping multiple validation errors
// returned by ModuleStatItem.ValidateAll() if the designated constraints
// aren't met.
type ModuleStatItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModuleStatItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModuleStatItemMultiError) AllErrors() []error { return m }

// ModuleStatItemValidationError is the validation error returned by
// ModuleStatItem.Validate if the designated constraints aren't met.
type ModuleStatItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModuleStatItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModuleStatItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModuleStatItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModuleStatItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModuleStatItemValidationError) ErrorName() string { return "ModuleStatItemValidationError" }

// Error satisfies the builtin error interface
func (e ModuleStatItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModuleStatItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModuleStatItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModuleStatItemValidationError{}

// Validate checks the field values on GetTechDebtReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetTechDebtReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTechDebtReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetTechDebtReqMultiError,
// or nil if none found.
func (m *GetTechDebtReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTechDebtReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return GetTechDebtReqMultiError(errors)
	}

	return nil
}

// GetTechDebtReqMultiError is an error wrapping multiple validation errors
// returned by GetTechDebtReq.ValidateAll() if the designated constraints
// aren't met.
type GetTechDebtReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTechDebtReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTechDebtReqMultiError) AllErrors() []error { return m }

// GetTechDebtReqValidationError is the validation error returned by
// GetTechDebtReq.Validate if the designated constraints aren't met.
type GetTechDebtReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTechDebtReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTechDebtReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTechDebtReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTechDebtReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTechDebtReqValidationError) ErrorName() string { return "GetTechDebtReqValidationError" }

// Error satisfies the builtin error interface
func (e GetTechDebtReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTechDebtReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTechDebtReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTechDebtReqValidationError{}

// Validate checks the field values on TechDebtStats with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TechDebtStats) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TechDebtStats with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TechDebtStatsMultiError, or
// nil if none found.
func (m *TechDebtStats) ValidateAll() error {
	return m.validate(true)
}

func (m *TechDebtStats) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalUnfixed

	// no validation rules for FatalUnfixed

	// no validation rules for CriticalUnfixed

	// no validation rules for DebtScore

	for idx, item := range m.GetTopModules() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TechDebtStatsValidationError{
						field:  fmt.Sprintf("TopModules[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TechDebtStatsValidationError{
						field:  fmt.Sprintf("TopModules[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TechDebtStatsValidationError{
					field:  fmt.Sprintf("TopModules[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TechDebtStatsMultiError(errors)
	}

	return nil
}

// TechDebtStatsMultiError is an error wrapping multiple validation errors
// returned by TechDebtStats.ValidateAll() if the designated constraints
// aren't met.
type TechDebtStatsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TechDebtStatsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TechDebtStatsMultiError) AllErrors() []error { return m }

// TechDebtStatsValidationError is the validation error returned by
// TechDebtStats.Validate if the designated constraints aren't met.
type TechDebtStatsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TechDebtStatsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TechDebtStatsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TechDebtStatsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TechDebtStatsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TechDebtStatsValidationError) ErrorName() string { return "TechDebtStatsValidationError" }

// Error satisfies the builtin error interface
func (e TechDebtStatsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTechDebtStats.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TechDebtStatsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TechDebtStatsValidationError{}

// Validate checks the field values on GetDashboardReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDashboardReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDashboardReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDashboardReqMultiError, or nil if none found.
func (m *GetDashboardReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDashboardReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for Period

	if all {
		switch v := interface{}(m.GetStartTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDashboardReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDashboardReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDashboardReqValidationError{
				field:  "StartTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDashboardReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDashboardReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDashboardReqValidationError{
				field:  "EndTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetDashboardReqMultiError(errors)
	}

	return nil
}

// GetDashboardReqMultiError is an error wrapping multiple validation errors
// returned by GetDashboardReq.ValidateAll() if the designated constraints
// aren't met.
type GetDashboardReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDashboardReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDashboardReqMultiError) AllErrors() []error { return m }

// GetDashboardReqValidationError is the validation error returned by
// GetDashboardReq.Validate if the designated constraints aren't met.
type GetDashboardReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDashboardReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDashboardReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDashboardReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDashboardReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDashboardReqValidationError) ErrorName() string { return "GetDashboardReqValidationError" }

// Error satisfies the builtin error interface
func (e GetDashboardReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDashboardReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDashboardReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDashboardReqValidationError{}

// Validate checks the field values on DashboardData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DashboardData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DashboardData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DashboardDataMultiError, or
// nil if none found.
func (m *DashboardData) ValidateAll() error {
	return m.validate(true)
}

func (m *DashboardData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMetrics()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DashboardDataValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DashboardDataValidationError{
					field:  "Metrics",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetrics()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DashboardDataValidationError{
				field:  "Metrics",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetReviewTrend() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DashboardDataValidationError{
						field:  fmt.Sprintf("ReviewTrend[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DashboardDataValidationError{
						field:  fmt.Sprintf("ReviewTrend[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DashboardDataValidationError{
					field:  fmt.Sprintf("ReviewTrend[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetDefectTrend() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DashboardDataValidationError{
						field:  fmt.Sprintf("DefectTrend[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DashboardDataValidationError{
						field:  fmt.Sprintf("DefectTrend[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DashboardDataValidationError{
					field:  fmt.Sprintf("DefectTrend[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetModuleDistribution() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DashboardDataValidationError{
						field:  fmt.Sprintf("ModuleDistribution[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DashboardDataValidationError{
						field:  fmt.Sprintf("ModuleDistribution[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DashboardDataValidationError{
					field:  fmt.Sprintf("ModuleDistribution[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetTopReviewers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DashboardDataValidationError{
						field:  fmt.Sprintf("TopReviewers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DashboardDataValidationError{
						field:  fmt.Sprintf("TopReviewers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DashboardDataValidationError{
					field:  fmt.Sprintf("TopReviewers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DashboardDataMultiError(errors)
	}

	return nil
}

// DashboardDataMultiError is an error wrapping multiple validation errors
// returned by DashboardData.ValidateAll() if the designated constraints
// aren't met.
type DashboardDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DashboardDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DashboardDataMultiError) AllErrors() []error { return m }

// DashboardDataValidationError is the validation error returned by
// DashboardData.Validate if the designated constraints aren't met.
type DashboardDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DashboardDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DashboardDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DashboardDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DashboardDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DashboardDataValidationError) ErrorName() string { return "DashboardDataValidationError" }

// Error satisfies the builtin error interface
func (e DashboardDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDashboardData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DashboardDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DashboardDataValidationError{}

// Validate checks the field values on TrendPoint with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TrendPoint) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TrendPoint with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TrendPointMultiError, or
// nil if none found.
func (m *TrendPoint) ValidateAll() error {
	return m.validate(true)
}

func (m *TrendPoint) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Date

	// no validation rules for Count

	if len(errors) > 0 {
		return TrendPointMultiError(errors)
	}

	return nil
}

// TrendPointMultiError is an error wrapping multiple validation errors
// returned by TrendPoint.ValidateAll() if the designated constraints aren't met.
type TrendPointMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TrendPointMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TrendPointMultiError) AllErrors() []error { return m }

// TrendPointValidationError is the validation error returned by
// TrendPoint.Validate if the designated constraints aren't met.
type TrendPointValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TrendPointValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TrendPointValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TrendPointValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TrendPointValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TrendPointValidationError) ErrorName() string { return "TrendPointValidationError" }

// Error satisfies the builtin error interface
func (e TrendPointValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTrendPoint.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TrendPointValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TrendPointValidationError{}

// Validate checks the field values on GenerateReportReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GenerateReportReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateReportReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateReportReqMultiError, or nil if none found.
func (m *GenerateReportReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateReportReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ReportType

	// no validation rules for Format

	// no validation rules for StatMonth

	if all {
		switch v := interface{}(m.GetStartTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateReportReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateReportReqValidationError{
					field:  "StartTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateReportReqValidationError{
				field:  "StartTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateReportReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateReportReqValidationError{
					field:  "EndTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateReportReqValidationError{
				field:  "EndTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GenerateReportReqMultiError(errors)
	}

	return nil
}

// GenerateReportReqMultiError is an error wrapping multiple validation errors
// returned by GenerateReportReq.ValidateAll() if the designated constraints
// aren't met.
type GenerateReportReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateReportReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateReportReqMultiError) AllErrors() []error { return m }

// GenerateReportReqValidationError is the validation error returned by
// GenerateReportReq.Validate if the designated constraints aren't met.
type GenerateReportReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateReportReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateReportReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateReportReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateReportReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateReportReqValidationError) ErrorName() string {
	return "GenerateReportReqValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateReportReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateReportReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateReportReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateReportReqValidationError{}

// Validate checks the field values on ReportInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReportInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReportInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReportInfoMultiError, or
// nil if none found.
func (m *ReportInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ReportInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReportId

	// no validation rules for TenantId

	// no validation rules for ReportType

	// no validation rules for Format

	// no validation rules for Title

	// no validation rules for FileUrl

	// no validation rules for Status

	// no validation rules for CreatorUid

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReportInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReportInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReportInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReportInfoMultiError(errors)
	}

	return nil
}

// ReportInfoMultiError is an error wrapping multiple validation errors
// returned by ReportInfo.ValidateAll() if the designated constraints aren't met.
type ReportInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReportInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReportInfoMultiError) AllErrors() []error { return m }

// ReportInfoValidationError is the validation error returned by
// ReportInfo.Validate if the designated constraints aren't met.
type ReportInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReportInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReportInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReportInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReportInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReportInfoValidationError) ErrorName() string { return "ReportInfoValidationError" }

// Error satisfies the builtin error interface
func (e ReportInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReportInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReportInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReportInfoValidationError{}

// Validate checks the field values on ListReportsReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListReportsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReportsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListReportsReqMultiError,
// or nil if none found.
func (m *ListReportsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReportsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ReportType

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListReportsReqValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListReportsReqValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListReportsReqValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListReportsReqMultiError(errors)
	}

	return nil
}

// ListReportsReqMultiError is an error wrapping multiple validation errors
// returned by ListReportsReq.ValidateAll() if the designated constraints
// aren't met.
type ListReportsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReportsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReportsReqMultiError) AllErrors() []error { return m }

// ListReportsReqValidationError is the validation error returned by
// ListReportsReq.Validate if the designated constraints aren't met.
type ListReportsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReportsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReportsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReportsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReportsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReportsReqValidationError) ErrorName() string { return "ListReportsReqValidationError" }

// Error satisfies the builtin error interface
func (e ListReportsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReportsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReportsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReportsReqValidationError{}

// Validate checks the field values on ListReportsResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListReportsResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListReportsResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListReportsRespMultiError, or nil if none found.
func (m *ListReportsResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ListReportsResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListReportsRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListReportsRespValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListReportsRespValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListReportsRespValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListReportsRespValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListReportsRespValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListReportsRespMultiError(errors)
	}

	return nil
}

// ListReportsRespMultiError is an error wrapping multiple validation errors
// returned by ListReportsResp.ValidateAll() if the designated constraints
// aren't met.
type ListReportsRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListReportsRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListReportsRespMultiError) AllErrors() []error { return m }

// ListReportsRespValidationError is the validation error returned by
// ListReportsResp.Validate if the designated constraints aren't met.
type ListReportsRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListReportsRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListReportsRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListReportsRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListReportsRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListReportsRespValidationError) ErrorName() string { return "ListReportsRespValidationError" }

// Error satisfies the builtin error interface
func (e ListReportsRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListReportsResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListReportsRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListReportsRespValidationError{}

// Validate checks the field values on GetReportDownloadReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetReportDownloadReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetReportDownloadReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetReportDownloadReqMultiError, or nil if none found.
func (m *GetReportDownloadReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetReportDownloadReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReportId

	if len(errors) > 0 {
		return GetReportDownloadReqMultiError(errors)
	}

	return nil
}

// GetReportDownloadReqMultiError is an error wrapping multiple validation
// errors returned by GetReportDownloadReq.ValidateAll() if the designated
// constraints aren't met.
type GetReportDownloadReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetReportDownloadReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetReportDownloadReqMultiError) AllErrors() []error { return m }

// GetReportDownloadReqValidationError is the validation error returned by
// GetReportDownloadReq.Validate if the designated constraints aren't met.
type GetReportDownloadReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetReportDownloadReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetReportDownloadReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetReportDownloadReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetReportDownloadReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetReportDownloadReqValidationError) ErrorName() string {
	return "GetReportDownloadReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetReportDownloadReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetReportDownloadReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetReportDownloadReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetReportDownloadReqValidationError{}

// Validate checks the field values on ReportDownloadResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReportDownloadResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReportDownloadResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReportDownloadRespMultiError, or nil if none found.
func (m *ReportDownloadResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ReportDownloadResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DownloadUrl

	if all {
		switch v := interface{}(m.GetExpireAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReportDownloadRespValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReportDownloadRespValidationError{
					field:  "ExpireAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpireAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReportDownloadRespValidationError{
				field:  "ExpireAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReportDownloadRespMultiError(errors)
	}

	return nil
}

// ReportDownloadRespMultiError is an error wrapping multiple validation errors
// returned by ReportDownloadResp.ValidateAll() if the designated constraints
// aren't met.
type ReportDownloadRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReportDownloadRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReportDownloadRespMultiError) AllErrors() []error { return m }

// ReportDownloadRespValidationError is the validation error returned by
// ReportDownloadResp.Validate if the designated constraints aren't met.
type ReportDownloadRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReportDownloadRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReportDownloadRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReportDownloadRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReportDownloadRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReportDownloadRespValidationError) ErrorName() string {
	return "ReportDownloadRespValidationError"
}

// Error satisfies the builtin error interface
func (e ReportDownloadRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReportDownloadResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReportDownloadRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReportDownloadRespValidationError{}
